<div class="block"><span class="pink">Offene Posten:</span>
<hr class="light" />
<ul style="margin-top: 0;">
	<li class="active"
		onmouseover="document.getElementById('guest_has_payed_1').style.display='inline';"
		onmouseout="document.getElementById('guest_has_payed_1').style.display='none';">
	<span class="title">Maximilian Mustermann</span><br />
	2 Cocktails, 5,50 Euro <input type="button" class="pink right"
		id="guest_has_payed_1" value="hat bezhalt" name="action"
		style="display: none;" />
	<hr class="light" />
	</li>
	<li
		onmouseover="document.getElementById('guest_has_payed_2').style.display='inline';"
		onmouseout="document.getElementById('guest_has_payed_2').style.display='none';">
	<span class="title">Kurt Krause</span><br />
	1 Cocktail, 2,00 Euro <input type="button" class="pink right"
		id="guest_has_payed_2" value="hat bezhalt" name="action"
		style="display: none;" />
	<hr class="light" />
	</li>
	<li
		onmouseover="document.getElementById('guest_has_payed_3').style.display='inline';"
		onmouseout="document.getElementById('guest_has_payed_3').style.display='none';">
	<span class="title">Caroline Bock</span><br />
	0 Cocktails, 0,00 Euro <input type="button" class="pink right"
		id="guest_has_payed_3" value="hat bezhalt" name="action"
		style="display: none;" />
	<hr class="light" />
	</li>
</ul>
<p class="block_info_guests">Anzahl Gäste: 3<br />
<input type="button" class="pink left margin_top" value="&lt; zurück"
	name="action" /> <input type="button" class="pink right margin_top"
	value="weiter &gt;" name="action" /><br />
</p>
<hr class="bottom_divider" />
<p class="switch_party">Party wechseln: <select class="switch_party">
	<option>Hawaii Party</option>
</select></p>
</div>
<div class="cash">
<p class="center"><strong>Tabas Bar <br />
Kleiststraße 21 <br />
70197 Stuttgart</strong></p>
<p class="center"><em>Hawaii Party</em></p>
<p>Gast: Maximilian Mustermann</p>
<p>1x Cuba Libre <span class="right">2,00 Euro </span><br />
1x Mai Tai <span class="right">2,50 Euro </span><br />
=================================== <br />
Gesamt <span class="right">7,50 Euro</span></p>
<p class="smaller">Es bediente dich: <span class="right">Thomas Bachmann</span></p>
<p class="smaller">Datum und Uhrzeit: <span class="right">28.08.2010, 23:55 Uhr</span></p>
<p class="center" style="margin-top: 4em;">Vielen Dank für deinen Besuch! Bis zum nächstem Mal!</p>
<p class="center smaller" style="bottom: 35px; left: 445px; position: absolute;">Ein Service von www.cocktailberater.de.</p>
<p class="center"><input type="submit" value="Drucken" name="action" class="pink" style="bottom: 20px; left: 530px; position: absolute;" /></p>
</div>
