<h3>Barkunde</h3>
<p>Um Barkeeper zu werden bedarf es einer Menge Wissen. Alles Wissen
rund um die Bar wird in unserer Barkunde festgehalten.</p>
<ul>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'nutrition')); ?>">Nährwerttabelle</a> mit den Kalorien für
	alle Cocktails.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'glas')); ?>">Gläserkunde</a> mit den passenden Gläsern zu
	jedem Cocktail.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'utensilien')); ?>">Utensilien</a> zum Zubereiten von
	Cocktails.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'mixtechniken')); ?>">Mixtechniken</a> damit jeder Cocktail
	zum Genuss wird.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'grundausstattung')); ?>">Grundausstattung</a> um die erste
	eigene Bar einzurichten.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'ingredient',
		'action'=>'index')); ?>">Zutaten</a> mit Beschreibungen, passenden
	Produkten und Rezepten</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'manufacturer',
		'action'=>'index')); ?>">Hersteller</a> mit Beschreibungen, ihren
	Produkten und Rezepten</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'product',
		'action'=>'index')); ?>">Warenkunde</a> mit Beschreibungen und Rezepten</li>
	<li>Empfehlenswerte <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'buecher')); ?>">Bücher</a> rund um das Thema Cocktails.</li>
	<li>Andere <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'andere-seiten')); ?>">Cocktailseiten</a> mit interessanten
	Rezepten.</li>
</ul>
