<?php
$format = Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html');
?>
<ul class="textLeft no-bullet-html">
<?php foreach($this->container as /*@var $page Zend_Navigation_Page_Mvc */$page) { ?>
	<li <?php print $page->isActive(true) ? ' class="active"' : ''; ?>><a
		href="<?php print $page->getHref(); ?>?format=<?php print $format; ?>"><?php print $page->getLabel(); ?></a>
	<ul class="no-bullet-html">
	<?php foreach($page->getPages() as /*@var $page Zend_Navigation_Page_Mvc */$subPage) { ?>
		<li <?php print $subPage->isActive(true) ? ' class="active"' : ''; ?>><a
			href="<?php print $subPage->getHref(); ?>?format=<?php print $format; ?>"><?php print $subPage->getLabel(); ?></a>
		<ul class="no-bullet-html">
		<?php foreach($subPage->getPages() as /*@var $page Zend_Navigation_Page_Mvc */$subSubPage) { ?>
			<li
			<?php print $subSubPage->isActive(true) ? ' class="active"' : ''; ?>><a
				href="<?php print $subSubPage->getHref(); ?>?format=<?php print $format; ?>"><?php print $subSubPage->getLabel(); ?></a>
			<ul class="no-bullet-html">
			<?php foreach($subSubPage->getPages() as /*@var $page Zend_Navigation_Page_Mvc */$subSubSubPage) { ?>
				<li
				<?php print $subSubSubPage->isActive(true) ? ' class="active"' : ''; ?>><a
					href="<?php print $subSubSubPage->getHref(); ?>?format=<?php print $format; ?>"><?php print $subSubSubPage->getLabel(); ?></a></li>
					<?php } ?>
			</ul>
			</li>
			<?php } ?>
		</ul>
		</li>
		<?php } ?>
	</ul>
	</li>
	<?php } ?>
</ul>
