<div class="sub_nav">
<ul class="textLeft">
	<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'community'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Community</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'cocktail-der-woche'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Cocktail der Woche</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'top10-drinks'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Top 10 Drinks</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'forum'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Forum</a></li>
	</ul></li> -->
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'hausbar'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Party Helferlein</a>
	<ul>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'login'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Anmelden / Login</a></li> -->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Hausbar</a></li>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-favoriten'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Meine Favoriten</a></li> -->
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-cocktails'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Meine Cocktails</a></li> -->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Cocktailkarte</a></li>
	</ul></li>
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'barkunde'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Barkunde</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'nutrition'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Nährwerte</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'glas'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Gläser</a></li>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'utensilien'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Utensilien</a></li>-->
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'mixtechniken'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Mixtechniken</a></li>-->
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'grundausstattung'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Grundausstattung</a></li>-->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'ingredient','action'=>'index'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Zutaten</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'manufacturer','action'=>'index'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Hersteller</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'product','action'=>'index'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Warenkunde</a></li>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'buecher'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">Buchempfehlungen</a></li> -->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'andere-seiten'),null,true); ?>?format=<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html'); ?>">andere Cocktailseiten</a></li>
	</ul></li>
</ul>
</div>
