<?php
Zend_Debug::dump($this);
exit;
$photos = Website_Model_Photo::photosByRecipeId($this->id); ?>
<div id="cocktail" style="width: 100px; height: 150px"><a
	href="<?php print $this->url(
	array('controller'=>'index','action'=>'recipe','cocktail'=>$this->name,'id'=>$this->id),null,true); ?>"><img
	style="height: 100px;" src="<?php print $this->baseUrl();
	if(isset($photos[0]) && $photos[0]->id){
		print '/img/recipes/'.$this->escape($photos[0]->fileName);
	} else { 
		print '/img/wikilogo.png';
	} ?>" /></a><a
	id="mylink<?php print $this->id; ?>"
	href="<?php print $this->url(array('controller'=>'index','action'=>'recipe-preview','cocktail'=>$this->name,'id'=>$this->id),null,true); ?>?width=140"
	class="betterTip"
	onclick="location.href='<?php print $this->url(array('controller'=>'index','action'=>'recipe','cocktail'=>$this->name,'id'=>$this->id),null,true); ?>'"
	title="<?php echo $this->escape(str_replace('\\','',$this->name)) ?>"><img
	src="<?php print $this->baseUrl(); ?>/img/info.png" align="top" /></a><br />
<a
	href="<?php print $this->url(array('controller'=>'index','action'=>'recipe','cocktail'=>$this->name,'id'=>$this->id),null,true); ?>">
<?php if(isset($mode) && $mode=='top10') {
	print '#'.$top.' - ';
}
echo $this->escape(str_replace('\\','',$this->name));
if(isset($mode) && $mode=='top10') {
	//print ' - Bewertung: '.number_format($cocktail->bewertungs_summe/$cocktail->bewertungs_anzahl,2,',',NULL);
}
?></a></div>
