<?php
	
$entries[] = array(
	'title'       	=> $this->party->name,
	'link'        	=> $this->url(array(
		'id'			=>$this->party->id,
		'format'		=>$this->format)),
	'description' 	=> $this->party->getBar()->name."<br /><br />".$this->party->getHost()->firstname.' '.$this->party->getHost()->lastname."<br />".$this->party->date,
);

// Create the RSS array
$rss = array(
	'title'   => 'cocktailberater',
	'link'    => 'http://www.cocktailberater.de',
	'charset' => 'UTF-8',
	'entries' => $entries
);

// Import the array
$feed = Zend_Feed::importArray($rss, $this->format);
print $feed->saveXML();