<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$partysXML = $this->xml->createElement('partys');
if(is_array($this->partys)){
	foreach ($this->partys as $party){
		$party->toXml($this->xml,$partysXML);
	}
}
// set count for recipe element according to number of recipes found
$partysXML->setAttribute('count',count($this->partys));
// add the '$recipes' element to the 'rsp' element
$this->rsp->appendChild($partysXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
