<div id="spacing-left">
<h1>Cache gelöscht</h1>
<p>Am besten gleich neu erstellen:</p>
<ul>
	<li><a
		href="<?php echo $this->url(array('action'=>'index','controller'=>'recipe')) ?>">Rezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('action'=>'index','controller'=>'cocktail')) ?>">Cocktails</a></li>
	<li><a
		href="<?php echo $this->url(array('action'=>'index','controller'=>'ingredient')) ?>">Zutaten</a></li>
</ul>
</div>
