<h3>Community</h3>
<p>Die cocktailberater Community hilft den cocktailberater stets zu
verbessern. Neue Rezepte, Bewertungen, Tags/Schlagworte, Wissen für die
BarKunde etc. sorgen stets für anspruchsvolle Inhalte.</p>
<ul>
	<li>Finde heraus was der <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'cocktail-der-woche')); ?>">Cocktail
	der Woche</a> ist.</li>
	<li>Was sind eigentlich die <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'top10-drinks')); ?>">Top
	10 Drinks</a> im cocktailberater?</li>
	<li>Diskutiere mit im cocktailberater <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'forum')); ?>">Forum</a>.</li>
</ul>
