<?php
$de = new Zend_Locale('de_DE');
$latestInsertDate = new Zend_Date('2000-01-01',$de);
$publishedDate = new Zend_Date(Zend_Date::now(),$de);
// ratings
if(is_array($this->ratings)){
	foreach($this->ratings as /* @var $rating Website_Model_Rating */ $rating){
		$date = new Zend_Date($rating->insertDate,Zend_Date::ISO_8601);
		// update latest insert date (for feed attribute)
		if($date->isLater($latestInsertDate)){
			$latestInsertDate = $date;
		}
		$entries[] = $rating->toFeedEntry();
	}
}

// Create the RSS array
$rss = array(
	'title'   		=> 	'Liste aller Bewertungen - cocktailberater.de',
	'description'	=>	'Alle Bewertungen des cocktailberaters.',
	'link'    		=> 	$this->url().'?format='.$this->format,
	'author'		=>	'cocktailberater.de '.APPLICATION_VERSION,
	'email'			=>	'info@cocktailberater.de',
	'webmaster'		=>	'info@thobach.de',
	'image'			=>	$this->baseUrl().'/img/logo.png',
	'generator'		=>	'cocktailberater '.APPLICATION_VERSION,
	'language'		=>	'de',
	'published'		=> 	$publishedDate->getTimestamp(),
	'lastUpdate'	=> 	$latestInsertDate->getTimestamp(),
	'charset' 		=> 	'UTF-8',
	'entries' 		=> 	$entries
);

// Import the array
$feed = Zend_Feed::importArray($rss, $this->format);
print $feed->saveXML();