<?php
/**
 * Mobile Sitemap XML File for search engines
 */
if($this->pages){
	echo str_replace('xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"','xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"',
			str_replace('</url>','<mobile:mobile/></url>',
				str_replace('</loc>','?format=mobile</loc>',
					$this->navigation($this->pages)->sitemap()->setFormatOutput(true))));
}