<p class="left" style="margin: 1em 0 1em 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
            	'pages'      => array(
		            array(
		                'label'      => 'Barkunde',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'barkunde',
		    			'pages'      => array(
				            array(
				                'label'      => 'Hersteller',
				                'module'     => 'website',
				            	'action'	 => 'index',
				                'controller' => 'manufacturer',
				            	'pages'      => array(
				                    array(
				                        'label'      => $this->manufacturer->name,
				                        'module'     => 'website',
				                        'controller' => 'manufacturer',
				                        'action'     => 'get'
				                    )
				                )
				            )
				    	)
					)
				)
        	)
    	)
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?> (<a href="#recipes-list">Cocktailrezepte</a> und 
<a href="#products-list">Produkte</a>)</p>
<h2 style="margin-top: 0;"><?php print $this->manufacturer->name; ?></h2>
<div>
<h3 style="margin-top: 0; margin-bottom: 0.5em;">Hersteller/Marken-Informationen</h3>
<?php if($this->manufacturer->country){ ?>
<div class="attribut">Land:</div>
<div class="wert"><?php print $this->manufacturer->country; ?></div>
<?php }
if($this->manufacturer->website){ ?>
<div class="attribut">Webseite:</div>
<div class="wert"><?php print '<a href="'.$this->manufacturer->website.'">'.$this->manufacturer->website.'</a>'; ?></div>
<?php } ?>
<h3 class="clear left" id="products-list" style="margin-bottom: 0.7em;"><?php print $this->manufacturer->name; ?> Produkte</h3>
<ul class="clear">
<?php
if(is_array($this->manufacturer->getProducts())){
	foreach ($this->manufacturer->getProducts() as $product){ ?>
	<li
		style="text-align: center; float: left; clear: none; width: 130px; height: 130px; padding-right: 1em; padding-bottom: 1em;"><a
		href="<?php echo $this->url(
		array('controller'=>'product',
		'action'=>'get',
		'module'=>'website',
		'id'=>$product->getUniqueName())); ?>?format=mobile"><span
		style="width: 80px; height: 80px;"><img
		src="<?php echo ($product->getImage() ? $product->getImage() : '/img/bottle.png'); ?>"
		style="max-width: 80px; max-height: 80px;"
		alt="<?php echo $this->manufacturer->name.' '.$product->name; ?>" /></span><br />
		<?php echo $product->name; ?></a><br />(<a
		href="<?php echo $this->url(
		array('controller'=>'ingredient',
		'action'=>'get',
		'module'=>'website',
		'id'=>$product->getIngredient()->getUniqueName())); ?>?format=mobile"><?php
		echo $product->getIngredient()->name; ?></a>)</li>
		<?php } 
} ?>
</ul>
<?php if($this->manufacturer->getRecipes()){ ?>
<h3 class="clear left" style="margin-bottom: 1.7em;" id="recipes-list">Cocktailrezepte mit Zutaten von <?php print $this->manufacturer->name; ?></h3>
<ul class="clear">
<?php foreach ($this->manufacturer->getRecipes() as $recipe){ ?>
	<li style="float: left; clear: none;"><?php $this->cocktailPreview($recipe)?></li>
	<?php } ?>
</ul>
<?php } ?>
</div>
