<div class="content">
<h2><?php print $this->manufacturer->name; ?></h2>
<p>Gehe direkt zu <a href="#recipes-list">Cocktailrezepte</a> und 
<a href="#products-list">Produkte</a></p>
<h3>Hersteller/Marken-Informationen</h3>
<?php if($this->manufacturer->country){ ?>
<div class="attribut">Land:</div>
<div class="wert"><?php print $this->manufacturer->country; ?></div>
<?php }
if($this->manufacturer->website){ ?>
<div class="attribut">Webseite:</div>
<div class="wert"><?php print '<a href="'.$this->manufacturer->website.'">'.$this->manufacturer->website.'</a>'; ?></div>
<?php } ?>
<h3 id="products-list"><?php print $this->manufacturer->name; ?> Produkte</h3>
<ul class="no-bullet" style="margin-left: 0;">
<?php
if(is_array($this->manufacturer->getProducts())){
	foreach ($this->manufacturer->getProducts() as $product){ 
		$this->productPreview($product);
	} 
} ?>
</ul>
<?php if($this->manufacturer->getRecipes()){ ?>
<h3 id="recipes-list">Cocktailrezepte mit Zutaten von <?php print $this->manufacturer->name; ?></h3>
<ul class="no-bullet abstand_oben">
<?php foreach ($this->manufacturer->getRecipes() as $recipe){ ?>
	<li style="float: left; clear: none;"><?php $this->cocktailPreview($recipe)?></li>
	<?php } ?>
</ul>
<?php } ?>
</div>
