<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$ordersXML = $this->xml->createElement('orders');
if(is_array($this->orders)){
	foreach ($this->orders as $order){
		$order->toXml($this->xml,$ordersXML);
	}
}
// set count for recipe element according to number of recipes found
$ordersXML->setAttribute('count',count($this->orders));
// add the '$recipes' element to the 'rsp' element
$this->rsp->appendChild($ordersXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
