<?php
foreach ($this->orders as $order){
	$entries[] = array(
		'title'       => $order->getRecipe()->name.' für '.$order->getMember()->firstname.' '.$order->getMember()->lastname,
		'link'        => $this->url(array(
			'id'		=>$order->id,
			'format'	=>$this->format)),
		'description' => '',
	);

}

// Create the RSS array
$rss = array(
	'title'   => 'cocktailberater',
	'link'    => 'http://www.cocktailberater.de',
	'charset' => 'UTF-8',
	'entries' => $entries
);

// Import the array
$feed = Zend_Feed::importArray($rss, $this->format);
print $feed->saveXML();