<div id="hinweis"><?=$this->message; ?></div>

<form class="regular_form" style="width:38em; margin-left: 2em;" method="post">
	<fieldset>
		<legend>Produktinformationen</legend>
		<label class="attribut" for="product_name">Produktname</label>
		<input class="q2 wert" name="product_name" id="product_name" value="<?=$this->product_name;?>"/>
		<label class="attribut" for="product_group">Produktgruppe  (<a href="<?=$this->url(array('action'=>'add-ingredient'));?>">neu</a>)</label>
		<select class="q2 wert" style="width:auto" name="product_group" id="product_group">
		<?php foreach($this->ingredients as $ingredient){ ?>
			<option value="<?php print $ingredient->id; ?>"><?php print $ingredient->name; ?></option>
		<?php } ?>
		</select>
		<label class="attribut" for="manufacturer">Hersteller</label>
		<input class="q2 wert" name="manufacturer" id="manufacturer" value="<?=$this->manufacturer;?>"/>
		<label class="attribut" for="amount">Menge</label>
		<input class="wert small"  name="amount" id="amount" value="<?=$this->amount;?>"/> 
		<select class="q2 wert" style="width:auto" name="unit" id="unit">
			<option value="l" selected="selected">Liter</option>
			<option value="g">Gramm</option>
		</select>
		<label class="attribut" for="alcohol_level">Alkoholgehalt</label>
		<div class="wert"><input class="small" name="alcohol_level" id="alcohol_level" value="<?=$this->alcohol_level;?>"/> %</div>
		<label class="attribut" for="fruit_concentration">Fruchtgehalt</label>
		<div class="wert"><input class="small" name="fruit_concentration" id="fruit_concentration" value="<?=$this->fruit_concentration;?>"/> %</div>
		<label class="attribut" for="calories_kcal">Kalorien</label>
		<div class="wert"><input class="small" name="calories_kcal" id="calories_kcal" value="<?=$this->calories_kcal;?>"/> kcal</div>
		<label class="attribut" for="density_gcm3">Dichte</label>
		<div class="wert"><input class="small" name="density_gcm3" id="density_gcm3" value="<?=$this->density_gcm3;?>"/> g/cm<sup>3</sup></div>
		<label class="attribut" for="additional_information">Zusatz-informationen</label>
		<div class="wert"><textarea id="additional_information" class="text wert" name="additional_information" ><?=$this->additional_information;?></textarea>(z.B. Standardprodukt für Cola)</div>
		<label class="attribut" for="additional_information">Optionen</label>
		<div class="wert">
			<input class="q2 wert submit" style="float: left" type="submit" name="reset" value="&nbsp;&nbsp;&nbsp;Reset"/>
			<input class="q2 wert submit" style="float: right" type="submit" name="save_product" value="Speichern"/>
		</div>
	</fieldset>
</form>
<form class="regular_form" style="width:38em; margin-left: 2em;" method="post">
	<fieldset>
		<legend>Kette</legend>
		<label class="attribut" for="chain_name">Name</label>
		<input class="q2 wert" name="chain_name" id="chain_name" value="<?=$this->chain_name;?>"/>
		<label class="attribut" for="chain_website">Webseite</label>
		<input class="q2 wert" name="chain_website" id="chain_website" value="<?=$this->chain_website;?>"/>
		<label class="attribut" for="additional_information">Optionen</label>
		<div class="wert">
			<input class="q2 wert submit" style="float: left" type="submit" name="reset" value="&nbsp;&nbsp;&nbsp;Reset"/>
			<input class="q2 wert submit" style="float: right" type="submit" name="save_chain" value="Speichern"/>
		</div>
	</fieldset>
</form>
<form class="regular_form" style="width:38em; margin-left: 2em;" method="post">
	<fieldset>
		<legend>Kaufinformationen</legend>
		<label class="attribut" for="chain">Kette</label>
		<select class="q2 wert" name="chain" id="chain" style="width:auto">
			<option value="1">Aldi Süd</option>
		</select>
		<label class="attribut" for="shop">Händler</label>
		<select class="q2 wert" name="shop" id="shop" style="width:auto">
			<option value="1">Aldi Süd</option>
		</select>
		<label class="attribut" for="location">Ort</label>
		<input class="q2 wert" id="location" name="location" value="<?=$this->location;?>"/>
		<label class="attribut" for="price">Preis</label>
		<div class="wert"><input class="small" id="price" name="price" value="<?=$this->price;?>"/> Euro</div>
		<label class="attribut" for="shop_website">Webseite</label>
		<input class="q2 wert" name="shop_website" id="shop_website" value="<?=$this->shop_website;?>"/>
		<label class="attribut" for="shop_description">Beschreibung</label>
		<textarea class="text wert" name="shop_description" id="shop_description"><?=$this->shop_description;?></textarea>
		<label class="attribut" for="additional_information">Optionen</label>
		<div class="wert">
			<input class="q2 wert submit" style="float: left" type="submit" name="reset" value="&nbsp;&nbsp;&nbsp;Reset"/>
			<input class="q2 wert submit" style="float: right" type="submit" name="save_price" value="Speichern"/>
		</div>
	</fieldset>
</form>