<h1>der cocktailberater - Newsletter</h1>
<div id="spacing-left"><img src="<?php print $this->baseUrl(); ?>img/newsletter.png" align="right"
	style="margin-left: 1em;" title="Newsletter" alt="Newletter" />
<p>Der Newsletter von cocktailberater.de erscheint <strong>monatlich</strong>
und stellt dir <strong>neue Rezept</strong> sowie die <strong>Top 10 des
Monats</strong> vor. Außerdem gibt es regelmäßig <strong>Partnerangebote</strong>
und <strong>Tipps und Tricks zum Cocktail mixen</strong>.</p>
<?php
require ("views/scripts/template/newsletter_abmelden.phtml");
?></div>