<?php $this->partial('template/search.phtml'); ?>
<p class="left" style="margin: 1em 0 1em 25px; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Zutaten',
                'module'     => 'website',
                'controller' => 'ingredient',
                'pages'      => array(
                    array(
                        'label'      => $this->ingredient->name,
                        'module'     => 'website',
                        'controller' => 'ingredient',
                        'action'     => 'get'
                    )
                )
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo $this->navigation($container)->breadcrumbs();
?> (<a href="#recipes-list">Cocktailrezepte</a> und 
<a href="#products-list">Produkte</a>)</p>
<h2 class="left clear" style="margin-left: 25px; margin-top: 0;"><?php print $this->ingredient->name; ?></h2>
<div style="margin-left: 25px;">
<h3 class="clear left" style="margin-top: 0; margin-bottom: 0.5em;">Zutateninformationen (Durchschnittswerte)</h3>
<?php if($this->ingredient->description) {?>
<div class="attribut">Beschreibung:</div>
<div class="wert"><?php print $this->ingredient->description; ?></div>
<?php } ?>
<?php if($this->ingredient->getAverageAlcoholLevel()) {?>
<div class="attribut">Alkoholgehalt:</div>
<div class="wert"><?php print $this->ingredient->getAverageAlcoholLevel(); ?> %</div>
<?php } ?>
<?php if($this->ingredient->getAverageCaloriesKcal()) {?>
<div class="attribut">Kalorien:</div>
<div class="wert"><?php print round($this->ingredient->getAverageCaloriesKcal()/10); ?> kcal / 100g bzw. 100 ml</div>
<?php } ?>
<?php if($this->ingredient->getAveragePricePerLitre() || $this->ingredient->getAveragePricePerKilogram()) {?>
<div class="attribut">Preis:</div>
<div class="wert"><?php 
if($this->ingredient->getAveragePricePerLitre()) { 
	print number_format($this->ingredient->getAveragePricePerLitre(),2,',','.'); ?> € / Liter <?php
}
if($this->ingredient->getAveragePricePerLitre() && $this->ingredient->getAveragePricePerKilogram()) {
	print '<br />';
}
if($this->ingredient->getAveragePricePerKilogram()) {
	print number_format($this->ingredient->getAveragePricePerKilogram(),2,',','.'); ?> € / kg <?php 
} ?></div>
<?php } ?>
<?php if($this->ingredient->getAverageWeightGram()) {?>
<div class="attribut">Gewicht pro Einheit:</div>
<div class="wert"><?php print $this->ingredient->getAverageWeightGram(); ?> g</div>
<?php } ?>
<?php if($this->ingredient->getIngredientCategories()) {?>
<div class="attribut">Kategorien:</div>
<div class="wert"><?php
if(is_array($this->ingredient->getIngredientCategories())){
	foreach ($this->ingredient->getIngredientCategories() as $category) {

		print $category->name.'<br />';
	}
}
; ?></div>
<?php }
if($this->recipes) {?>
<h3 class="clear left" style="margin-bottom: 1.7em;" id="recipes-list">Cocktailrezepte mit <?php print $this->ingredient->name; ?></h3>
<div style="clear: left; "><?php
if(is_array($this->recipes)){
	foreach ($this->recipes as $recipe) { ?>
		<?php $this->cocktailPreview($recipe); ?>
	<?php 
	}
} ?></div>
<?php }
$products = Website_Model_Product::productsByIngredientId($this->ingredient->id);
if($products) { ?>
<h3 class="clear left" id="products-list"><?php print $this->ingredient->name; ?> Produkte</h3>
<div style="clear: left; text-align: left;"><?php
if(is_array($products)){
	print '<ul style="list-style-type: circle; margin-left: 25px;">';
	foreach ($products as $product) {
		$avgPrice = $product->getAveragePrice();
		$offers = $product->getOffers();
		print '<li style="padding-top: 0.7em;"><a href="'.$this->url(array(
		'controller'=>'product','id'=>$product->getUniqueName())).'">'.
		$product->name.	'</a> von <a href="'.$this->url(array(
		'controller'=>'manufacturer','id'=>$product->getManufacturer()->getUniqueName())).'">'.
		$product->getManufacturer()->name.'</a> ('.str_replace('.',',',round($product->size,2)).' '.
		$product->unit.') '.(count($offers)>0 ? 'gibt es '.($avgPrice ? 'für durchschnittlich '.
		number_format($avgPrice,2,',','.').' € ' : '').' bei:<br />' : '').
		($product->getImage() ? '<img src="'.$product->getImage().'" '.
		'style="max-width: 160px; max-height: 160px; float: right; '.
		'margin-right: 25px; margin-top: 1em;" '. 
		'alt="'.$offer['title'].' ('.$offer['brand'].')" '.
		'title="'.$offer['title'].' ('.$offer['brand'].')" />' : '').
		(count($offers)>0 ? '<ul style="clear: left; margin-top: 0.2em; list-style-type: circle; margin-left: 25px;">' : '');
		
		$i=0;
		foreach($offers as $offer){
			$i++;
			print '<li style="text-align: left;'.
				($i==1 ? 'clear: left;' : 'clear: none;').'">
				<a href="'.$offer['shopUrl'].'">';
				print ''.$offer['shop'].'</a> für '.number_format($offer['price'],2,',','.').' €</li>';
		}
		print (count($offers)>0 ? '</ul>' : '').'</li>';
	}
	print '</ul>';
}
?></div>
<?php } 