<?php echo $this->partial ("template/search.phtml"); ?>
<h1>Zutaten</h1>
<ul style="">
<?php
$i=0;
foreach ($this->ingredients as $ingredient){
	$i++;
	print '<li style="text-align: left; width: 20em; float: left; margin-bottom: 1em; margin-left: 1em; margin-right: 1em; '.( ($i == 1) ? 'clear: left;' : 'clear: none;' ).'"><a href="'.$this->url().'/'.$ingredient->getUniqueName().'">'.$ingredient->name.'</a><br />';
	if($ingredient->description) {
		print $ingredient->description.'<br />';
	}
	if($ingredient->getAverageAlcoholLevel()) {
		print 'Alkoholgehalt: '.$ingredient->getAverageAlcoholLevel().'%<br />';
	}
	if($ingredient->getAverageCaloriesKcal()) {
		print 'Kalorien: '.round($ingredient->getAverageCaloriesKcal()/10).'&nbsp;kcal / 100&nbsp;g bzw. 100&nbsp;ml<br />';
	}
	if($ingredient->getAveragePricePerLitre() || $ingredient->getAveragePricePerKilogram()) {
		print 'Durchschnittspreis: ';
		if($ingredient->getAveragePricePerLitre()) {
			print number_format($ingredient->getAveragePricePerLitre(),2,',','.').'&nbsp;€&nbsp;/&nbsp;Liter ';
		}
		if($ingredient->getAveragePricePerLitre() && $ingredient->getAveragePricePerKilogram()) {
			print '<br />';
		}
		if($ingredient->getAveragePricePerKilogram()) {
			print number_format($ingredient->getAveragePricePerKilogram(),2,',','.').'&nbsp;€&nbsp;/&nbsp;kg<br />';
		}
	}
	$products = Website_Model_Product::productsByIngredientId($ingredient->id);
	if(is_array($products)) { 
		print 'Produkte: ';
		print '<ul style="font-size: 0.9em; list-style-type: circle; margin-left: 2em;">';
		foreach ($products as $product) {
			$avgPrice = $product->getAveragePrice();
			print '<li>'.$product->name.' '.(($product->getManufacturer()->name!='') ? ' ('.$product->getManufacturer()->name.') - ' : '').
			str_replace('.',',',round($product->size,2)).'&nbsp;'.$product->unit.
			($avgPrice ? ' - Durchschnittspreis: '.number_format($avgPrice,2,',','.').'&nbsp;€ ' : '').'</li>';
		}
		print '</ul>';
	}
	print '</li>';
}
?>
</ul>
