<p class="left" style="margin: 1em 0 1em 25px; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Zutaten',
                'module'     => 'website',
                'controller' => 'ingredient'
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo $this->navigation($container)->breadcrumbs();
?></p>
<?php 
// dojo helper
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
$this->dojo()->enable()->requireModule('dijit.Tooltip');
$this->headScript()->captureStart();
?>
dojo.addOnLoad(function() {
	priceTooltip = new dijit.Tooltip({
		connectId: ["priceTooltip"],
		label: "Alle Preisangaben sind Durschnittspreise."
	});
	caloriesTooltip = new dijit.Tooltip({
		connectId: ["caloriesTooltip"],
		label: "Kalorienangaben pro 100 g bzw. 100 ml"
	});
});
<?php $this->headScript()->captureEnd(); ?>
<div style="clear: left; margin-left: 25px; margin-right: 25px;">
<h2 style="margin-top: 0; text-align: left;">Zutaten für Cocktailrezepte</h2>
<table class="table">
	<thead>
		<tr>
			<th>Zutat</th>
			<th>Kategorie</th>
			<th>Alk.- gehalt</th>
			<th><a href="#" class="tip pink" id="caloriesTooltip">Kalorien</a></th>
			<th><a href="#" class="tip pink" id="priceTooltip">Preis</a></th>
			<th>Rezepte</th>
			<th>Produkte</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->ingredients as $ingredient){ /* @var $ingredient Website_Model_Ingredient */ ?>
		<tr>
			<td><?php 
			$categories = '';
			if(is_array($ingredient->getIngredientCategories())){
				foreach($ingredient->getIngredientCategories() as $cagetory){
					$cagetory = '<a href="'.$this->url(array('controller'=>'ingredient-category','action'=>'get','module'=>'website','id'=>$cagetory->getUniqueName())).'">'.$cagetory->name.'</a>';
					$categories	= ($categories ? $categories.', '.$cagetory : $cagetory);
				}
			} ?> <a
				href="<?php print $this->url(array('controller'=>'ingredient','action'=>'get','module'=>'website','id'=>$ingredient->getUniqueName())); ?>">
				<?php print $ingredient->name; ?></a></td>
			<td><?php print $categories; ?></td>
			<td><?php if($ingredient->getAverageAlcoholLevel()) { print $ingredient->getAverageAlcoholLevel().' %'; } else { print '0 %'; } ?></td>
			<td><?php if($ingredient->getAverageCaloriesKcal()) { print round($ingredient->getAverageCaloriesKcal()/10); ?>&nbsp;kcal<?php } else { print 'k.A.'; } ?></td>
			<td><?php 
			if($ingredient->getAveragePricePerLitre() || $ingredient->getAveragePricePerKilogram()) {
				if($ingredient->getAveragePricePerLitre()) {
					print number_format($ingredient->getAveragePricePerLitre(),2,',','.').'&nbsp;€&nbsp;/&nbsp;l ';
				}
				if($ingredient->getAveragePricePerLitre() && $ingredient->getAveragePricePerKilogram()) {
					print ' bzw. ';
				}
				if($ingredient->getAveragePricePerKilogram()) {
					print number_format($ingredient->getAveragePricePerKilogram(),2,',','.').'&nbsp;€&nbsp;/&nbsp;kg';
				}
			} ?></td>
			<td><?php 
			$numberOfRecipes = $ingredient->getNumberOfRecipes();
			if($numberOfRecipes) { ?>
				<a href="<?php print $this->url(array(
				'controller'=>'ingredient','action'=>'get','module'=>'website',
				'id'=>$ingredient->getUniqueName())); ?>#recipes-list">
				<?php print $numberOfRecipes; ?> Stk.</a><?php
			}
			?></td>
			<td><?php 
			$products = Website_Model_Product::numberOfProductsByIngredientId($ingredient->id);
			if($products>0) { ?><a href="<?php print $this->url(array(
				'controller'=>'ingredient','action'=>'get','module'=>'website',
				'id'=>$ingredient->getUniqueName())); ?>#products-list"><?php print $products; ?>
				Stk.</a><?php 
			} ?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
</div>