<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$ingredientsXML = $this->xml->createElement('ingredients');
if(is_array($this->ingredients)){
	foreach ($this->ingredients as $ingredient){
		$ingredient->toXml($this->xml,$ingredientsXML);
	}
}
// set count for ingredients element according to number of ingredients found
$ingredientsXML->setAttribute('count',count($this->ingredients));
// add the '$ingredients' element to the 'rsp' element
$this->rsp->appendChild($ingredientsXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
