<?php

/**
 * Kontakt view
 *
 * @author  VWA Studienakademie
 * @version 1.0
 */

$this->headTitle ( 'VWA Studienakademie - Bachelorball 2009 - Organistion - Kontakt' );
$this->placeholder ( 'breadcrumb' )->set ( 'Organistion &gt; Kontakt' );
$this->placeholder ( 'title' )->set ( 'Kontakt' );
?>
<h2 class="no_bottom_margin">Vielen Dank für Ihre Nachricht!</h2>
<p>Wir werden Ihre Nachricht umgehend an die betreffende Person weiterleiten und Ihnen antworten.</p>
