<h1>der cocktailberater - Impressum</h1>
<div id="spacing-left">
<div class="attribut">Anschrift</div>
<div class="wert">Der Webseitenberater<br />
Wehlener Str. 27<br />
01328 Dresden<br />
Deutschland</div>
<div class="attribut">Steuernummer</div>
<div class="wert">201/203/03326</div>
<div class="attribut">Finanzamt</div>
<div class="wert">Dresden 1</div>
<div class="attribut">Geschäfts- führung</div>
<div class="wert"><a href="http://www.thobach.de"
	title="Webseite von Thomas Bachmann">Thomas Bachmann</a></div>
<div class="attribut">E-Mail</div>
<div class="wert"><img src="<?php print $this->baseUrl(); ?>/img/email.png"
	alt="E-Mail" title="E-Mail" style="height: 16px; vertical-align: top" />
<a href="mailto:info@thobach.de">info@thobach.de</a></div>
<div class="attribut">Telefon</div>
<div class="wert"><img src="<?php print $this->baseUrl(); ?>/img/telefon.png"
	alt="Telefon" title="Telefon" style="height: 16px; vertical-align: top" />
0711 - 935 08 58</div>
<div class="attribut">Mobil</div>
<div class="wert">0172 - 174 69 74</div>
<div class="attribut">Fax</div>
<div class="wert">012126-THBACHMANN</div>
<div style="float: left; clear: both; margin-top: 20px"></div>
<div class="attribut">Betreiber</div>
<div class="wert"><a href="http://www.webseitenberater.de"
	title="Webprogrammierung - Der Webseitenberater"><img
	src="http://www.webseitenberater.de/no_html/logo_boxen.png"
	title="Webprogrammierung - Der Webseitenberater"
	alt="Logo von: Der Webseitenberater" style="height: 100px;" /><br />
der webseitenberater</a></div>
<div class="attribut">Entwicklungs- Blog</div>
<div class="wert"><a href="http://blog.cocktailberater.de/">cocktailberater</a></div>
<div class="attribut">Projekt- management</div>
<div class="wert"><a href="http://code.google.com/p/cocktailberater/">cocktailberater bei googel code</a></div>
<div class="attribut">ZendFramework Version</div>
<div class="wert"><?php print Zend_Version::VERSION; ?></div>
<div class="attribut">PHP Version</div>
<div class="wert"><a href="<?php print $this->baseUrl(); ?>/phpinfo.php"><?php print phpversion(); ?></a></div>
<div class="attribut">Umgebung</div>
<div class="wert"><?php print APPLICATION_ENV; ?></div>
</div>
