<?php
$this->format = 'html';
// setting meta keywords
$this->headMeta()->appendName(	'keywords', 'cocktail, rezept, cocktails, '.
								'rezepte, cocktailrezepte, cocktailrezept, '.
								'alkoholisch, alkoholfrei, top10, '.
								'cocktailberater');
// setting meta description
$this->headMeta()->appendName(	'description', 'Alkoholfreie und '.
								'alkoholische Cocktailrezepte, Top 10 '.
								'Cocktails, Rum-Cocktails, Vodka-Cocktails, '.
								'Cocktails mit Bildern, Cocktailkarten, '.
								'Barkunde und vieles mehr.');
// atom comments
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Kommentare - Atom',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'comment','action'=>'index')).
                      '?format=atom'));
// rss comments
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Kommentare - RSS',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'comment','action'=>'index')).
                      '?format=rss'));
// atom tags
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Tags - Atom',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'tag','action'=>'index')).'?format=atom'));
// rss tags
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Tags - RSS',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'tag','action'=>'index')).'?format=rss'));
// atom ratings
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Bewertungen - Atom',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'rating','action'=>'index')).
                      '?format=atom'));
// rss ratings
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Bewertungen - RSS',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'rating','action'=>'index')).
                      '?format=rss'));
// atom recipes
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Cocktailrezepte - Atom',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe')).'?format=atom'));
// rss recipes
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Cocktailrezepte - RSS',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe')).'?format=rss'));

?>
<div class="abstand_oben_doppelt"><?php print $this->partial('template/search.phtml',array('uri' => $this->baseUrl())); ?>
</div>
<div class="browse">
<h2>Stöbern</h2>
<?php require_once ('browse.inc.phtml'); ?>
<div class="clear"></div>
</div>
