<?php
// setting meta keywords
$this->headMeta()->appendName('keywords', 'cocktail, rezept, cocktails, rezepte, cocktailrezepte, cocktailrezept, alkoholisch, alkoholfrei, top10, cocktailberater');
// setting meta description
$this->headMeta()->appendName('description', 'Datenbank mit Rezepten für alkoholfreie und alkoholische Cocktails');
?>
<div class="abstand_oben_doppelt"><?php print $this->partial('template/search.phtml',array('uri' => $this->baseUrl())); ?>
</div>
<div class="browse">
<h2>Stöbern</h2>
<ul>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'alcoholic')); ?>" title="Cocktails mit Alkohol"><img
		src="<?php echo $this->baseUrl(); ?>/img/alkohol-cocktails.png" />Alkoholische<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'top10')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/topcocktail.png" />Top 10<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'non-alcoholic')); ?>" title="Cocktails ohne Alkohol"><img
		src="<?php echo $this->baseUrl(); ?>/img/alkoholfrei.png" />Alkholfreie<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'search','search_type'=>'difficulty','search'=>'beginner')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/anfaenger3.png" />Einfache<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'search','search_type'=>'ingredient','search'=>'vodka')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/vodka.png" />Cocktailrezepte<br />
	mit Vodka</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'search','search_type'=>'ingredient','search'=>'rum')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/rum.png" />Cocktailrezepte<br />
	mit Rum</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'search','filter'=>'with-image')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/galerie2.png" />Cocktailrezepte<br />
	mit Bildern</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'barkunde')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/stoessel.png" />Wissen &amp;<br />
	Barkunde</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'community')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/community.png" />Cocktail-<br />
	Community</a></li>
	<!-- <li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'index','action'=>'imprint')); ?>"><img
		src="<?php echo $this->baseUrl(); ?>/img/cocktailberater.png" />Über<br />
	Cocktailberater</a></li> -->
</ul>
<div class="clear"></div>
</div>
