<?php echo $this->partial ("template/search.phtml"); ?>
<h1> Top 10 Cocktails </h1><div id="ergebnisse"
	style="clear:left;">
<?php 
//$config = Zend_Registry::get('config');
echo $this->partialLoop ("template/preview.phtml",$this->cocktails);
/*$top=1;
foreach ($this->cocktails as $key => $val){
	$mode = 'top10';
	$recipe = Website_Model_Recipe::getRecipe($val->id);
	
	require ("views/scripts/template/preview.phtml");
	$top++;
}
*/
?></div>
