<div class="block">Gäste: <input type="submit"
	value="Neuen Gast hinzufügen" name="action" class="pink right" />
<ul>
	<li><span class="title">Maximilian Mustermann</span>
	<hr class="light" />
	</li>
	<li><span class="title">Kurt Krause</span>
	<hr class="light" />
	</li>
	<li><span class="title">Caroline Bock</span>
	<hr class="light" />
	</li>
</ul>
<p class="block_info_guests">Anzahl Gäste: 3<br />
<input type="button" class="pink left margin_top" value="&lt; zurück"
	name="action" /> <input type="button" class="pink right margin_top"
	value="weiter &gt;" name="action" /><br />
</p>
<hr class="bottom_divider" />
<p class="switch_party">Party wechseln: <select class="switch_party">
	<option>Hawaii Party</option>
</select></p>
</div>
<div class="bestellungen"><span class="right"><img
	src="/img/recipes/1.jpg" alt="" class="recipe_image" /><br /><input type="submit"
	value="austragen" name="action" class="pink right" style="margin-right: 40px;" />
</span> <span
	class="title">Maximilian Mustermann</span><br />
<br />
<span class="pink">E-Mail-Adresse:</span><br />
maximilian.mustermann@myprovider.de
<br />
<br />
<span class="pink">Geburtstag:</span>
<br />01.01.1988
<br /><br />
<span class="pink">Letzter Login:</span><br />
04.03.2010 <br /><br /><span class="pink">Erstmalige Anmeldung:</span><br />
01.02.2008 <br/><br /><span class="pink">Teilnahme an Partys:</span><br />
<ul>
	<li>Hawaii Party</li>
</ul>
</div>
