<div class="login"><h2 class="pink">Anmelden</h2>
<form action="" method="post"><label>E-Mail-Adresse: <br />
<input type="email" /><span class="grey smaller">(z.B.
max.mustermann@tollebar.de)</span> </label> <label>Passwort: <br />
<input type="password" /></label> <a class="grey button" href="<?php print $this->url(array('action'=>'index')); ?>"
	 >Abbrechen</a><input
	type="submit" value="Anmelden" name="action" class="pink right" /></form>
<ul>
	<li><a href="<?php print $this->url(array('action'=>'password')); ?>">Passwort vergessen?</a></li>
	<li><a href="<?php print $this->url(array('action'=>'register')); ?>">Noch keinen Account?</a></li>
</ul>
</div>
