<?php
// setting meta keywords
$this->headMeta()->appendName(	'keywords', 'cocktail, rezept, cocktails, '.
								'mobile, handy, '.
								'rezepte, cocktailrezepte, cocktailrezept, '.
								'alkoholisch, alkoholfrei, top10, '.
								'cocktailberater');
// setting meta description
$this->headMeta()->appendName(	'description', 'Mobile Datenbank mit '.
								'alkoholfreien und alkoholischen '. 
								'Cocktailrezepten');
?>
<div class="browse">
	<h2>Stöbern</h2>
	<?php require_once ('browse.inc.phtml'); ?>
	<div class="clear"></div>
</div>
