<?php
// setting meta keywords
$this->headMeta()->appendName(	'keywords', 'cocktail, rezept, cocktails, '.
								'rezepte, cocktailrezepte, cocktailrezept, '.
								'alkoholisch, alkoholfrei, top10, '.
								'cocktailberater');
// setting meta description
$this->headMeta()->appendName(	'description', 'Alkoholfreie und '.
								'alkoholische Cocktailrezepte, Top 10 '.
								'Cocktails, Rum-Cocktails, Vodka-Cocktails, '.
								'Cocktails mit Bildern, Cocktailkarten, '.
								'Barkunde und vieles mehr.');
// atom comments
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Kommentare - Atom',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'comment','action'=>'index')).
                      '?format=atom'));
// rss comments
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Kommentare - RSS',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'comment','action'=>'index')).
                      '?format=rss'));
// atom tags
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Tags - Atom',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'tag','action'=>'index')).'?format=atom'));
// rss tags
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Tags - RSS',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'tag','action'=>'index')).'?format=rss'));
// atom ratings
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Bewertungen - Atom',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'rating','action'=>'index')).
                      '?format=atom'));
// rss ratings
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Bewertungen - RSS',
                      'href' => $this->url(array('module'=>'website',
                      'controller'=>'rating','action'=>'index')).
                      '?format=rss'));
// atom recipes
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => 'Alle Cocktailrezepte - Atom',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe')).'?format=atom'));
// rss recipes
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => 'Alle Cocktailrezepte - RSS',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe')).'?format=rss'));

?>
<div class="abstand_oben_doppelt"><?php print $this->partial('template/search.phtml',array('uri' => $this->baseUrl())); ?>
</div>
<div class="browse">
<h2>Stöbern</h2>
<ul>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'alcoholic')); ?>"
		title="Cocktails mit Alkohol"><span class="stoebern_sprites"
		id="spr_alcoholic"></span>Alkoholische<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'top10')); ?>">
	<span class="stoebern_sprites" id="spr_top10"></span>Top 10<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'non-alcoholic')); ?>"
		title="Cocktails ohne Alkohol"><span class="stoebern_sprites"
		id="spr_non_alcoholic"></span>Alkholfreie<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'difficulty','search'=>'beginner')); ?>">
	<span class="stoebern_sprites" id="spr_beginner"></span>Einfache<br />
	Cocktailrezepte</a></li>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'ingredient','search'=>'Vodka')); ?>">
	<span class="stoebern_sprites" id="spr_vodka"></span>Cocktailrezepte<br />
	mit Vodka</a></li>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'ingredient','search'=>'Rum')); ?>">
	<span class="stoebern_sprites" id="spr_rum"></span>Cocktailrezepte<br />
	mit Rum</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'image')); ?>">
	<span class="stoebern_sprites" id="spr_image"></span>Cocktailrezepte<br />
	mit Bildern</a></li>
	<li><a
		href="<?php echo $this->url(array('module' => 'website', 'controller' => 'recipe','search_type'=>'tag','search'=>'Klassiker')); ?>">
	<span class="stoebern_sprites" id="spr_classics"></span>Cocktail-<br />Klassiker</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'authors')); ?>">
	<span class="stoebern_sprites" id="spr_original"></span>Original-<br />Rezepte</a></li>
	 <!-- <li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'community')); ?>">
	<span class="stoebern_sprites" id="spr_community"></span>Cocktail-<br />
	Community</a></li> --> 
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'hausbar')); ?>">
	<span class="stoebern_sprites" id="spr_tools"></span>Party <br />
	Helferlein</a></li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'barkunde')); ?>">
	<span class="stoebern_sprites" id="spr_barkunde"></span>Wissen &amp;<br />
	Barkunde</a></li>
	 <li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'about')); ?>">
	<span class="stoebern_sprites" id="spr_icon"></span>Über das Projekt <br />cocktailberater</a></li> 
</ul>
<div class="clear"></div>
</div>
