<?php
// setting meta keywords
$this->headMeta()->appendName(	'keywords', 'cocktail, rezept, cocktails, '.
								'mobile, handy, '.
								'rezepte, cocktailrezepte, cocktailrezept, '.
								'alkoholisch, alkoholfrei, top10, '.
								'cocktailberater');
// setting meta description
$this->headMeta()->appendName(	'description', 'Mobile Datenbank mit '.
								'alkoholfreien und alkoholischen '. 
								'Cocktailrezepten');
// atom comments
$this->headLink(array(	'rel' => 'alternate','type' => 'application/atom+xml',
						'title' => 'Alle Kommentare - Atom',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'comment','action'=>'index')).
							'?format=atom'));
// rss comments
$this->headLink(array(	'rel' => 'alternate','type' => 'application/rss+xml',
						'title' => 'Alle Kommentare - RSS',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'comment','action'=>'index')).
							'?format=rss'));
// atom tags
$this->headLink(array(	'rel' => 'alternate','type' => 'application/atom+xml',
						'title' => 'Alle Tags - Atom',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'tag','action'=>'index')).
							'?format=atom'));
// rss tags
$this->headLink(array(	'rel' => 'alternate','type' => 'application/rss+xml',
						'title' => 'Alle Tags - RSS',
						'href' => $this->url(array('module'=>'website',
						  'controller'=>'tag','action'=>'index')).'?format=rss'));
// atom ratings
$this->headLink(array(	'rel' => 'alternate','type' => 'application/atom+xml',
						'title' => 'Alle Bewertungen - Atom',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'rating','action'=>'index')).
							'?format=atom'));
// rss ratings
$this->headLink(array(	'rel' => 'alternate','type' => 'application/rss+xml',
						'title' => 'Alle Bewertungen - RSS',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'rating','action'=>'index')).
							'?format=rss'));
// atom recipes
$this->headLink(array(	'rel' => 'alternate','type' => 'application/atom+xml',
						'title' => 'Alle Cocktailrezepte - Atom',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'recipe')).'?format=atom'));
// rss recipes
$this->headLink(array(	'rel' => 'alternate','type' => 'application/rss+xml',
						'title' => 'Alle Cocktailrezepte - RSS',
						'href' => $this->url(array('module'=>'website',
							'controller'=>'recipe')).'?format=rss'));

?>
<div class="abstand_oben"><?php 
print $this->partial('template/search.mobile.phtml',
array('uri' => $this->baseUrl())); ?></div>
<div class="browse">
<h2>Stöbern</h2>
<ul>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'alcoholic')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_alcoholic"></span>Alkoholische Cocktailrezepte</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'top10')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_top10"></span>Top 10 Cocktailrezepte</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'non-alcoholic')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_non_alcoholic"></span>Alkholfreie Cocktailrezepte</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'difficulty','search'=>'beginner')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_beginner"></span>Einfache Cocktailrezepte</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'ingredient','search'=>'Vodka')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_vodka"></span>Cocktailrezepte mit Vodka</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'ingredient','search'=>'Rum')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_rum"></span>Cocktailrezepte mit Rum</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'recipe','search_type'=>'image')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_image"></span>Cocktailrezepte mit Bildern</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'barkunde')); ?>?format=mobile"> <span class="stoebern_sprites" id="spr_barkunde"></span>Wissen &amp; Barkunde</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'hausbar')); ?>?format=mobile"> <span id="spr_tools"></span>Party Helferlein</a></li>
</ul>
<div class="clear"></div>
</div>
