<div id="spacing-left">
<div id="sub_nav">
<ul>
	<li>Community</li>
	<ul>
		<li>Cocktail der Woche</li>
		<li>Top 10 Drinks</li>
		<li>Forum</li>
	</ul>
	<li>HausBar</li>
	<ul>
		<li>Anmelden / Login</li>
		<li>Meine Hausbar</li>
		<li>Meine Favoriten</li>
		<li>Meine Cocktails</li>
		<li>Cocktailbuch erstellen</li>
	</ul>
	<li>BarKunde</li>
	<ul>
		<li><a href="<?php print $this->baseUrl(); ?>portal/glas">Gläser</a></li>
		<li>Utensilien</li>
		<li>Mixtechniken</li>
		<li>Grundausstattung</li>
		<li>Zutaten (Beschreibung)</li>
		<li>empfehlenswerte Bücher</li>
		<li>andere Cocktailseiten</li>
	</ul>
</ul>
</div>
<div id="content">content</div>
</div>
