<?php
print $this->partial('template/search.phtml',$this);
$this->dojo()->enable()->requireModule('dijit.Tooltip')->requireModule('dojox.image.Lightbox');
$this->dojo()->addStylesheet($this->dojo()->getCdnBase().$this->dojo()->getCdnVersion().'/dojox/image/resources/Lightbox.css');
$recipe = $this->recipe;
$photos = $recipe->getPhotos();
$videos = $recipe->getVideos();
$alternatives = $this->alternatives;
$gesamt = count($alternatives);
// ingredient list
foreach ( $recipe->getComponents() as $component ) {
	$ingredientList[] = $component->amount.' '.$component->unit.' '.$component->getIngredient()->name;
	$ingredientList2[] = $component->getIngredient()->name;
}
// setting meta keywords
$this->headMeta()->appendName('keywords', $recipe->name.', '.implode($ingredientList2,', ').', cocktail, rezept, cocktails, rezepte, cocktailrezepte, cocktailrezept, cocktailberater');
// setting meta description
$this->headMeta()->appendName('description', 'Das  Rezept des '.$recipe->name.' Cocktails besteht aus '.implode($ingredientList,', ').'. Mehr mit Beschreibung, Anweisung, Fotos, Videos und Kommentaren hier.');
?>
<div>
<div style="float: right;"><img style="<?php 
	if(isset($photos[0]) && $photos[0]->fileName) {  ?>width: 160px<?php } 
	else { ?>margin-top: 1em; <?php }?>"
	src="<?php
	if(isset($photos[0]) && $photos[0]->fileName) { 
		echo $this->baseUrl() .'/img/recipes/'. $photos[ 0 ]->fileName ;
	} else {
	 	echo $this->baseUrl().'/img/wikilogo.png';
	}
	?>"
	alt="<?php
	print str_replace ( '\\', '', $recipe->name ) ;
	?>"
	title="<?php
	print str_replace ( '\\', '', $recipe->name ) ;
	?>"
	style="margin-bottom: 20px;" />
<div
	style="clear: both; margin-left: auto; margin-right: auto; width: 140px;">
	<?php
	if (sizeof($videos)>0) {
		?><a href="#video"><img src="<?php
	print $this->baseUrl() ;
	?>/img/video.png" alt="Video"
	title="Video"
	style="margin-right: 10px; margin-top: 4px; vertical-align: top;"
	onclick="document.getElementById('video').style.display='block';" /></a><?php
	}
	$i = 0 ;
	if(is_array($photos)){
		foreach ( $photos as $photo ) {
			$i ++ ;
			?><a
	href="<?php echo $this->baseUrl() .'/img/recipes/' . $photo->originalFileName ; ?>" 
	dojoType="dojox.image.Lightbox" group="one" 
	title="<?php print str_replace ( '\\', '', $recipe->name ) ; ?>"><?php
	if ($i == 1) {
		?><img src="<?php
		print $this->baseUrl() ;
		?>/img/foto.png" alt="Fotos"
	title="Fotos"
	style="margin-left: 10px; margin-top: 4px; vertical-align: top; margin-bottom: 20px;" /><?php
	}
	?></a><?php
		}
	}
	?></div>
</div>
<!-- class="right" -->
<div style="margin-left: 25px; margin-top: 15px">
<div class="attribut">Name:</div>
<div class="wert"><?php
print str_replace ( '\\', '', $recipe->name ) ;
if($recipe->isOriginal){
	print  ' (original)';
}
if(!$recipe->isAlcoholic){
	print  ' (alkoholfrei)';
}
?></div>
<?php if($recipe->description){?><div class="attribut">Beschreibung:</div>
<div class="wert"><p><?php
print str_replace("\n",'</p><p>',$recipe->description);
?></p></div><?php } ?>
<div class="attribut">Zutaten:</div>
<div class="wert"><p><strong>Cocktail</strong></p><ul><?php
//Zend_Debug::dump($rezept); exit;
foreach ( $recipe->getComponents() as $component ) {
	print '<li>';
	print $component->amount ;
	print ' ' ;
	print $component->unit ;
	print ' ' ;
	?>
	<?php $this->headScript()->captureStart(); ?>
	dojo.addOnLoad(function() {
		zutat<?php print $component->getIngredient()->id ;?>Tooltip = new dijit.Tooltip({
            connectId: ["zutat<?php print $component->getIngredient()->id ;?>"],
            label: "<?php
$alcoholLevel = $component->getIngredient()->getAverageAlcoholLevel();
$calories = $component->getIngredient()->getAverageCaloriesKcal();
$categories = $component->getIngredient()->getIngredientCategories();
$products = $component->getIngredient()->getProducts();
?><div style=\"text-align:left;\"><?php
if($alcoholLevel){ ?><span class=\"pink\">Alkoholgehalt:</span> <?php print $alcoholLevel; ?> %<br /><?php }
if($calories) { ?><span class=\"pink\">Kalorien:</span> <?php print $calories; ?> kcal<br /><?php } 
if ($categories) {?><span class=\"pink\">Kategorie(n):</span> <?php
if(is_array($categories)){
	foreach ($categories as $category) {
		print $category->name.'<br />';
	}
}
}
if($products) { ?><span class=\"pink\">Produkte:</span> <?php
if(is_array($products)){
	foreach ($products as $product) {
		print $product->name.' ('.$product->getManufacturer()->name.') - '.$product->size.' '.$product->unit.'<br />';
	}
}
}
?></div>"
        });
    });
	<?php $this->headScript()->captureEnd(); ?>
	<a id="zutat<?php print $component->getIngredient()->id ;?>"
	href="<?php print $this->url(array('module'=>'website','controller'=>'index',
		'action'=>'ingredient','id'=>$component->getIngredient()->id),null,true); ?>"
	title="<?php echo $this->escape ( str_replace ( '\\', '', $component->getIngredient()->name ) ) ?>">
	<?php print $component->getIngredient()->name ; ?></a></li>
	<?php
} // foreach
?></ul><p class="abstand_oben"><strong>Dekoration</strong></p><ul><li>Früchte nach Belieben.</li></ul></div>
<div class="attribut">Anweisung:</div>
<div class="wert"><p><?php
print str_replace("\n",'</p><p>',$recipe->instruction);
?></p></div>
<div class="attribut">Schlagworte / Tags:<br />
<span id="switcha1"
	onclick="document.getElementById('tag_form').style.display='block'; document.getElementById('switcha1').innerHTML=''; dojo.byId('newtag').focus();"
	style="cursor: pointer; color: #54616E">(hinzufügen)</span></div>
<div class="wert"><?php
$tagCloud =  Website_Model_Tag::getRecipeTagCloud($recipe->id);
require_once(APPLICATION_PATH.'/Wb/Decorator/HtmlTag.php');
$decorator = new Wb_Decorator_HtmlTag();
$decorator->setView($this);
$tagCloud->setTagDecorator($decorator);
echo $tagCloud;
?>
<?php
// dojo helper
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
// enable dojo with custom module (readStore), parser, and comboBox
$this->dojo()->enable()
->registerModulePath('custom', $this->baseUrl().'/js/custom')
->requireModule('dojo.parser')
->requireModule('dojox.data.QueryReadStore')
->requireModule('dijit.form.ComboBox')
->requireModule('custom.TagReadStore');
// define url for autoCompletion
$autoCompletionUrl = array('action'=>'suggest','controller'=>'index','module'=>'website','format'=>'ajax');
?>
<div dojoType="custom.TagReadStore" jsId="tagStore" url="<?php echo $this->url($autoCompletionUrl); ?>"
	requestMethod="get"></div>
<?php $this->headScript()->captureStart(); ?>
// configure query
djConfig.usePlainJson=true;
// add the possibility to submit the search by pressing the ENTER key 
function initTag() {
	dojo.connect(dojo.byId("newtag"), 'onkeypress', function(e) { 
		if (e.keyCode == dojo.keys.ENTER) { 
			dojo.byId('tag_form').submit(); 
		} 
	});
}
dojo.addOnLoad(initTag);
<?php $this->headScript()->captureEnd(); ?>
<form id="tag_form" class="regular_form hide abstand_oben abstand_unten" method="post"
	action="<?php print $this->url(array('module'=>'website','controller'=>'index','action'=>'recipe','id'=>$recipe->id),null,true); ?>">
	<fieldset>
		<legend>Schlagwort / Tag hinzufügen</legend>
		<label for="newtag">Dein Tag:</label>
		<!-- text input w/ autocompletion -->
		<?php 
			$autoCompletetionInputOptions = array('dojoType'=>array('dijit.form.ComboBox'),'store'=>'tagStore','autoComplete'=>'false','hasDownArrow'=>'false'); 
			echo $this->formText('newtag',null,$autoCompletetionInputOptions);
		?>
		<input name="recipe" value="<?php print $recipe->id; ?>" type="hidden" />
		<input type="submit" class="small-button" value="hinzufügen"
			style="background-image: url('<?php echo $this->baseUrl(); ?>/img/general-button-small4.png');" />
	</fieldset>
</form>
</div>
<div class="attribut">Bewertung:</div>
<div class="wert"><?php
$durchschnitt = $this->recipe->getRating();
?> <a
	href="<?php print $this->url(array('module'=>'website','controller'=>'index','action'=>'recipe','id'=>$recipe->id,'rating'=>1),null,true); ?>"
	title="geschmackssache" style="clear: both; float: left;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 1) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>"
	alt="geschmackssache" id="bewertung1"
	style="width: 18px; height: 18px;"
	onmouseover="this.src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'"
	onmouseout="this.src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 1) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'" /></a> <a
	href="<?php print $this->url(array('module'=>'website','controller'=>'index','action'=>'recipe','id'=>$recipe->id,'rating'=>2),null,true); ?>"
	title="ganz ok" style="float: left;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 2) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>"
	alt="ganz ok" id="bewertung2" style="width: 18px; height: 18px;"
	onmouseover="this.src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'"
	onmouseout="this.src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 2) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 1) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'" /></a> <a
	href="<?php print $this->url(array('module'=>'website','controller'=>'index','action'=>'recipe','id'=>$recipe->id,'rating'=>3),null,true); ?>"
	title="gut" style="float: left;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 3) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>"
	alt="gut" id="bewertung3" style="width: 18px; height: 18px;"
	onmouseover="this.src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung2').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; "
	onmouseout="this.src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 3) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 2) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung2').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 1) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'" /></a> <a
	href="<?php print $this->url(array('module'=>'website','controller'=>'index','action'=>'recipe','id'=>$recipe->id,'rating'=>4),null,true); ?>"
	title="sehr gut" style="float: left;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 4) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>"
	alt="sehr gut" id="bewertung4" style="width: 18px; height: 18px;"
	onmouseover="this.src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung2').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png';
	document.getElementById('bewertung3').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; "
	onmouseout="this.src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 4) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 3) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung2').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 2) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>';
	document.getElementById('bewertung3').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 1) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>';" /></a> <a
	href="<?php print $this->url(array('module'=>'website','controller'=>'index','action'=>'recipe','id'=>$recipe->id,'rating'=>5),null,true); ?>"
	title="absoluter Favorit" style="float: left;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 5) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>"
	alt="absoluter Favorit" id="bewertung5"
	style="width: 18px; height: 18px;"
	onmouseover="this.src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; 
	document.getElementById('bewertung2').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png';
	document.getElementById('bewertung3').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png';
	document.getElementById('bewertung4').src='<?php
	print $this->baseUrl() ;
	?>/img/1_stars_pink.png'; "
	onmouseout="this.src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 5) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung1').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 1) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>'; 
	document.getElementById('bewertung2').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 2) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>';
	document.getElementById('bewertung3').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 3) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>';
	document.getElementById('bewertung4').src='<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($durchschnitt >= 4) {
		print '1_stars.png' ;
	} else {
		print 'not_yet_rated_1.png' ;
	}
	?>';" /></a> &nbsp;(Anzahl Stimmen: <?php
	print $this->recipe->ratingsCount.' - Ø ' . number_format ( $this->recipe->getRating(), 2, ',', '' ) ;

	?>)</div>
<div class="attribut">Rezeptquelle:</div>
<div class="wert"><?php if($recipe->source) {
	print $recipe->source;
} else {
	?>-keine angegeben-<?php } ?></div>	
	<?php $this->headScript()->captureStart(); ?>
// hide all comments
function hideComments() {
	dojo.byId('commentList').style.display='none';
	dojo.byId('comment_form').style.display='none';
	dojo.byId('switchc1').style.display='block';
	dojo.byId('switchb1').style.display='block';
	dojo.byId('switchb1').innerHTML='(einfügen)';
	dojo.byId('switchc1').innerHTML='<?php $amountOfComments = count($this->recipe->getComments()); echo $amountOfComments; ?> Kommentar(e) anzeigen';
}
// show all comments and new comment form 
function showComments() {
	dojo.byId('commentList').style.display='block';
	dojo.byId('switchc1').innerHTML='';
	dojo.byId('comment_form').style.display='block';
	dojo.byId('switchb1').innerHTML='';
}
// only hide comments when anchor is not set in url
if(!(location.hash=='#comment-insert' || location.hash=='#comments')){ 
	dojo.addOnLoad(hideComments);
}
	<?php $this->headScript()->captureEnd(); ?>
<div class="attribut"><a name="comments" class="nolink">Kommentare:</a><br />
<a id="switchb1" class="hide" href="#comment-insert"
	onclick="showComments();"
	style="cursor: pointer; color: #54616E"></a></div>
<div class="wert"><a id="switchc1" href="#comments" class="hide"
	onclick="showComments();"
	style="cursor: pointer; color: #54616E"></a>
	<ul id="commentList"><?php
	if (is_array ( $this->recipe->getComments() )) {
		foreach ( $this->recipe->getComments() as $comment ) {
			print '<li style="border-bottom: 1px solid rgb(170, 16, 97); margin-bottom: 0.5em;"><p>#'.($amountOfComments--).' von <em>' ;
			if ($comment->memberId) {
				$member = new Website_Model_Member ( $comment->memberId ) ;
				print '<a href="mailto:' . $this->escape($member->email) . '">' . $this->escape(stripslashes($member->firstname)) . ' ' . $this->escape(stripslashes($member->lastname)) . '</a>' ;
			} else {
				print 'anonym' ;
			}
			print '</em> am '.$comment->insertDate;
			print '<br />'.stripslashes(str_replace (array("\r\n", "\r", "\n",'\r\n', '\r', '\n'),'</p><p>',$this->escape($comment->comment))) . '</p></li>' ;
		}
	} else {
		print 'keine Kommentare vorhanden' ;
	}
	?></ul>
<form id="comment_form" class="regular_form"
	style="margin-top: 1em;"
	action="<?php print $this->url(array('module'=>'website','controller'=>'index',
		'action'=>'recipe','id'=>$this->recipe->id),null,true); ?>#comment-insert"
	method="post">
<fieldset>
	<legend><a name="comment-insert">Kommentar hinzufügen</a></legend>
	<?php if($this->error) { ?>
		<p class="error"><?php print $this->error; ?></p>
	<?php }
	if($this->success) { ?>
		<p class="success"><?php print $this->success; ?></p>
	<?php } 
	if(!$this->success) { ?>
	<label for="comment" class="clear pink left">Dein Kommentar (reiner Text):</label>  
	<textarea name="comment" id="comment" class="clear text pink left abstand_unten"><?php if($this->error) { print $_POST['comment']; } ?></textarea>
	<?php 
	$captcha = new Zend_Captcha_ReCaptcha(array(
	    'name' => 'captcha',
		'privKey' => '6LdKvggAAAAAADoKDLXugjbiSxuTc7zdrAVm8-qC',
		'pubKey' => '6LdKvggAAAAAAAhu1rSAwtIm1Ejzls4LDi0K27Td',
		'width' => 100,
		'height' => 50,
		'font' => APPLICATION_PATH.'/modules/website/captcha/fonts/arial.ttf',
		'imgDir' => realpath(APPLICATION_PATH.'/../public/img/captchas/'),
		'imgUrl' => $this->baseUrl().'/img/captchas/',
	    'expiration' => 300,
	));
	$captcha->getService()->setOption('lang','de');
	echo $captcha->render($this);
?>
<input type="submit" class="right clear small-button"
	style="background-image: url('<?php echo $this->baseUrl(); ?>/img/general-button-small4.png'); margin-top: 0.5em; margin-right: 3px;" value="abschicken"
	name="submit" /><?php } ?></fieldset>
</form>
</div>
<?php if($gesamt>1) { ?>
	<div class="attribut">Rezept- alternativen:</div>
	<div class="wert">
	<ul class="nolist">
	<?php
	foreach ($alternatives as $alternative) { ?>
		<li><?php $this->cocktailPreview($alternative); ?></li>
	<?php 
	} ?>
	</ul>
	</div>
	<?php } ?>
</div>
<!-- class=left -->
<div id="video" style="display: none;"><?php
if ($videos) {
	$i = 0 ;
	foreach ( $videos as $video ) {
		?>
<div id="box"
	style="float: left; clear: both; width: 440px; margin-left: 110px"><object
	width="425" height="350">
	<param name="movie"
		value="<?php
		echo $this->escape ( $video->url ) ;
		?>" />
	<param name="wmode" value="transparent" />
	<embed src="<?php
		echo $this->escape ( $video->url ) ;
		?>"
		type="application/x-shockwave-flash" wmode="transparent" width="425"
		height="350" /></object></div>
		<?php
	}
} else {
	?>
<div id="box"
	style="float: left; clear: both; width: 440px; margin-left: 110px">Kein
Video gefunden.</div>
	<?php
}
?></div>
<div
	style="clear: both; position: relative; height: 110px; margin-left: 25px"
	class="left">
<a name="video"></a>
<div class="left icon" style="left: 270px;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/zeit.png" alt="Zeitaufwand"
	title="Zeitaufwand" /><br />
	<?php
	print $recipe->workMin;
	?> min</div>
<div class="left icon" style="left: 180px;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($recipe->difficulty == Website_Model_Recipe::BEGINNER) {
		print "/difficulty/beginnner.png" ;
		$difficultyMessage = 'Anfänger';
	}
	else if ($recipe->difficulty == Website_Model_Recipe::ADVANCED) {
		print "/difficulty/advanced.png" ;
		$difficultyMessage = 'Fortgeschritten';
	}
	else if ($recipe->difficulty == Website_Model_Recipe::PROFI) {
		print "/difficulty/professional.png" ;
		$difficultyMessage = 'Profi';
	} else {
		// TODO: Bild erstellen, welches ausdrückt, dass es keine Information dazu gibt...
		print "/difficulty/unknown.png" ;
		$difficultyMessage = 'nicht eingestuft';
	}
	?>"
	alt="Schwierigkeitsgrad <?php
	print $difficultyMessage;
	?>"
	title="Schwierigkeitsgrad <?php
	print $difficultyMessage;
	?>" /><br />
	<?php
	print $difficultyMessage
	;
	?></div>
<div class="left icon" style="left: 0px;"><img
	src="<?php
	echo $this->baseUrl() .'/img/glasses/'. $recipe->getGlass()->getPhoto()->fileName ;
	?>"
	alt="Glas <?php
	print $recipe->getGlass()->name ;
	?>"
	title="Glas <?php
	print $recipe->getGlass()->name ;
	?>" /><br />
	<?php
	print $recipe->getGlass()->name ;
	?></div>
<div class="left icon" style="left: 360px;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/calories.png" alt="Kalorien"
	title="Kalorien" /><br />
	<?php
	print $recipe->getCaloriesKcal();
	?> kcal</div>
<div class="left icon" style="left: 450px;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/prozent.png" alt="Alkoholgehalt"
	title="Alkoholgehalt" /><br />
	<?php
	print $recipe->getAlcoholLevel();
	?> % Alkohol</div>
<div class="left icon" style="left: 90px;"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/volumen.png" alt="Volumen"
	title="Volumen" /><br />
	<?php
	print $recipe->getVolumeCl() ;
	?> cl</div>
</div>
</div>