<div class="party">
<div class="calendar block"><span class="pink">Partykalender</span> <input
	type="button"
	onclick="document.getElementById('new_party').style.display='block';"
	value="Party hinzufügen" name="action" class="pink right" />
<div class="center" style="margin-top: 0.9em; margin-bottom: 0.4em;"><select>
	<option>Januar</option>
	<option>Februar</option>
	<option>März</option>
	<option>April</option>
	<option>Mai</option>
	<option>Juni</option>
	<option>August</option>
	<option>September</option>
	<option>Oktober</option>
	<option>November</option>
	<option>Dezember</option>
</select> <input type="number" min="<?php print date('Y'); ?>"
	max="<?php print date('Y')+10; ?>" step="1"
	value="<?php print date('Y'); ?>" size="7" /></div>
<table class="center" width="100%">
	<thead>
		<tr>
			<th>M</th>
			<th>D</th>
			<th>M</th>
			<th>D</th>
			<th>F</th>
			<th>S</th>
			<th>S</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>2</td>
			<td>3</td>
			<td>4</td>
			<td>5</td>
			<td>6</td>
			<td>7</td>
		</tr>
		<tr>
			<td>8</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>12</td>
			<td class="pink">13</td>
			<td>14</td>
		</tr>
		<tr>
			<td>15</td>
			<td>16</td>
			<td>16</td>
			<td>17</td>
			<td>18</td>
			<td>19</td>
			<td>20</td>
		</tr>
		<tr>
			<td>21</td>
			<td>22</td>
			<td>23</td>
			<td>24</td>
			<td>25</td>
			<td>26</td>
			<td>27</td>
		</tr>
		<tr>
			<td>28</td>
			<td>29</td>
			<td>30</td>
			<td class="grey">1</td>
			<td class="grey">2</td>
			<td class="grey">3</td>
			<td class="grey">4</td>
		</tr>
	</tbody>
</table>
<ul>
	<li>Hawaii Party <span class="grey hide">am 10.09.2010</span><input
		type="submit" class="pink right hide" value="löschen" name="delete" />
	<hr class="light" />
	</li>
	<li>80er Jahre Party <span class="grey hide">am 1.10.2010</span><input
		type="submit" class="pink right hide" value="löschen" name="delete" />
	<hr class="light" />
	</li>
	<li class="active">Ü30 Party <span class="grey">am 13.11.2010</span> <input
		type="submit" class="pink right" value="löschen" name="delete" />
	<hr class="light" />
	</li>
</ul>


<p class="block_info">Anzahl Partys: 3 <input type="button"
	class="pink right" style="margin-left: 1em;" value="weiter &gt;"
	name="action" /> <input type="button" class="pink right"
	value="&lt; zurück" name="action" /></p>
</div>
<div class="party_detail hide" id="new_party"><span class="pink">Partydetails:</span>
<form action="" method="post"><label class="name">Name: <input
	class="right" size="30" /><span class="clear right grey smaller">(z.B.
80er Jahre Party) </span></label> <label class="date">Datum: <input
	type="date" class="right" value="<?php print date('Y-m-d'); ?>" /></label>
<input type="submit" value="Speichern" name="action" class="pink right" /><a
	class="grey button right margin_right"
	href="<?php print $this->url(array('action'=>'index')); ?>">Abbrechen</a></form>
</div>
<div class="divider"></div>
<div class="guests">
<h2 class="margin_top_small pink">Gästeliste:</h2>
<ul class="clear left margin_top_small">
	<li>Maximilian Mustermann</li>
	<li class="active">Kurt Krause <input type="submit" value="löschen"
		name="action" class="pink right margin_bottom" /></li>
	<li>Caroline Bock</li>
	<li>Maximilian Mustermann</li>
	<li>Kurt Krause</li>
	<li>Caroline Bock</li>
	<li>Maximilian Mustermann</li>
	<li>Kurt Krause</li>
	<li>Caroline Bock</li>
</ul>
<ul class="left margin_top_small">
	<li>Kurt Krause</li>
	<li>Caroline Bock</li>
	<li>Maximilian Mustermann</li>
	<li>Kurt Krause</li>
	<li>Caroline Bock</li>
	<li>Maximilian Mustermann</li>
	<li>Kurt Krause</li>
</ul>
<hr class="clear long" />
Anzahl Gäste: 16 <input type="button" class="pink right"
	style="margin-left: 1em;" value="weiter &gt;" name="action" /> <input
	type="button" class="pink right" value="&lt; zurück" name="action" />
<hr class="long" />
<h2 class="pink margin_top">Gast hinzufügen:</h2>
<div class="left margin_top"><strong>Stammgast:</strong> <br />
<label> Name: <select class="right">
	<option>Florian Helios</option>
</select></label> <input type="submit" value="Stammgast hinzufügen"
	name="action" class="pink right clear margin_top" /></div>
<div class="right margin_top"><strong>Neuer Gast:</strong> <br />
<label>Name:<input class="right" size="30" /></label> <label>E-Mail-Adresse:
<input type="email" class="right" size="20" /></label><input
	type="submit" value="Stammgast hinzufügen" name="action"
	class="pink right margin_top" /><a
	class="grey button right margin_top margin_right"
	href="<?php print $this->url(array('action'=>'index')); ?>">Abbrechen</a></div>

</div>
</div>
