<?php
/**
 * Default Layout
 *
 * @author  der cocktailberater
 * @version 1.0
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype()
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php
echo $this->headTitle()."\n";
echo $this->headScript();
echo $this->headLink();
echo $this->headStyle();
?>
</head>
<body>
<div><?php echo $this->layout()->content ?></div>
</body>
</html>