<p style="margin: 1em 0 1em 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
	    'pages'      => array(
	            array(
	                'label'      => 'Portal',
	                'module'     => 'website',
	                'controller' => 'portal',
	            	'action'	 => 'index',
	            	'pages'      => array(
			            array(
			                'label'      => 'Barkunde',
			                'module'     => 'website',
			                'controller' => 'portal',
			            	'action'	 => 'barkunde',
					    	'pages'      => array(
					            array(
					                'label'      => 'Zutatenkategorien',
					                'module'     => 'website',
					                'controller' => 'ingredient-category'
					           	)
						)
					)
				)
			)
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<div>
<h2 style="margin-top: 0;">Zutatenkategorien</h2>
<?php $i=0;
foreach ($this->ingredientCategories as $ingredientCategory){ 
	$i++; 
	if($i!=1) { print ', '; } ?><a href="#<?php print $ingredientCategory->getUniqueName(); ?>"><?php print $ingredientCategory->name; ?></a><?php 
} ?>
<?php foreach ($this->ingredientCategories as $ingredientCategory){ ?>
<h3 id="<?php print $ingredientCategory->getUniqueName(); ?>"
 style="margin-bottom: 0.5em;"><a 
 href="<?php print $this->url(
 array('controller'=>'ingredient-category','action'=>'get','module'=>'website',
 'id'=>$ingredientCategory->getUniqueName())); ?>?format=mobile"><?php 
 print $ingredientCategory->name; ?></a></h3>
<table class="table" style="margin-bottom: 2em;">
	<thead>
		<tr>
			<th>Zutat</th>
			<th>Kalorien</th>
			<th>Preis</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach (Website_Model_IngredientCategory::getIngredientsByCategory($ingredientCategory->id) as $ingredient){ ?>
		<tr>
			<td><a
				href="<?php print $this->url(array('controller'=>'ingredient','action'=>'get','module'=>'website','id'=>$ingredient->getUniqueName())); ?>?format=mobile">
				<?php print $ingredient->name; ?></a> (<?php if($ingredient->getAverageAlcoholLevel()) { print $ingredient->getAverageAlcoholLevel().' %'; } else { print '0 %'; } ?>)<?php 
			if($ingredient->getRecipes()) {
				$i=0;
				foreach($ingredient->getRecipes() as $recipe){
					$i++;
				}
				?>, <a
				href="<?php print $this->url(array('controller'=>'ingredient','action'=>'get','module'=>'website','id'=>$ingredient->getUniqueName())); ?>?format=mobile#recipes-list"><?php print $i; ?>
			Rezepte</a><?php
			}
			?><?php 
			$products = Website_Model_Product::productsByIngredientId($ingredient->id);
			if(is_array($products)) {
				$i=0;
				foreach ($products as $product) {
					$i++;
				}
			}
			?>, <a
				href="<?php print $this->url(array('controller'=>'ingredient','action'=>'get','module'=>'website','id'=>$ingredient->getUniqueName())); ?>?format=mobile#products-list"><?php print $i; ?>
			Produkte</a></td>
			<td><?php if($ingredient->getAverageCaloriesKcal()) { print round($ingredient->getAverageCaloriesKcal()/10); ?>&nbsp;kcal<?php } else { print 'k.A.'; } ?></td>
			<td><?php 
			if($ingredient->getAveragePricePerLitre() || $ingredient->getAveragePricePerKilogram()) {
				if($ingredient->getAveragePricePerLitre()) {
					print number_format($ingredient->getAveragePricePerLitre(),2,',','.').'&nbsp;€&nbsp;/&nbsp;l ';
				}
				if($ingredient->getAveragePricePerLitre() && $ingredient->getAveragePricePerKilogram()) {
					print ' bzw. ';
				}
				if($ingredient->getAveragePricePerKilogram()) {
					print number_format($ingredient->getAveragePricePerKilogram(),2,',','.').'&nbsp;€&nbsp;/&nbsp;kg';
				}
			} ?></td>
		</tr>
		<?php } ?>
	</tbody>
</table><?php } ?>
</div>