<?php
$this->addScriptPath('../application/modules/website/views/partials');
if($this->contact['salutation']=='Frau') {
	print 'Sehr geehrte';
	print ' '.$this->contact['salutation'];
	print ' '.$this->contact['lastname'].','."\n\n";

} else if($this->contact['salutation']=='Herr'){
	print 'Sehr geehrter';
	print ' '.$this->contact['salutation'];
	print ' '.$this->contact['lastname'].','."\n\n";
}else if($this->contact['salutation']=='Firma' OR $this->contact['salutation']==''){
	print 'Sehr geehrte Damen und Herren'.",\n\n";
}
print 'vielen Dank für Ihre Anfrage auf cocktailberater.de. Sie haben folgende persönlichen Daten angegeben'.':'."\n\n";
print $this->partial('contact-mail-person.phtml', $this);
print 'Folgende Nachricht haben Sie angegeben'.':'."\n\n";
print $this->partial('contact-mail-details.phtml', $this);
print 'Mit freundlichen Grüßen,'."\n";
print 'Ihr cocktailberater Team.'."\n";
?>