<?php require ("views/scripts/template/header.phtml"); ?>
<h2>Newsletterabmeldung von cocktailberater.de!</h2>
<p>Es ist nur noch ein Schritt nötig, um Ihre Newsletterabmeldung zu
vervollständigen:<br />
<br />
<a
	href="<?php print $this->baseUrl(); ?>index/newsletterAbmeldungBestaetigung/email/<?php print $this->email; ?>"
	style="text-decoration: underline">Newsletterabmeldung bestätigen</a><br />
<br />
Vielen Dank.</p>
<?php require ("views/scripts/template/footer.phtml"); ?>