<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$membersXML = $this->xml->createElement('members');
if(is_array($this->members)){
	foreach ($this->members as $member){
		$member->toXml($this->xml,$membersXML);
	}
}
// set count for recipe element according to number of recipes found
$membersXML->setAttribute('count',count($this->members));
// add the '$recipes' element to the 'rsp' element
$this->rsp->appendChild($membersXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
