<h1>Uuups, da ist wohl etwas dazwischen gekommen....</h1>
<h2><?php echo $this->message ?></h2>
<?php if ('testing' == APPLICATION_ENV || 'development' == APPLICATION_ENV || 'thobamac' == APPLICATION_ENV){ ?>
<h3>Exception information:</h3>
<pre style="font-family: Courier; overflow: scroll; margin: 0 25px;">
<?php echo $this->exception; ?>
</pre>
<h3>Request Parameters:</h3>
<pre><?php var_dump($this->request->getParams()) ?>
  </pre>
<?php } ?>