<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$guestsXML = $this->xml->createElement('guests');
if(is_array($this->guests)){
	foreach ($this->guests as $order){
		$order->toXml($this->xml,$guestsXML);
	}
}
// set count for recipe element according to number of recipes found
$guestsXML->setAttribute('count',count($this->guests));
$guestsXML->setAttribute('party',count($this->party));
// add the '$recipes' element to the 'rsp' element
$this->rsp->appendChild($guestsXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
