<ul>
	<li><a href="<?php echo $this->url(array('module'=>'website')); ?>">Website</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'api')); ?>">API</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'test')); ?>">Tests</a></li>
	<li><a href="http://admin.cocktailberater.de/update-test.php">Update Test</a> (unnötig da Continous Integration)</li>
	<li><a href="http://admin.cocktailberater.de/update-stage.php">Update Stage</a></li>
	<li><a href="http://admin.cocktailberater.de/update-life.php">Update Life</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'admin','action'=>'disable-analytics')); ?>">Disable Analytics</a></li>
</ul>
