<div class="content">
<h2>Produkte für Cocktailrezepte</h2>
<?php 
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
$this->dojo()->enable()->requireModule('dijit.Tooltip');
$this->headScript()->captureStart();
?>
dojo.addOnLoad(function() {
	priceTooltip = new dijit.Tooltip({
		connectId: ["priceTooltip"],
		label: "Errechneter Durschnittspreis von verschiedenen (Online)-Händlern"
	});
	caloriesTooltip = new dijit.Tooltip({
		connectId: ["caloriesTooltip"],
		label: "Gesamtkalorien des Produktes"
	});
});
<?php $this->headScript()->captureEnd(); ?>
<table class="table clear">
	<thead>
		<tr>
			<th>Produkt (Hersteller / Marke)</th>
			<th>Zutat &amp; Alkohol- / Fruchtgehalt</th>
			<th class="textRight"><a href="#" class="tip pink" id="caloriesTooltip">Kalorien</a> &amp; <a href="#" class="tip pink" id="priceTooltip">Preis</a></th>
			<th class="textRight">Rezepte</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->products as $product){ ?>
	<tr>
		<td><a href="<?php print $this->url(
			array('id'=>$product->getUniqueName(),'controller'=>'product',
			'action'=>'get','module'=>'website')); ?>"><?php print $product->name; ?></a> 
		<?php if($product->getManufacturer() && $product->getManufacturer()->name){ ?>
			(<a href="<?php print $this->url(array('controller'=>'manufacturer',
			'id'=>$product->getManufacturer()->getUniqueName())); ?>"><?php 
			print $product->getManufacturer()->name; ?></a>)
		<?php } ?> 
		<?php print number_format($product->size,2,',','.').'&nbsp;'.$product->unit; ?></td>
		<td>
		<?php if($product->getIngredient()) { ?>
			<a href="<?php print $this->url(array('id'=>$product->getIngredient()->getUniqueName(),
			'controller'=>'ingredient','action'=>'get','module'=>'website')); ?>"><?php 
			print $product->getIngredient()->name; ?></a>
		<?php } ?><br /><?php print round($product->alcoholLevel); ?>&nbsp;% / 
			<?php print round($product->fruitConcentration); ?>&nbsp;%</td>
		<td class="textRight"><?php if($product->caloriesKcal!==null){ 
			print number_format($product->caloriesKcal,0,',','.'); ?>&nbsp;kcal<?php 
		} else {
			?>k.A.<?php 
		} ?><br /><?php if($product->getAveragePrice()) {
			print number_format($product->getAveragePrice(),2,',','.').'&nbsp;€';
		} 
		else { 
			print 'k.A.'; 
		} ?></td>
		<td class="textRight"><?php $numberOfRecipes = $product->getNumberOfRecipes(); 
		if($numberOfRecipes>0){ ?>
			<a href="<?php echo $this->url(array('controller'=>'product',
				'id'=>$product->getUniqueName(),'action'=>'get','module'=>'website')); ?>#recipes-list"><?php 
			echo $numberOfRecipes; ?>&nbsp;Stk.</a>
		<?php } 
		else { ?>
			keine
		<?php } ?></td>
	</tr>
	<?php } ?>
	</tbody>
</table>
</div>