<?php
/**
 * Kontakt view
 *
 * @author  Thomas Bachmann
 * @version 1.0
 */
?>
<div class="content abstand_links_doppelt" style="width: 600px">
<h2>Nehmen Sie mit uns Kontakt auf!</h2>
<p class="abstand_unten">Mit diesem Formular können Sie schnell und einfach mit uns in Kontakt
treten.<br />
Wir freuen uns auf Ihre Nachricht!</p>
<?php if($this->form->isErrors()){ ?>
<div class="error"><?php echo $this->translate('Fehler aufgetreten!'); ?></div>
<?php } ?>
<?php echo $this->form; ?>
<p class="clear">(*) <?php echo $this->translate('Pflichtfeld'); ?></p>
</div>