<h2 class="pink" style="font-size: 1.2em; margin:0;">Rezepte mit dem Tag &quot;<?php echo $this->tag; ?>&quot;:</h2>
<ul style="text-align:left"><?php
foreach ($this->recipes as $key => $recipe) {
	$photos = $recipe->getPhotos();
	?><li style="width: 15em; padding: 0.2em; line-height: 2em;">
	<p>
		<img style="height: 1.5em; float: left; margin-right: 0.5em; margin-top: 0.2em; margin-bottom: 0.2em;"
			src="<?php print $this->baseUrl();
			if(isset($photos[0]) && $photos[0]->id){
				print '/img/recipes/'.$this->escape($photos[0]->fileName);
			} else { 
				print '/img/wikilogo.png';
			} ?>" />
		<?php echo $this->escape(str_replace('\\','',$recipe->name)) ?>
	</p>
	</li>
	<?php
} ?></ul>