<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$menuesXML = $this->xml->createElement('menues');
if(is_array($this->menues)){
	foreach ($this->menues as $menue){
		$menue->toXml($this->xml,$menuesXML);
	}
}
// set count for recipe element according to number of recipes found
$menuesXML->setAttribute('count',count($this->menues));
// add the '$recipes' element to the 'rsp' element
$this->rsp->appendChild($menuesXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
