<body onLoad="javascript:pageTracker._setVar('test_value');">
<p>Setting 'test_value' variable for google analytics, see <a
	href="http://www.google.com/support/googleanalytics/bin/answer.py?answer=55481">documentation</a>.</p>
<!-- Google Analytics START -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
	var pageTracker = _gat._getTracker("UA-7324992-1");
	pageTracker._trackPageview();
} catch(err) {
	
}</script>
<!-- Google Analytics END -->