<?php 
// for JS-fallback
$currentShow =  Zend_Controller_Front::getInstance()->getRequest()->getParam('show');
// HTML 5 header
echo $this->doctype('HTML5'); 
?>
<html>
<head>
<meta charset="utf-8" />
<?php
// title
$title = 'Cocktail Rezepte vom cocktailberater';
if($this->layout()->getView()->title!='') {
	$title =  $this->layout()->getView()->title. ' vom cocktailberater';
}
echo $this->headTitle($title);
// meta
// setting content type and character set
$this->headMeta()->appendHttpEquiv('Content-Type',
                                   'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'de');
// setting meta generator
$this->headMeta()->setName('generator', 'cocktailberater version '.APPLICATION_VERSION);
// setting meta robots
$this->headMeta()->setName('robots', 'index,follow');
echo $this->headMeta();
// echo styles
echo $this->headStyle()."\n";
// dojo
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
$this->dojo()->enable();
$this->dojo()->setDjConfigOption('parseOnLoad', true);
$this->dojo()->setDjConfigOption('baseUrl', './');
$this->dojo()->addStyleSheetModule('dijit.themes.tundra');
// for dropdown boxes in at the top
$this->dojo()->requireModule('dijit.Dialog');
//$this->dojo()->requireModule('dijit.form.FilteringSelect');
//$this->dojo()->requireModule('dijit.form.Button');
// end for dropdown boxes
echo $this->dojo()."\n";
// css style sheets
$this->headLink()->appendStylesheet($this->baseUrl().'/css/screen.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/print.css','print');
// faveicon
$this->headLink(array('rel' => 'shortcut icon',
                      'href' => $this->baseUrl().'/favicon.ico'),
                      'PREPEND');
// feed (rss & atom)
$this->headLink(array('rel' => 'alternate',
					  'type' => 'application/atom+xml',
					  'title' => 'cocktailberater - Atom',
                      'href' => 'http://blog.cocktailberater.de/feeds/posts/default'));
$this->headLink(array('rel' => 'alternate',
					  'type' => 'application/rss+xml',
					  'title' => 'cocktailberater - RSS',
                      'href' => 'http://blog.cocktailberater.de/feeds/posts/default?alt=rss'));
$this->headLink(array('rel' => 'image_src',
					  'type' => 'image/jpeg',
                      'href' => 'http://www.cocktailberater.de/img/logo.png'));
// echo css, faveicon and feeds
echo $this->headLink()."\n";
// toggeling dialogs
$this->headScript()->captureStart(); ?>

// prevent from hiding immidiately after showing dialog 
// (body -> onclick is called after every click anywhere) 
var hideDialog;



// show dialog
function showDialog(dialog,show){
	// remove non-JS borders and paddings
	dojo.query('ul.noJS').removeClass('noJS');
	
	// hide active dialog
	if(show == false) { // dojo.byId(dialog).style.display == 'block' 
		dojo.byId(dialog).style.display = 'none';
	} 
	// show only activated dialog
	else {
		// hide all dialogs
		dojo.query('div.dijitTooltipDialog', document).forEach( 
			function(selectTag) {
				selectTag.style.display = 'none';
			}
		);
		// show activated dialog
		dojo.byId(dialog).style.display = 'block';
	}
	// don't hide all dialogs immidiately
	hideDialog = false;
	// don't call the url in a -> href
	return false;
}

// hide all dialogs (body -> onclick)
function hideDialogs(){
	// only hide all dialogs if NOT clicked on any link
	if(hideDialog){
		dojo.query('div.dijitTooltipDialog', document).forEach( 
			function(selectTag) {
				selectTag.style.display = 'none';
			}
		);
		
	}
	// next time the user clicks anywhere BUT the link hide all dialogs
	hideDialog = true;
}
<?php $this->headScript()->captureEnd();
// echo scripts
echo $this->headScript()."\n";
?>
</head>
<body class="tundra" onclick="hideDialogs();">
<!-- begin: top links -->
<div id="pre-header">
	<ul>
		<!-- social bookmarking & RSS -->
		<li style="margin-left: 1em;" 
			onmouseover="dojo.byId('spr_facebook_fan_gray').id='spr_facebook_fan';" 
			onmouseout="dojo.byId('spr_facebook_fan').id='spr_facebook_fan_gray';">
			<a href="http://www.facebook.com/pages/cocktailberater/132058865565" style="padding-top: 0.2em; padding-bottom: 0.2em;">
				<span class="social_sprites" id="spr_facebook_fan_gray"></span> Fan werden
			</a></li>
		<li style="margin-left: 1em;"
			onmouseover="dojo.byId('spr_facebook_share_gray').id='spr_facebook_share';" 
			onmouseout="dojo.byId('spr_facebook_share').id='spr_facebook_share_gray';">
			<a style="padding-top: 0.2em; padding-bottom: 0.2em;"
				href="http://www.facebook.com/sharer.php?u=http://www.cocktailberater.de<?php echo $this->url(); ?>&amp;t=<?php echo urlencode($title); ?>">
				<span class="social_sprites" id="spr_facebook_share_gray"></span> Teilen</a></li>
		<li style="margin-left: 1em;">
			<a href="http://del.icio.us/post?url=http://www.cocktailberater.de<?php echo $this->url(); ?>&amp;title=<?php echo urlencode($title); ?>">
				<span class="social_sprites" id="spr_delicious"></span>
			</a></li>
		<li style="margin-left: 1em;">
			<a href="http://digg.com/submit?phase=2&amp;url=http://www.cocktailberater.de<?php echo $this->url(); ?>&amp;title=<?php echo urlencode($title); ?>">
				<span class="social_sprites" id="spr_digg"></span>
			</a></li>
		<li style="margin-left: 1em;">
			<a href="http://www.stumbleupon.com/submit?url=http://www.cocktailberater.de<?php echo $this->url(); ?>&amp;title=<?php echo urlencode($title); ?>">
			<span class="social_sprites" id="spr_su"></span>
			</a></li>
		<li style="margin-left: 1em;">
			<a href="http://twitter.com/home?status=<?php echo urlencode($title . ': http://www.cocktailberater.de' . $this->url()); ?>">
				<span class="social_sprites" id="spr_twitter"></span>
			</a></li>
		<li><a href="http://blog.cocktailberater.de/feeds/posts/default">
				<span class="social_sprites" id="spr_rss"></span>
			</a></li>
			
		<!-- kontakt -->
		<li>
			<a href="<?php if($currentShow=='contact') { $show = 'none'; } 
				else { $show = 'contact'; } echo $this->url(array('show'=>$show)); ?>" 
				onmouseover="return showDialog('tooltipDlg3', true);" onclick="return false;">kontakt 
			<img src="<?php print $this->baseUrl(); ?>/img/down.png" alt="Pfeil nach unten" height="7" width="10" /></a>
			<div dojoType="dijit.TooltipDialog" id="tooltipDlg3" onmouseover="return showDialog('tooltipDlg3', true);" onmouseout="return showDialog('tooltipDlg3', false);"
				style="<?php if($currentShow!='contact') { ?>display: none;<?php } ?> position: absolute; margin-left: -17em; padding: 0 4em 4em 4em;">
			    <ul class="noJS">
			    	<li><a href="<?php print $this->url(array(
							'module'=>'website',
							'controller'=>'portal',
							'action'=>'imprint'),'default',true); ?>">impressum</a></li>
					<li><a href="<?php print $this->url(array(
							'module'=>'website',
							'controller'=>'portal',
							'action'=>'contact'),'default',true); ?>">kontakt</a></li>
					<li><a href="http://www.thobach.de">thomas bachmann (entwickler)</a></li>
					<li><a href="http://www.carolinebock.de">caroline bock (designer)</a></li>
				</ul>
			</div>
		</li>
		
		<!-- cocktailberater auf -->
		<li>
			<a href="<?php if($currentShow=='partner') { $show = 'none'; } 
				else { $show = 'partner'; } echo $this->url(array('show'=>$show)); ?>" 
				onmouseover="return showDialog('tooltipDlg1', true);" onclick="return false;">über cocktailberater 
			<img src="<?php print $this->baseUrl(); ?>/img/down.png" height="7" width="10"
				alt="Pfeil nach unten" /></a>
			<div dojoType="dijit.TooltipDialog" id="tooltipDlg1" onmouseover="return showDialog('tooltipDlg1', true);" onmouseout="return showDialog('tooltipDlg1', false);" 	
				style="<?php if($currentShow!='partner') { ?>display: none;<?php } ?> position: absolute; margin-left: -4.5em; padding: 0 4em 4em 4em;">
			    <ul class="noJS">
			    	<li><a href="http://www.facebook.com/pages/cocktailberater/132058865565">cb auf facebook</a></li>
					<li><a href="http://twitter.com/cocktailberater">cb auf twitter</a></li>
					<li><a href="http://ohloh.net/p/cocktailberater">cb auf ohloh</a></li>
					<li><a href="http://code.google.com/p/cocktailberater/">cb auf google code</a></li>
					<li><a href="http://code.google.com/p/cocktailberater/issues/entry">fehler gefunden?</a></li>
					<li><a href="http://code.google.com/p/cocktailberater/wiki/API">api dokumentation</a></li>
			    </ul>
			</div>
		</li>
		
		<!-- projekte -->
		<li>
			<a href="<?php if($currentShow=='projects') { $show = 'none'; } else { $show = 'projects'; } echo $this->url(array('show'=>$show)); ?>" 
				onmouseover="return showDialog('tooltipDlg2', true);" onclick="return false;">projekte <img src="<?php print $this->baseUrl(); ?>/img/down.png" height="7" width="10"
				alt="Pfeil nach unten" /></a>
			<div dojoType="dijit.TooltipDialog" id="tooltipDlg2" onmouseover="return showDialog('tooltipDlg2', true);" onmouseout="return showDialog('tooltipDlg2', false);" 
				style="<?php if($currentShow!='projects') { ?>display: none;<?php } ?> position: absolute; margin-left: -9em; padding: 0 4em 4em 4em;">
		    	<ul class="noJS">
		    		<li><a href="<?php print $this->url(array(
						'module'=>'website',
						'controller'=>'index',
						'action'=>'index'),'default',true); ?>">rezeptdatenbank</a></li>
		    		<li><a href="http://blog.cocktailberater.de">entwickler blog</a></li>
		    		<li><a href="<?php print $this->url(array(
						'module'=>'website',
						'controller'=>'portal',
						'action'=>'barkunde'),'default',true); ?>">barkunde</a></li>
					<li><a href="<?php print $this->url(array(
						'module'=>'website',
						'controller'=>'portal',
						'action'=>'hausbar'),'default',true); ?>">hausbar</a></li>
					<li><a href="<?php print $this->url(array(
						'module'=>'website',
						'controller'=>'portal',
						'action'=>'community'),'default',true); ?>">community</a></li>
		    	</ul>
			</div>
		</li>
	</ul>
</div>
<!-- end: top links -->
<div id="wrapper">
<?php
// show full header only start page 
if(Zend_Controller_Front::getInstance()->getRequest()->getActionName()=='index' &&	
	Zend_Controller_Front::getInstance()->getRequest()->getControllerName()=='index') { 
	$headStyle = 'background-image: url(\''.$this->baseUrl().'/img/header.png\'); height: 142px;';
	$linkStyle = 'height: 142px;';
	$homeStyle = '';
	$homeStyleHover = '';
}
// show small header on all other pages
else { 
	$headStyle = 'background-image: url(\''.$this->baseUrl().'/img/header-detail.png\'); height: 50px;';
	$linkStyle = 'height: 50px;'; 
	$homeStyle = '<div id="home_hover" style="position: relative; background: url(\''.$this->baseUrl().'/img/home.png'.'\') no-repeat; height: 40px; left: 270px; top: 6px; display: none;">&nbsp;</div>';
	$homeStyleHover = ' onmouseover="document.getElementById(\'home_hover\').style.display=\'block\';"  onmouseout="document.getElementById(\'home_hover\').style.display=\'none\';"';
}
?>
	<div id="header" style="<?php echo $headStyle; ?>"<?php print $homeStyleHover; ?>>
		<a href="<?php 
		$mainPage = array('controller'=>'index','action'=>'index','module'=>'website');
		print $this->url($mainPage,null,true); ?>" style="<?php echo $linkStyle;?>"><h1>cocktailberater</h1><?php print $homeStyle; ?></a>
	</div><!-- id:header -->
	<div id="homepage">
		<div id="content"><?php echo $this->layout()->content ?></div>
	</div><!-- id:homepage -->
	<div class="clear"></div>
</div><!-- id:wrapper -->
<?php if(APPLICATION_ENV=='production') {?>
<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://stats.thobach.de/" : "http://stats.thobach.de/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 4);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://stats.thobach.de/piwik.php?idsite=4" style="border:0" alt=""/></p></noscript>
<!-- End Piwik Tag -->
<?php } ?>
</body>
</html>
