<!-- layout.html.phtml --><?php
// for JS-fallback
$currentShow =  Zend_Controller_Front::getInstance()->getRequest()->getParam('show');
// HTML 5 header
echo $this->doctype('HTML5')."\n";
?>
<html lang="de-DE" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/">
<head>
<meta charset=utf-8>
<?php
// meta
// setting content type and character set
//$this->headMeta()->setCharset('UTF-8');
// title
$title = 'Cocktail Rezepte vom cocktailberater';
if($this->layout()->getView()->title!='') {
	$title =  strip_tags($this->layout()->getView()->title). ' vom cocktailberater';
}
echo $this->headTitle($title)."\n";
// meta
// setting meta generator
$this->headMeta()->setName('generator', 'cocktailberater version '.APPLICATION_VERSION);
// setting meta robots
$this->headMeta()->setName('robots', 'index,follow');
// setting google verification
$this->headMeta()->setName('google-site-verification', 'L3zaslftTHZhIO01_Og9b-KvBNM7mecVfIyMMcj2IdM');
echo $this->headMeta();
// setting meta data for facebook
print '<meta property="og:title" content="'.str_replace(' vom cocktailberater','',$title).'" />';
// type
$type = 'website';
if($this->placeholder('type')!='') {
	$type =  $this->placeholder('type');
}
print '<meta property="og:type" content="'.$type.'" />';
print '<meta property="og:url" content="http://www.cocktailberater.de'.urlencode($_SERVER['REQUEST_URI']).'" />';
print '<meta property="og:site_name" content="cocktailberater" />';
// image
$image = 'http://www.cocktailberater.de/img/logo.png';
if($this->placeholder('image')!='') {
	$image =  $this->placeholder('image');
}
print '<meta property="og:image" content="'.$image.'" />';
print '<meta property="fb:admins" content="563752616" />';
print '<meta property="fb:app_id" content="111381035582024" />';
// echo styles
echo $this->headStyle()."\n";
// dojo
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
$this->dojo()->enable();
$this->dojo()->setDjConfigOption('parseOnLoad', true);
$this->dojo()->setDjConfigOption('baseUrl', './');
$this->dojo()->addStyleSheetModule('dijit.themes.tundra');
echo $this->dojo()."\n";
// css style sheets
$this->headLink()->appendStylesheet($this->baseUrl().'/css/screen.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/print.css','print');
// faveicon
$this->headLink(array('rel' => 'shortcut icon',
                      'href' => $this->baseUrl().'/favicon.ico'),
                      'PREPEND');
// feed of blog (rss & atom)
$this->headLink(array('rel' => 'alternate',
					  'type' => 'application/atom+xml',
					  'title' => 'cocktailberater.de Blog - Atom',
                      'href' => 'http://blog.cocktailberater.de/feeds/posts/default'));
$this->headLink(array('rel' => 'alternate',
					  'type' => 'application/rss+xml',
					  'title' => 'cocktailberater.de Blog - RSS',
                      'href' => 'http://blog.cocktailberater.de/feeds/posts/default?alt=rss'));
// e.g. for facebook sharing
$this->headLink(array('rel' => 'image_src',
					  'type' => 'image/jpeg',
                      'href' => $image));
// echo css, faveicon and feeds
echo $this->headLink()."\n";
// echo scripts
echo $this->headScript()."\n";
?>
</head>
<body class="tundra">
<!-- begin: top links -->
<div id="pre-header">
<?php 
$imprintLink = array('module'=>'website','controller'=>'portal','action'=>'imprint');
?>
<ul class="no-bullet">
	<li onmouseover="dojo.byId('spr_info_gray').id='spr_info';"
		onmouseout="dojo.byId('spr_info').id='spr_info_gray';"><a
		href="<?php print $this->url($imprintLink,'default',true); ?>"> <span
		class="social_sprites" id="spr_info_gray"></span> Impressum</a></li>
	<li onmouseover="dojo.byId('spr_rss_gray').id='spr_rss';"
		onmouseout="dojo.byId('spr_rss').id='spr_rss_gray';"><a
		href="http://blog.cocktailberater.de/feeds/posts/default"
		title="Blog als RSS-Feed abonnieren"> <span class="social_sprites"
		id="spr_rss_gray"></span> Blog </a></li>
	<li onmouseover="dojo.byId('spr_mobile_gray').id='spr_mobile';"
		onmouseout="dojo.byId('spr_mobile').id='spr_mobile_gray';"><a
		href="?format=mobile"> <span class="social_sprites"
		id="spr_mobile_gray"></span> Mobile Seite</a></li>
	<li
		onmouseover="dojo.byId('spr_facebook_fan_gray').id='spr_facebook_fan';"
		onmouseout="dojo.byId('spr_facebook_fan').id='spr_facebook_fan_gray';">
	<a href="http://www.facebook.com/cocktailberater"
		title="auf facebook Fan werden"> <span class="social_sprites"
		id="spr_facebook_fan_gray"></span> Fan werden </a></li>
	<li
		onmouseover="dojo.byId('spr_facebook_share_gray').id='spr_facebook_share';"
		onmouseout="dojo.byId('spr_facebook_share').id='spr_facebook_share_gray';">
	<a
		href="http://www.facebook.com/sharer.php?u=<?php echo urlencode('http://www.cocktailberater.de'.$_SERVER['REQUEST_URI']); ?>&amp;t=<?php echo urlencode($title); ?>"
		title="auf facebook teilen"> <span class="social_sprites"
		id="spr_facebook_share_gray"></span> Teilen</a></li>
	<li onmouseover="dojo.byId('spr_twitter_gray').id='spr_twitter';"
		onmouseout="dojo.byId('spr_twitter').id='spr_twitter_gray';"><a
		href="http://twitter.com/home?status=<?php echo urlencode($title . ': http://www.cocktailberater.de' . $_SERVER['REQUEST_URI']); ?>"
		title="auf Twitter posten"> <span class="social_sprites"
		id="spr_twitter_gray"></span> Twittern </a></li>
	<li class="left"><a
		href="http://del.icio.us/post?url=<?php echo urlencode('http://www.cocktailberater.de'.$_SERVER['REQUEST_URI']); ?>&amp;title=<?php echo urlencode($title); ?>"
		title="auf delicious bookmarken"> <span class="social_sprites"
		id="spr_delicious"></span> <span class="hide">delicious</span> </a></li>
	<li class="left"><a
		href="http://digg.com/submit?phase=2&amp;url=<?php echo urlencode('http://www.cocktailberater.de'.$_SERVER['REQUEST_URI']); ?>&amp;title=<?php echo urlencode($title); ?>"
		title="auf Digg bookmarken"> <span class="social_sprites"
		id="spr_digg"></span> <span class="hide">Digg</span> </a></li>
	<li class="left"><a
		href="http://www.stumbleupon.com/submit?url=<?php echo urlencode('http://www.cocktailberater.de'.$_SERVER['REQUEST_URI']); ?>&amp;title=<?php echo urlencode($title); ?>"
		title="auf StumbleUpon bookmarken"> <span class="social_sprites"
		id="spr_su"></span> <span class="hide">StumbleUpon</span> </a></li>
</ul>
</div>
<!-- end: top links -->
<div id="wrapper">
<?php
// show full header only start page 
if(Zend_Controller_Front::getInstance()->getRequest()->getActionName()=='index' &&	
	Zend_Controller_Front::getInstance()->getRequest()->getControllerName()=='index') { 
	$headStyle = 'background-image: url(\''.$this->baseUrl().'/img/header.png\'); height: 142px;';
	$linkStyle = 'height: 142px;';
	$homeStyle = '';
	$homeStyleHover = '';
}
// show small header on all other pages
else { 
	$headStyle = 'background-image: url(\''.$this->baseUrl().'/img/header-detail.png\'); height: 50px;';
	$linkStyle = 'height: 50px;'; 
	$homeStyle = '<span id="home_hover" style="position: relative; background: url(\''.$this->baseUrl().'/img/home.png'.'\') no-repeat; height: 40px; left: 270px; top: 6px; display: none; width: 100px;">&nbsp;</span>';
	$homeStyleHover = ' onmouseover="document.getElementById(\'home_hover\').style.display=\'block\';"  onmouseout="document.getElementById(\'home_hover\').style.display=\'none\';"';
}
?>
	<div id="header" style="<?php echo $headStyle; ?>"<?php print $homeStyleHover; ?>>
		<h1 style="margin: 0;"><a href="<?php 
		$mainPage = array('controller'=>'index','action'=>'index','module'=>'website');
		print $this->url($mainPage,null,true); ?>" style="<?php echo $linkStyle;?>"><span class="hide">cocktailberater</span><?php print $homeStyle; ?></a></h1>
	</div><!-- id:header -->
	<div id="homepage">
	<?php
	$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$controllersForBreadcrumb = array('portal','ingredient','product','manufacturer');
	if(in_array($controller, $controllersForBreadcrumb)) { ?>
		<p class="breadcrumb">
		<?php if($this->format=='html') { ?>Sie sind hier: <?php }
		$portalNavigationConfig = new Zend_Config_Ini(APPLICATION_PATH.'/modules/website/config/portal-navigation.ini','nav');
		$container = new Zend_Navigation($portalNavigationConfig);
		if($this->format=='html') {
			echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs()->setSeparator(' &gt;'.PHP_EOL));
		} else {
			echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs()->setSeparator(' &gt;'.PHP_EOL));
		}
		if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>
	<?php } ?>
	<div id="content"><?php echo $this->layout()->content ?></div>
	<?php 
	// render menu for portal pages
	if(in_array($controller, $controllersForBreadcrumb)) {
		$community = $this->navigation()->findOneByLabel('Portal');
		$options = array(
		    'ulClass' => 'textLeft no-bullet-html'
		);
		echo '<div class="sub_nav">'.$this->navigation()->menu()->renderMenu($community, $options).'</div>';
	}
	?>
	</div><!-- id:homepage -->
	<div class="clear"></div>
</div><!-- id:wrapper -->
<?php if(APPLICATION_ENV=='production') { ?>
<!-- Piwik -->
<script type="text/javascript">
	var pkBaseURL = (("https:" == document.location.protocol) ? "https://stats.thobach.de/" : "http://stats.thobach.de/");
	document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
	try {
		var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 4);
		piwikTracker.trackPageView();
		piwikTracker.enableLinkTracking();
	} catch( err ) {}
</script>
<noscript>
<p><img src="http://stats.thobach.de/piwik.php?idsite=4"
	style="border: 0" alt="" /></p>
</noscript>
<!-- End Piwik Tag -->
<?php } ?>
</body>
</html>
