<?php
$components = '';
foreach ($this->recipe->getComponents() as $component){
	$components .= $component->amount.' '.$component->unit.' '.$component->getIngredient()->name.'<br />';
}
$entries[] = array(
	'title'       	=> $this->recipe->name,
	'link'        	=> $this->url(array(
		'id'			=>$this->recipe->id,
		'cocktail'		=>$this->_getParam('cocktail'),
		'format'		=>$this->format)),
	'description' 	=> $this->recipe->description."<br /><br />".$components."<br />".$this->recipe->instruction,
);


// Create the RSS array
$rss = array(
	'title'   => 'cocktailberater',
	'link'    => 'http://www.cocktailberater.de',
	'charset' => 'UTF-8',
	'entries' => $entries
);

// Import the array
$feed = Zend_Feed::importArray($rss, $this->format);
print $feed->saveXML();