<?php
// for JS-fallback
$currentShow =  Zend_Controller_Front::getInstance()->getRequest()->getParam('show');
echo '<?xml version="1.0" encoding="utf-8"?>';
?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
// title
$title = 'Cocktail Rezepte vom cocktailberater';
if($this->layout()->getView()->title!='') {
	$title =  $this->layout()->getView()->title. ' vom cocktailberater';
}
echo $this->headTitle($title)."\n";
// meta
// setting content type and character set
//$this->headMeta()->appendHttpEquiv('Content-Type',
 //                                  'text/html; charset=UTF-8');
// setting client-side cache
$this->headMeta()->appendHttpEquiv('expires',
                                   gmdate('D, d M Y H:i:s', time()+$expires) . ' GMT')
                 ->appendHttpEquiv('pragma', 'private')
                 ->appendHttpEquiv('Cache-Control', 'private');
// also enable caching in HTTP header
// seconds, minutes, hours, days
$expires = 60*60*24*7;
header("Pragma: private");
header("Cache-Control: maxage=".$expires);
header('Expires: ' . gmdate('D, d M Y H:i:s', time()+$expires) . ' GMT');
 // setting meta generator
$this->headMeta()->setName('generator', 'cocktailberater version '.APPLICATION_VERSION);
// setting meta robots
$this->headMeta()->setName('robots', 'index,follow');
// setting meta viewport
$this->headMeta()->setName('viewport', 'width=device-width, initial-scale=1, maxium-scale=1');
// setting google verification
$this->headMeta()->setName('google-site-verification', 'L3zaslftTHZhIO01_Og9b-KvBNM7mecVfIyMMcj2IdM');
echo $this->headMeta();
// echo styles
echo $this->headStyle()."\n";
// css style sheets
$this->headLink()->appendStylesheet($this->baseUrl().'/css/mobile.css');
// faveicon
$this->headLink(array('rel' => 'shortcut icon',
                      'href' => $this->baseUrl().'/favicon.ico'),
                      'PREPEND');
// feed of blog (rss & atom)
$this->headLink(array('rel' => 'alternate',
					  'type' => 'application/atom+xml',
					  'title' => 'cocktailberater.de Blog - Atom',
                      'href' => 'http://blog.cocktailberater.de/feeds/posts/default'));
$this->headLink(array('rel' => 'alternate',
					  'type' => 'application/rss+xml',
					  'title' => 'cocktailberater.de Blog - RSS',
                      'href' => 'http://blog.cocktailberater.de/feeds/posts/default?alt=rss'));
// e.g. for facebook sharing
$this->headLink(array('rel' => 'image_src',
					  'type' => 'image/jpeg',
                      'href' => 'http://www.cocktailberater.de/img/logo.png'));
// echo css, faveicon and feeds
echo $this->headLink()."\n";
?>
</head>
<body>
<div id="wrapper">
<div id="header" style="background-image: url('<?php print $this->baseUrl(); ?>/img/logo.mobile.png'); height: 50px;"><a
	href="<?php 
	print $this->url(array('module'=>'website',
							'controller'=>'index',
							'action'=>'index'),null,true); ?>?format=mobile"
	style="display: block; width: 100%; height: 50px;"><span class="hide">Startseite</span></a></div>
<!-- id:header -->
<div id="homepage">
<div id="content"><?php echo $this->layout()->content ?></div>
<!-- begin: top links -->
<h2 style="padding-top: 1em;">Social</h2>
<ul>
	<li style="clear: left;"><a href="http://www.facebook.com/cocktailberater"
		style="padding-top: 0.2em; padding-bottom: 0.2em;"
		title="auf facebook Fan werden"><span class="social_sprites"
		id="spr_facebook_fan"></span> Fan werden</a></li>
	<li style="clear: left;"><a style="padding-top: 0.2em; padding-bottom: 0.2em;"
		href="http://www.facebook.com/sharer.php?u=http://www.cocktailberater.de<?php echo $this->url(); ?>&amp;t=<?php echo urlencode($title); ?>"
		title="auf facebook teilen"> <span class="social_sprites"
		id="spr_facebook_share"></span> Teilen</a></li>
	<li style="clear: left;"><a
		href="http://twitter.com/home?status=<?php echo urlencode($title . ': http://www.cocktailberater.de' . $this->url()); ?>"
		title="auf Twitter posten"> <span class="social_sprites"
		id="spr_twitter"></span>Twitter(n)</a></li>
</ul>
<h2>Weitere Informationen</h2>
<ul>
	<li><a href="http://blog.cocktailberater.de" title="Entwickler Blog">Blog</a></li>
	<li><a
		href="<?php print $this->url(array(
							'module'=>'website',
							'controller'=>'portal',
							'action'=>'about'),'default',true); ?>?format=mobile">über cocktailberater</a></li>
	<li><a class="social_sprites_text"
		href="<?php print $this->url(array(
							'module'=>'website',
							'controller'=>'portal',
							'action'=>'imprint'),'default',true); ?>?format=mobile">impressum</a></li>
	<li><a class="social_sprites_text"
		href="<?php print $this->url(array(
							'module'=>'website',
							'controller'=>'portal',
							'action'=>'contact'),'default',true); ?>?format=mobile">kontakt</a></li>
</ul>
<p class="abstand_oben">[ <a href="?format=html">Desktop-Version</a> ]</p>
<!-- end: top links --></div>
<!-- id:homepage --></div>
<!-- id:wrapper -->
		<?php if(APPLICATION_ENV=='production') {?>
<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://stats.thobach.de/" : "http://stats.thobach.de/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 4);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script>
<noscript>
<p><img src="http://stats.thobach.de/piwik.php?idsite=4"
	style="border: 0" alt="" /></p>
</noscript>
<!-- End Piwik Tag -->
		<?php } ?>
</body>
</html>
