<?php
print $this->partial('template/search.mobile.phtml',$this);


// rename variables & fetch required data
/* @var $recipe Website_Model_Recipe */
$recipe = $this->recipe;
$photos = $recipe->getPhotos();
$videos = $recipe->getVideos();
$alternatives = $this->alternatives;
$components = $recipe->getComponents();
$gesamt = count($alternatives);
// ingredient list
foreach ( $components as /* @var $component Website_Model_Component */ $component ) {
	$ingredientList[] = $component->amount.' '.$component->unit.' '.$component->getIngredient()->name;
	$ingredientList2[] = $component->getIngredient()->name;
}
// setting meta keywords
$this->headMeta()->appendName('keywords', $recipe->name.', '.implode($ingredientList2,', ').', cocktail, rezept, cocktails, rezepte, cocktailrezepte, cocktailrezept, cocktailberater');
// setting meta description
$this->headMeta()->appendName('description', 'Das  Rezept des '.$recipe->name.' Cocktails besteht aus '.implode($ingredientList,', ').'. Mehr mit Beschreibung, Zubereitung, Fotos, Videos, Tags/Schlagworten, Kosten/Preisen, Kalorien und Kommentaren hier.');
// rdf
$this->headLink(array('rel' => 'alternate','type' => 'application/rdf+xml',
					  'title' => $recipe->name.' - RDF',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe','action'=>'get','id'=>$recipe->getUniqueName())).'?format=rdf'));
// atom
$this->headLink(array('rel' => 'alternate','type' => 'application/atom+xml',
					  'title' => $recipe->name.' - Atom',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe','action'=>'get','id'=>$recipe->getUniqueName())).'?format=atom'));
// rss
$this->headLink(array('rel' => 'alternate','type' => 'application/rss+xml',
					  'title' => $recipe->name.' - RSS',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe','action'=>'get','id'=>$recipe->getUniqueName())).'?format=rss'));
// json
$this->headLink(array('rel' => 'alternate','type' => 'application/json',
					  'title' => $recipe->name.' - JSON',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe','action'=>'get','id'=>$recipe->getUniqueName())).'?format=json'));
// xml
$this->headLink(array('rel' => 'alternate','type' => 'application/xml',
					  'title' => $recipe->name.' - XML',
                      'href' => $this->url(array('module'=>'website','controller'=>'recipe','action'=>'get','id'=>$recipe->getUniqueName())).'?format=xml'));
?>
<!-- class="right" -->
<div class="right clear">
	<img src="<?php
	if(isset($photos[0]) && $photos[0]->fileName) { 
		echo $this->baseUrl() .'/img/recipes/'. $photos[ 0 ]->fileName ;
	} else {
	 	echo $this->baseUrl().'/img/glasses/'.$recipe->getGlass()->getPhoto()->originalFileName;
	} 
	?>" id="recipe_image" alt="<?php print str_replace ( '\\', '', $recipe->name ) ; ?>"
	title="<?php print str_replace ( '\\', '', $recipe->name ) ; ?>"
	style="margin-right: 1.6em; width: 160px; margin-top: 0.2em; margin-bottom: 20px;" />
<!-- end of class="right" -->
</div>
<!-- end of class="right" -->
<div>
<div class="attribut">Name:</div>
<div class="wert"><?php
print str_replace ( '\\', '', $recipe->name ) ;
if($recipe->isOriginal){
	print  ' (original)';
}
if(!$recipe->isAlcoholic()){
	print  ' (alkoholfrei)';
}
?></div>
<?php if($recipe->description){?><div class="attribut">Beschreibung:</div>
<div class="wert"><p><?php
print str_replace("\n",'</p><p>',$recipe->description);
?></p></div><?php } ?>
<div class="attribut">Zutaten:</div>
<div class="wert"><p><strong>Cocktail</strong></p><ul><?php
$decorations = "";
$ingredients = "";
foreach ( $components as /* @var $component Website_Model_Component */ $component ) {
	$componentString = '<li>';
	$componentString .= ''.$component->amount.'';
	$componentString .= ' ' ;
	$componentString .= ''.$component->unit.'';
	$componentString .= ' ' ;
	
	
	
	$componentString .= '<a id="zutat'.$component->getIngredient()->id.'" '.
							'href="'.$this->url(array('module'=>'website',
							'controller'=>'ingredient',
							'id'=>$component->getIngredient()->getUniqueName()),
							null,true).'">'.
							$component->getIngredient()->name.'</a>';
	if($component->getPreferredProduct()){
		$componentString .= '<ul style="margin-left: 1.9em;"><li>empfohlen <a href="'.$this->url(array('module'=>'website',
							'controller'=>'product',
							'id'=>$component->getPreferredProduct()->getUniqueName()),
							null,true).'">'.$component->getPreferredProduct()->name.
							'</a> von <a href="'.$this->url(array('module'=>'website',
							'controller'=>'manufacturer',
							'id'=>$component->getPreferredProduct()->getManufacturer()->getUniqueName()),
							null,true).'">'.
							$component->getPreferredProduct()->getManufacturer()->name.'</a></li></ul>'; 
	} 
	$componentString .= '</li>';
	
	if($component->isDecoration){
		$decorations .= $componentString;
	} else {
		$ingredients .= $componentString;
	}
} // foreach

print $ingredients;

?></ul><?php 
if($decorations) { ?>
	<p class="abstand_oben"><strong>Dekoration</strong></p>
	<ul>
	<?php print $decorations; ?>
	</ul>
<?php 
} ?>
</div>
<div class="attribut">Zubereitung:</div>
<div class="wert"><p><?php
print str_replace("\n",'</p><p>',$recipe->instruction);
?></p></div>
<?php $this->headScript()->captureStart(); ?>
// sumbit the form 
var ratingFormSubmit = function(e){
    // prevent the form from actually submitting
    e.preventDefault(); 
    // submit the form in the background    
    dojo.xhrPost({
        url: "<?=$this->url(array('controller'=>'rating','action'=>'post','module'=>'website'),null,true)?>?format=json",
        form: "rating_form",
        handleAs: "json",
        handle: function(data,args){
            if (data.rsp["@attributes"].status == "ok"){
            	clearRatingFormError();
            	dojo.removeClass("rating_state");
            	dojo.addClass("rating_state","success");
            	dojo.byId("rating_state").innerHTML="Deine Bewertung wurde hinzugefügt.";
            }
            else if (data.rsp["@attributes"].status == "error"){
            	clearRatingFormError();
            	dojo.removeClass("rating_state");
            	dojo.addClass("rating_state","error");
            	dojo.byId("rating_state").innerHTML="Du hast schon abgestimmt!";
            }
            else {
                clearRatingFormError();
            	dojo.removeClass("rating_state");
            	dojo.addClass("rating_state","error");
            	dojo.byId("rating_state").innerHTML="Es ist ein Fehler aufgetreten. Bitte versuch es später nochmal.";
            }
        }
    });
};
dojo.addOnLoad(function(){
    var ratingForm = dojo.byId("rating_form");
    // another dojo.connect syntax: call a function directly    
    dojo.connect(ratingForm,"onsubmit",ratingFormSubmit);
});
function clearRatingFormError(){
	dojo.removeClass("rating_form")
	dojo.addClass("rating_form","hide")
}
<?php $this->headScript()->captureEnd(); ?>
<div class="attribut">Bewertung:</div>
<div class="wert"><?php $durchschnitt = $recipe->getRating(); ?>
	<div id="rating_state" class="hide">&nbsp;</div>
	<form id="rating_form" method="post" style="margin-top: 0.3em;"
	action="<?php print $this->url(array('module'=>'website','controller'=>'rating'),null,true); ?>">
	<fieldset>
		<?php for($rating = 1; $rating <= 5; $rating++){
		?><button type="submit" id="rating<?php echo $rating; ?>"
			onclick="document.getElementById('rating').value='<?php echo $rating; ?>';" 
			onmouseover="document.getElementById('img_rating<?php 
			echo $rating; ?>').src='<?php print $this->baseUrl() ; ?>/img/1_stars_pink.png';<?php 
				for($rating2=1; $rating2 <= $rating; $rating2++){ 
					echo "document.getElementById('img_rating$rating2').src='{$this->baseUrl()}/img/1_stars_pink.png';";
				}
			?>"
			onmouseout="document.getElementById('img_rating<?php 
			echo $rating; ?>').src='<?php print $this->baseUrl() ; ?>/img/<?php 
			echo ($durchschnitt >= $rating) ? '1_stars.png' : 'not_yet_rated_1.png' ; ?>';<?php 
				for($rating2=1; $rating2 <= $rating; $rating2++){ 
					if($durchschnitt >= $rating2){
						echo "document.getElementById('img_rating$rating2').src='{$this->baseUrl()}/img/1_stars.png';";
					} else {
						echo "document.getElementById('img_rating$rating2').src='{$this->baseUrl()}/img/not_yet_rated_1.png';";
					}
				}
			?>">
			<img id="img_rating<?php echo $rating; ?>" src="<?php print $this->baseUrl() ; ?>/img/<?php echo ($durchschnitt >= $rating) ? '1_stars.png' : 'not_yet_rated_1.png' ; ?>" height="18" width="18" alt="rate.." /></button><?php } ?>
		<input name="recipe" type="hidden" value="<?php echo $recipe->id; ?>" />
		<input name="rating" id="rating" type="hidden" value="" /> 
			<span style="vertical-align: top;">(<?php print ($recipe->ratingsCount==1 ? 
				$recipe->ratingsCount.' Stimme' : $recipe->ratingsCount.' Stimmen');
			print ' - Ø '.number_format ( $recipe->getRating(), 2, ',', '' ) ; ?>)</span>
	</fieldset>
	</form></div>
<?php if($recipe->source){ ?>
<div class="attribut">Rezeptquelle:</div>
<div class="wert"><?php print $recipe->source; ?></div>
<?php } ?>	
<!-- Tags -->
<div class="attribut">Schlagworte:</div>
<div class="wert"><ul id="tagList"><?php
$tags =  Website_Model_Tag::tagsByRecipeId($recipe->id,true);
foreach($tags as $tag){	?>
	<li class="left" style="clear: none; margin-right: 0.4em;"><a href="<?php print $this->url(array('controller'=>'recipe',
	'action'=>'index','index'=>'index','search_type'=>'tag',
	'search'=>$tag->getTitle())); ?>" rel="tag" 
	id="tag<?php print str_replace(array('-',' ','.'),array('_','__','___'),$tag->getTitle()); ?>"><?php print $tag->name; ?></a></li>
	<?php 
}
?><li class="left" style="clear: none;"><a name="tag_prev" id="tag_prev" onclick="insertTag();" href="#tags" style="margin-top: 1em; text-decoration: underline;">Schlagwort hinzufügen</a></li></ul>




<form id="tag_form" class="regular_form hide abstand_unten clear" method="post"
	action="<?php print $this->url(array('module'=>'website','controller'=>'tag'),null,true); ?>" style="padding-top: 1em;">
	<fieldset>
		<legend>Schlagwort hinzufügen</legend>
		<div id="tag_state" class="hide">&nbsp;</div>
		<label for="tagvalue" class="hide">Dein Schlagwort:</label>
		<!-- text input w/ autocompletion -->
		<input id="tagvalue" name="" type="text" />
		<input name="newtag" id="newtag" value="" type="hidden" />
		<input name="recipe" value="<?php print $recipe->id; ?>" type="hidden" />
		<input type="submit" class="small-button" value="hinzufügen"
			style="background-image: url('<?php echo $this->baseUrl(); ?>/img/general-button-small4.png'); font-size: 0.9em;" />
	</fieldset>
</form>
</div>

<div class="attribut"><a id="comments" class="nolink">Kommentare:</a></div>
<div class="wert">
	<ul id="commentList"><?php
	if (is_array ( $this->recipe->getComments() )) {
		$currentCommentNumber = 0;
		foreach ( $this->recipe->getComments() as $comment ) {
			$currentCommentNumber++;
			print '<li style="border-bottom: 1px solid rgb(170, 16, 97); margin-bottom: 0.5em;"'.
			($currentCommentNumber>3 ? ' class="hide"' : '').'><p><!-- #'.
				($amountOfComments--).' von --><em>' ;
			if ($comment->memberId) {
				$member = new Website_Model_Member ( $comment->memberId ) ;
				print '<a href="mailto:' . $this->escape($member->email) . '">' . $this->escape(stripslashes($member->firstname)) . ' ' . $this->escape(stripslashes($member->lastname)) . '</a>' ;
			} else if($comment->name){
				if($comment->name && $comment->email){
					print '<a href="mailto:' . $this->escape($comment->email) . '">' . $this->escape(stripslashes($comment->name)) . '</a>' ;
				} else {
					print $this->escape(stripslashes($comment->name));
				}
			} else {
				print 'anonym' ;
			}
			print '</em> schreibt: ';
			$insertDate = new Zend_Date($comment->insertDate,Zend_Date::ISO_8601);
			print ''.stripslashes(str_replace (array("\r\n", "\r", "\n",'\r\n', '\r', '\n'),
				'</p><p>',$this->escape($comment->comment))).
					' <span style="color: #888888">'.
					$insertDate->get(Zend_Date::DATETIME_SHORT,new Zend_Locale('de_DE')).
					' Uhr</span></p></li>' ;
		}
	} else {
		print '<li>keine Kommentare vorhanden</li>' ;
	}
	?></ul>
</div>
<?php if($gesamt) { ?>
	<div class="attribut">Rezeptalternativen:</div>
	<div class="wert">
	<ul class="nolist">
	<?php
	foreach ($alternatives as $alternative) { ?>
		<li><?php $this->cocktailPreview($alternative); ?></li>
	<?php } ?>
	</ul>
	</div>
	<?php } ?>
<div class="attribut" id="statistics">Statistiken:</div>
<div class="wert" style="width: 36em;"><p>
	Dieses Rezept wurde insgesamt <?php
	$totalViews = 0; 
	$htmlViews = 0;
	$printViews = 0;
	$feedViews = 0;
	$appViews = 0;
	foreach($recipe->getStatistics() as /* @var $statistic Website_Model_Statistic */ $statistic) {
		if($statistic->format == Website_Model_Statistic::FORMAT_HTML ||
			$statistic->format == Website_Model_Statistic::FORMAT_MOBILE){
			$htmlViews += $statistic->views;
		} else if($statistic->format == Website_Model_Statistic::FORMAT_RSS || 
			$statistic->format == Website_Model_Statistic::FORMAT_ATOM){
			$feedViews += $statistic->views;
		} else if($statistic->format == Website_Model_Statistic::FORMAT_PDF) {
			$printViews += $statistic->views;
		} else {
			$appViews += $statistic->views;
		} 
		$totalViews += $statistic->views;
	}
	print $totalViews; ?> mal angeschaut.</p>
</div><!-- END of class=wert -->
</div><!-- END of class=left -->
<ul>
<li class="left icon"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/zeit.png" alt="Zeitaufwand"
	title="Zeitaufwand" height="42" width="43" /><?php
	print $recipe->workMin;
	?> min</li>
<li class="left icon"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/<?php
	if ($recipe->difficulty == Website_Model_Recipe::BEGINNER) {
		print "difficulty/beginner.png" ;
		$difficultyMessage = 'Anfänger';
	}
	else if ($recipe->difficulty == Website_Model_Recipe::ADVANCED) {
		print "difficulty/advanced.png" ;
		$difficultyMessage = 'Fortgeschritten';
	}
	else if ($recipe->difficulty == Website_Model_Recipe::PROFI) {
		print "difficulty/professional.png" ;
		$difficultyMessage = 'Profi';
	} else {
		// TODO: Bild erstellen, welches ausdrückt, dass es keine Information dazu gibt...
		print "difficulty/unknown.png" ;
		$difficultyMessage = 'nicht eingestuft';
	}
	?>" 
	alt="Schwierigkeitsgrad <?php
	print $difficultyMessage;
	?>"
	title="Schwierigkeitsgrad <?php
	print $difficultyMessage;
	?>" /><?php
	print $difficultyMessage
	;
	?></li>
<li class="left icon"><img
	src="<?php
	echo $this->baseUrl() .'/img/glasses/'. $recipe->getGlass()->getPhoto()->fileName ;
	?>"
	alt="Glas <?php
	print $recipe->getGlass()->name ;
	?>"
	title="Glas <?php
	print $recipe->getGlass()->name ;
	?>" /><?php
	print $recipe->getGlass()->name ;
	?></li>
	
<li class="left icon" id="caloriesInfo"><img
	src="<?php
	print $this->baseUrl() ;
	?>/img/calories.png" alt="Kalorien" height="48" width="33"
	title="Kalorien" />
	<span style="text-decoration: underline; text-underline-style: dotted; cursor: pointer; color: rgb(84, 97, 110);"><?php
	if(!$caloriesComplete){
		print 'über ';
	} ?><span style="white-space: nowrap"><?php print $recipe->getCaloriesKcal(); ?> kcal</span></span></li>
<li class="left icon" ><img  height="42" width="34"
	src="<?php
	print $this->baseUrl() ;
	?>/img/prozent.png" alt="Alkoholgehalt"
	title="Alkoholgehalt" /><?php
	print round($recipe->getAlcoholLevel());
	?> % Alkohol</li>
	
<li class="left icon" id="priceInfo"><img  height="42" width="34"
	src="<?php
	print $this->baseUrl() ;
	?>/img/icons/money.png" alt="Preis / Kosten"
	title="Preis / Kosten" />
	<span style="text-decoration: underline; text-underline-style: dotted; cursor: pointer; color: rgb(84, 97, 110);">
	<?php
	if(!$priceComplete){
		print 'über ';
	}
	print number_format($recipe->getAveragePrice(),2,',','.');
	?> €</span></li>
<li class="left icon" ><img  height="47" width="25"
	src="<?php
	print $this->baseUrl() ;
	?>/img/volumen.png" alt="Volumen"
	title="Volumen" /><?php
	print $recipe->getVolumeCl() ;
	?> cl</li>
</ul>
