<?php
foreach ($this->recipes as $recipe){
	$components = '';
	foreach ($recipe->getComponents() as $component){
		$components .= "<li>".$component->amount.' '.$component->unit.' '.
			$component->getIngredient()->name."</li>";
	}
	$date = new Zend_Date($recipe->updateDate,Zend_Date::ISO_8601);
	$entries[] = array(
		'title'			=> $recipe->name,
		'lastUpdate'	=> $date->getTimestamp(),
		'link'			=> $this->url(array('id'=>$recipe->getUniqueName())),
		'content'		=> 	"<p><strong>Beschreibung:</strong></p>".
							"<p>".$recipe->description."</p>".
							"<p><strong>Zutaten:</strong></p>".
							"<ul>".$components."</ul>".
							"<p><strong>Anweisung:</strong></p>".
							"<p>".$recipe->instruction."</p>",
		'description'	=> "".$recipe->description,
	);

}

// Create the RSS array
$rss = array(
	'title'			=>	'Liste aller Cocktailrezepte',
	'description'	=>	'Alle Cocktailrezepte des cocktailberaters.',
	'link'    		=> 	'http://www.cocktailberater.de',
	'charset'		=> 	'UTF-8',
	'entries' 		=> 	$entries
);

// Import the array
$feed = Zend_Feed::importArray($rss, $this->format);
print $feed->saveXML();