<p class="left" style="margin: 1em 0 1em 0; font-size: 0.9em;"><a
	href="/?format=mobile">Start</a> &gt; Rezepte</p>
<?php echo $this->partial ('template/search.mobile.phtml');
if ($this->recipes) { ?>
<h2
	style="margin-bottom: 1.5em; margin-top: 0; maring-left: 2em; margin-right: 2em;"><?php 
	if(!$this->title) { ?>Cocktailrezepte<?php }
	else { echo $this->title; } ?></h2>
<div id="ergebnisse" style="clear: left;"><?php
foreach ($this->recipes as $recipe){
	if($this->top10){
		echo $this->cocktailPreview ($recipe,++$i);
	} else {
		echo $this->cocktailPreview ($recipe);
	}
}
?></div>
<!-- div: ergebnisse -->
<?php } else { ?>
<p>Bitte geben Sie einen Suchbegriff ein.</p>
<?php } ?>
<?php
$urlParams = Zend_Controller_Front::getInstance()->getParams();
$urlParams['index'] = 'index';
unset($urlParams['bootstrap']);
unset($urlParams['search_type_value']);
unset($urlParams['disableOutputBuffering']);
?>