<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

// set status for root element 'rsp' to 'ok'
if($this->auth){
	$this->rsp->setAttribute('status','ok');
} else {
	$this->rsp->setAttribute('status','error');
	$this->rsp->setAttribute('msg','Invalid credentials.');
}

// save and display tree
print $this->xml->saveXML();
