<?php
foreach ($this->partys as $party){
	$entries[] = array(
		'title'       => $party->name,
		'link'        => $this->url(array(
			'id'		=>$party->id,
			'format'	=>$this->format)),
		'description' => $party->name,
	);

}

// Create the RSS array
$rss = array(
	'title'   => 'cocktailberater',
	'link'    => 'http://www.cocktailberater.de',
	'charset' => 'UTF-8',
	'entries' => $entries
);

// Import the array
$feed = Zend_Feed::importArray($rss, $this->format);
print $feed->saveXML();