<div class="content">
<h2>Hersteller und Marken von Cocktailzutaten</h2>
<p>Die folgende Tabelle listet alle im cocktailberater verzeichneten Hersteller von Cocktailzutaten auf. Zu jedem Hersteller ist angegeben wie viele Produkte in unserer Datenbank hinterlegt sind und wie viele Rezepte sich damit mixen lassen.</p>
<table class="table">
	<thead>
		<tr>
			<th>Hersteller/Marke</th>
			<th>Webseite</th>
			<th>Produkte</th>
			<th>Rezepte</th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->manufacturers as $manufacturer){
	print '<tr>';
	$products = $manufacturer->getProducts();
	$recipes = $manufacturer->getRecipes();
	print '<td><a href="'.$this->url(
	array('id'=>$manufacturer->getUniqueName(),'controller'=>'manufacturer','action'=>'get','module'=>'website'),'manufacturer',true).'">'.
	$manufacturer->name.'</a></td>';
	print '<td>'.($manufacturer->website ? '<a href="'.$manufacturer->website.'" style="text-overflow: ellipsis;">Link</a>' : '');
	print '</td>';
	print '<td>'.($products!==false ? '<a href="'.$this->url(
		array('id'=>$manufacturer->getUniqueName(),'controller'=>'manufacturer','action'=>'get','module'=>'website'),'manufacturer',true).'#products-list">'.count($products).' Stk.</a>' : 'keine').'</td>';
	print '<td>'.(count($recipes)>0 ? '<a href="'.$this->url(
		array('id'=>$manufacturer->getUniqueName(),'controller'=>'manufacturer','action'=>'get','module'=>'website'),'manufacturer',true).'#recipes-list">'.count($recipes).' Stk.</a>' : 'keine').'</td>';
	print '</tr>';
}
?>
	</tbody>
</table>
</div>
