<?php echo $this->partial ("template/search.phtml"); ?>
<h1>Cocktails mit Rezeptalternativen</h1>
<p>Hier finden Sie Cocktails mit verschiedenen Rezepten und Angaben zu durchschnittlichen Kalorien und Kosten/Preisen.</p>
<ul style="margin-top: 1em; margin-left: 1em;">
<?php
$i=0;
foreach ($this->cocktails as $cocktail){
	$i++;
	print '<li style="width: 20em; float: left; margin-bottom: 1em; margin-left: 1em; margin-right: 1em; '.( ($i == 1) ? 'clear: left;' : 'clear: none;' ).'">'.
	'<a href="'.$this->url(array('module'=>'website','controller'=>'cocktail','action'=>'get','id'=>$cocktail->getUniqueName())).'">'.$cocktail->name.'</a><br />';
	$recipes = $cocktail->getRecipes();
	if(is_array($recipes)) { 
		print '<ul style="font-size: 0.9em; list-style-type: circle; list-style-type: none;">';
		foreach ($recipes as $recipe) {
			$avgPrice = $recipe->getAveragePrice();
			$calories = $recipe->getCaloriesKcal();
			$photos = $recipe->getPhotos();
			print '<li style="margin-bottom: 1em;">';
			print '<a href="'.$this->url().'/'.$recipe->getUniqueName().'">'.
			'<img style="height: 100px;" src="'.$this->baseUrl();
			if(isset($photos[0]) && $photos[0]->id){
				print '/img/recipes/'.$this->escape($photos[0]->fileName);
			} else { 
				print '/img/glasses/'.$recipe->getGlass()->getPhoto()->originalFileName;
			}
			print '" /></a>';
			print '<br /><a href="'.$this->url(array('module'=>'website','controller'=>'recipe','action'=>'get','id'=>$recipe->getUniqueName())).'">'.$recipe->name.'</a> '.
			($avgPrice ? ' <br />Durchschnittspreis / Kosten: '.number_format($avgPrice,2,',','.').'&nbsp;€ ' : '').
			($calories ? ' <br />Durchschnittskalorien: '.number_format($calories,0,',','.').'&nbsp;kcal ' : '');
			print '</li>';
		}
		print '</ul>';
	}
	print '</li>';
}
?>
</ul>
