<?php print $this->partial('template/portal_nav.phtml'); ?>
<div class="content">
<h2>Barkunde - Gläser</h2>
<h3>Glaskategorien</h3>
<ul class="horizontal glas">
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/highball.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/collins.png"
		alt="Longdrinkglas" />Longdrinkglas<br />
	ca. 25 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/red_wine.png"
		alt="Longdrinkglas" />Stielglas<br />
	</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/hurricane.png"
		alt="Longdrinkglas" />Fancyglas<br />
	30-50 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/cocktail.png"
		alt="Longdrinkglas" />Cocktailglas / -schale<br />
	6-10 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/old_fashioned.png"
		alt="Longdrinkglas" />Tumbler<br />
	20 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/irish_coffee_cup.png"
		alt="Longdrinkglas" />Glas für Heißgetränke<br />
	ca. 20 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/red_wine.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/white_wine.png"
		alt="Longdrinkglas" />kleines / großes Weinglas<br />
	</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/brandy_sniffer.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_5.png"
		alt="Longdrinkglas" />Schwenker<br />
	4 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_3.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/champagne_flute.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_7.png"
		alt="Longdrinkglas" />Sektkelch<br />
	10-20 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/unbekannt.png"
		alt="Longdrinkglas" />Schnapsglas<br />
	2-4 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/margarita.png"
		alt="Longdrinkglas" />Margaritaglas<br />
	ca. 25 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/sherry_glass.png"
		alt="Longdrinkglas" />Sherryglas<br />
	5 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_1.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_2.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_4.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_6.png"
		alt="Longdrinkglas" />nicht zugeordnet<br />
	</p>
	</li>
</ul>
<div class="clear"></div>
<h3 class="clear abstand_oben_doppelt">Gläserkunde</h3>
<ul>
	<li><strong>Dünne Gläser</strong> sehen zwar schick aus, zerbrechen aber schnell beim
	Abspülen oder Hinunterfallen.</li>
	<li>Besser sind Gläser mit dickem Rand und geringem <strong>Platzbedarf</strong>. Somit
	halten sie lange und nehmen auch noch wenig Platz weg.</li>
	<li>Die angegebenen Volumen entsprechen der typischen <strong>Füllmenge</strong>, nicht
	dem maximalen Fassungsvermögen.</li>
</ul>
</div>
