<h3>HausBar</h3>
<p>Cocktailparties benötigen ein wenig Organisation. Hier hilft die
virtuelle HausBar zum Verwalten von Rezepten, Vorräten und Favoriten.</p>
<ul>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'login')); ?>">Login / Anmeldung</a>
	zum Registrieren einer virtuellen HausBar.</li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>">Meine HausBar</a>
	verwalten.</li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-favoriten')); ?>">Meine Favoriten</a>
	verwalten.</li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-cocktails')); ?>">Meine Cocktails</a>
	verwalten.</li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch')); ?>">Cocktailbuch erstellen</a>
	aus meinen Cocktailrezepten meiner HausBar.</li>
</ul>
