<div class="sub_nav">
<ul class="textLeft">
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'community'),null,true); ?>">Community</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'cocktail-der-woche'),null,true); ?>">Cocktail der Woche</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'top10-drinks'),null,true); ?>">Top 10 Drinks</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'forum'),null,true); ?>">Forum</a></li>
	</ul></li>
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'hausbar'),null,true); ?>">HausBar</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'login'),null,true); ?>">Anmelden / Login</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar'),null,true); ?>">Meine HausBar</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-favoriten'),null,true); ?>">Meine Favoriten</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-cocktails'),null,true); ?>">Meine Cocktails</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch'),null,true); ?>">Cocktailbuch erstellen</a></li>
	</ul></li>
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'barkunde'),null,true); ?>">BarKunde</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'nutrition'),null,true); ?>">Nährwerte</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'glas'),null,true); ?>">Gläser</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'utensilien'),null,true); ?>">Utensilien</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'mixtechniken'),null,true); ?>">Mixtechniken</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'grundausstattung'),null,true); ?>">Grundausstattung</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'zutaten'),null,true); ?>">Zutaten (Beschreibung)</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'buecher'),null,true); ?>">empfehlenswerte Bücher</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'andere-seiten'),null,true); ?>">andere Cocktailseiten</a></li>
	</ul></li>
</ul>
</div>
