<?php
$isiPad = (bool) strpos($_SERVER['HTTP_USER_AGENT'],'iPad');
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
// HTML 5 header
echo $this->doctype('HTML5')."\n";
?>
<html lang="de-DE">
<head>
<meta charset=utf-8>
<?php if($isiPad){ ?>
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="viewport"
	content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=no" />
<?php } ?>
<title>Barclient - cocktailberater</title>
<style>
@import url(/css/barclient.css);
@font-face {
  font-family: 'cbfont';
  <?php if($isiPad){ ?>
  src: url('http://cocktailberater.local:10088/fonts/teenlite.svg#MySVGFont') format(svg);
  <?php } else { ?>
  src: url('http://cocktailberater.local:10088/fonts/teenlite.ttf');
  <?php } ?>
}

#wrapper {
	<?php if(!$isiPad){ ?>
	position:relative;
	top: 50%;
	margin-top: -345px;
	<?php } ?>
}
</style>
</head>
<body>
<div id="wrapper">
<h1><span class="pink">c</span>ocktail<span class="pink">b</span>erater</h1>
<div id="head_info">Du bist eingeloggt als Thomas Bachmann, <a href="<?php print $this->url(array('controller'=>'index','action'=>'logout')); ?>">ausloggen</a>. Bar: <select><option>Tabas Bar</option></select></div>
<ul class="navigation">
	<li style="width: 6.5em; margin-top: 4em; margin-left: -2.7em;"
		<?php if($controller=='orders') { ?> class="active"<?php } ?>><a 
		href="/barclient/orders">Bestellungen</a></li>
	<li style="width: 6em; margin-top: 11.5em; margin-left: -6.4em;"
		<?php if($controller=='cash') { ?> class="active"<?php } ?>><a
		href="/barclient/cash">Abrechnung</a></li>
	<li style="width: 4.5em; margin-top: 18em; margin-left: -5.65em;"
		<?php if($controller=='inventory') { ?> class="active"<?php } ?>><a
		href="/barclient/inventory">Inventar</a></li>
	<li style="width: 3.5em; margin-top: 23.25em; margin-left: -5.15em;"
		<?php if($controller=='menu') { ?> class="active"<?php } ?>><a
		href="/barclient/menu">Karte</a></li>
	<li style="width: 4.5em; margin-top: 28.5em; margin-left: -5.65em;"
		<?php if($controller=='statistic') { ?> class="active"<?php } ?>><a
		href="/barclient/statistic">Statistik</a></li>
	<li style="width: 4em; margin-top: 34em; margin-left: -5.4em;"><a
		<?php if($controller=='party') { ?> class="active"<?php } ?>href="/barclient/party">Partys</a></li>
</ul>
<div id="content"><?php echo $this->layout()->content; ?></div>
</div>
</body>
</html>
