<?php
// create a dom object
$this->xml = new DOMDocument("1.0");
// create root element 'rsp'
$this->rsp = $this->xml->createElement("rsp");
// add the 'rsp' element to the xml document
$this->xml->appendChild($this->rsp);

$barsXML = $this->xml->createElement('bars');
if(is_array($this->bars)){
	foreach ($this->bars as $bar){
		$bar->toXml($this->xml,$barsXML);
	}
}
// set count for recipe element according to number of recipes found
$barsXML->setAttribute('count',count($this->bars));
// add the '$recipes' element to the 'rsp' element
$this->rsp->appendChild($barsXML);
// set status for root element 'rsp' to 'ok'
$this->rsp->setAttribute('status','ok');

// save and display tree
print $this->xml->saveXML();
