<h2>Das Projekt „cocktailberater“</h2>
<div>
<h3 class="attribut">Idee</h3>
<p class="wert" style="">Der cocktailberater ist ein
studentisches Projekt und soll das Hobby Cocktails u.a. mit der
Programmierung verbinden. Es soll die Möglichkeit bestehen möglichst
viel Theoriewissen hier auszuprobieren und anzuwenden.</p>
<h3 class="attribut">Aktuelles Team</h3>
<ul class="wert" style="">
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;"><a
		href="http://www.thobach.de">thomas bachmann (entwickler)</a></li>
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;"><a
		href="http://www.carolinebock.de">caroline bock (designer)</a></li>
</ul>
<h3 class="attribut">Vision</h3>
<p class="wert" style="">Der cocktailberater soll ein
internationaler, virtueller Treffpunkt für alle Cocktailfreunde werden.
Dabei wünschen wir uns möglichst viele Menschen für das Thema Cocktails
zu begeistern.</p>
<h3 class="attribut">Mission</h3>
<p class="wert" style="">Monatlich über 1.000 Besucher auf
unsere Seiten locken.</p>
<h3 class="attribut">Strategie</h3>
<ul class="wert" style="">
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;">Wir wollen eine
	sehr gute <strong>Rezeptqualität</strong> bieten. Dazu gehören neben
	den Zutaten und der Zubereitung auch zusätzlichen Angaben wie die
	Geschichte des Cocktails, Kalorien, Kosten und erstklassige Fotos und
	Videos.</li>
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;">Wir wollen
	unsere Besucher möglichst lange auf unseren Seiten halten, indem wir
	viele <strong>nützliche Informationen</strong> rund um die
	dargestellten Cocktailrezepte bieten. Dazu gehören Zutaten-, Produkt-
	und Herstellerinformationen sowie eine ausgezeichnete Sammlung an
	Barwissen.</li>
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;">Wir wollen
	unseren Cocktailfreunden eine ansprechende, übersichtliche und <strong>freundliche
	Darstellung</strong> aller Inhalte bieten.</li>
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;">Wir wollen
	möglichst viele Informationen mit <strong>Quellen</strong> hinterlegen
	um eine hohe Datenqualität zu gewährleisten.</li>
	<li style="margin-left: 2em; list-style-type: circle; font-size: 1em;">Wir wollen mit <strong>offenen
	Schnittstellen</strong> jedem ermöglichen unsere gesammelten Daten auch
	elektronisch weiterzuverarbeiten und für sich zu nutzen.</li>
</ul>
</div>
