<h2>Das Projekt „cocktailberater“</h2>
<div id="spacing-left">
<h3 class="attribut">Idee</h3>
<p class="wert" style="width: 36em;">
Der cocktailberater ist ein studentisches Projekt und soll das Hobby
Cocktails u.a. mit der Programmierung verbinden. Es soll die Möglichkeit
bestehen möglichst viel Theoriewissen hier auszuprobieren und
anzuwenden.</p>
<h3 class="attribut">Aktuelles Team</h3>
<div class="wert" style="width: 36em;">
<ul>
	<li style="margin-left: 2em; list-style-type: circle;"><a
		href="http://www.thobach.de">thomas bachmann (entwickler)</a></li>
	<li style="margin-left: 2em; list-style-type: circle;"><a
		href="http://www.carolinebock.de">caroline bock (designer)</a></li>
</ul>
</div>
<div class="attribut">Vision</div>
<div class="wert" style="width: 36em;">
<p>Der cocktailberater soll ein internationaler, virtueller Treffpunkt
für alle Cocktailfreunde werden. Dabei wünschen wir uns möglichst viele
Menschen für das Thema Cocktails zu begeistern.</p>
</div>
<div class="attribut">Mission</div>
<div class="wert" style="width: 36em;">
<p>Monatlich über 1.000 Besucher auf unsere Seiten locken.</p>
</div>
<div class="attribut">Strategie</div>
<div class="wert" style="width: 36em;">
<ul>
	<li style="margin-left: 2em; list-style-type: circle;">Wir wollen eine
	sehr gute <strong>Rezeptqualität</strong> bieten. Dazu gehören neben
	den Zutaten und der Zubereitung auch zusätzlichen Angaben wie die
	Geschichte des Cocktails, Kalorien, Kosten und erstklassige Fotos und
	Videos.</li>
	<li style="margin-left: 2em; list-style-type: circle;">Wir wollen
	unsere Besucher möglichst lange auf unseren Seiten halten, indem wir
	viele <strong>nützliche Informationen</strong> rund um die
	dargestellten Cocktailrezepte bieten. Dazu gehören Zutaten-, Produkt-
	und Herstellerinformationen sowie eine ausgezeichnete Sammlung an
	Barwissen.</li>
	<li style="margin-left: 2em; list-style-type: circle;">Wir wollen
	unseren Cocktailfreunden eine ansprechende, übersichtliche und <strong>freundliche
	Darstellung</strong> aller Inhalte bieten.</li>
	<li style="margin-left: 2em; list-style-type: circle;">Wir wollen
	möglichst viele Informationen mit <strong>Quellen</strong> hinterlegen
	um eine hohe Datenqualität zu gewährleisten.</li>
	<li style="margin-left: 2em; list-style-type: circle;">Wir wollen mit <strong>offenen
	Schnittstellen</strong> jedem ermöglichen unsere gesammelten Daten auch
	elektronisch weiterzuverarbeiten und für sich zu nutzen.</li>
</ul>
</div>
<div class="attribut">Ursprüngliches Visions-dokument</div>
<div class="wert" style="width: 36em;">
<div style="width: 425px" id="__ss_349523"><strong
	style="display: block; margin: 12px 0 4px"><a
	href="http://www.slideshare.net/thobach/vorstellung-cocktailberaterde"
	title="Vorstellung cocktailberater.de">Vorstellung cocktailberater.de</a></strong><object
	id="__sse349523" width="425" height="355">
	<param name="movie"
		value="http://static.slidesharecdn.com/swf/ssplayer2.swf?doc=vorstellung-cocktailberaterde-20080322-v1-1208015305973774-9&stripped_title=vorstellung-cocktailberaterde" />
	<param name="allowFullScreen" value="true" />
	<param name="allowScriptAccess" value="always" />
	<embed name="__sse349523"
		src="http://static.slidesharecdn.com/swf/ssplayer2.swf?doc=vorstellung-cocktailberaterde-20080322-v1-1208015305973774-9&stripped_title=vorstellung-cocktailberaterde"
		type="application/x-shockwave-flash" allowscriptaccess="always"
		allowfullscreen="true" width="425" height="355"></embed></object>
<div style="padding: 5px 0 12px">View more <a
	href="http://www.slideshare.net/">presentations</a> from <a
	href="http://www.slideshare.net/thobach">Thomas Bachmann</a>.</div>
</div>
</div>
</div>
