<?php if($this->format=='html') { print $this->partial('template/portal_nav.phtml'); } ?>
<div class="content">
<p class="breadcrumb">
<?php if($this->format=='html') { ?>Sie sind hier: <?php } ?><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Barkunde',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'barkunde',
		            	'pages'      => array(
				            array(
				                'label'      => 'Original Cocktailrezepte',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'authors'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($this->format=='html') {
	echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
} else {
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
}
if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>
<h2>Original Cocktailrezepte</h2>
<h3>Cocktailrezept-Autoren</h3>
<?php
$options = array(	'controller'=>'recipe',
					'action'=>'index',
					'search_type'=>'author',
					'search'=>'*');
?>
<ul>
	<li><a
		href="<?php 
		$options['search'] = urlencode('Schumann'); 
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Charles Schumann</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['schumann'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
	<li><a
		href="<?php
		$options['search'] = urlencode('Brandl');
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Franz Brandl</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['brandl'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
	<li><a
		href="<?php
		$options['search'] = urlencode('Beach');
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Donn Beach</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['beach'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
	<li><a
		href="<?php
		$options['search'] = urlencode('Trader Vic');
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Trader Vic</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['trader_vic'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
</ul>
<h3>Cocktailbücher und andere Quellen</h3>
<ul>
<?php
$options['search_type'] = 'source';
foreach($this->sources as $source) { ?>
	<li><a
		href="<?php
		$options['search'] = urlencode($source);
		print $this->url($options); ?>?format=<?php print $this->format; ?>"><?php print $source; ?></a></li>
		<?php } ?>
</ul>
</div>
