<div class="content">
<h2>Original Cocktailrezepte</h2>
<p>Oft ist ein Cocktailrezept keinem Autor mehr zuordenbar.
cocktailberater versucht nur Rezepte zu veröffentlichen, von denen der
<a href="#autor">Autor</a> bekannt ist. Daher sind die meisten dargestellten Rezepte aus <a href="#quellen">Cocktailbüchern</a> übernommen.</p>
<h3 class="pink" id="autor">Cocktailrezepte nach Autor</h3>
<?php
$options = array(	'controller'=>'recipe',
					'action'=>'index',
					'search_type'=>'author',
					'search'=>'*');
?>
<ul>
	<li><a
		href="<?php 
		$options['search'] = urlencode('Schumann'); 
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Charles
	Schumann</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['schumann'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
	<li><a
		href="<?php
		$options['search'] = urlencode('Brandl');
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Franz
	Brandl</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['brandl'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
	<li><a
		href="<?php
		$options['search'] = urlencode('Beach');
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Donn
	Beach</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['beach'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
	<li><a
		href="<?php
		$options['search'] = urlencode('Trader Vic');
		print $this->url($options); ?>?format=<?php print $this->format; ?>">Trader
	Vic</a>:
	<div style="margin-top: 1em;"><?php foreach($this->recipes['trader_vic'] as $recipe){ 
		print $this->cocktailPreview($recipe);
	} ?></div>
	</li>
</ul>
<h3 class="pink" id="quellen">Cocktailrezepte nach Cocktailbuch oder anderer Quelle</h3>
<ul>
<?php
$options['search_type'] = 'source';
foreach($this->sources as $source) { ?>
	<li><a
		href="<?php
		$options['search'] = urlencode($source);
		print $this->url($options); ?>?format=<?php print $this->format; ?>"><?php print $source; ?></a></li>
		<?php } ?>
</ul>
</div>
