<div class="content">
<h2>Cocktailbücher</h2>
<p>Dies ist eine kleine Auswahl an wirklich empfehlenswerten
Cocktailbüchern mit Rezepten und Barwissen.</p>
<ul>
	<li><strong>American Bar</strong> von <em>Charles Schumann</em>, auch
	bekannt als die Bar-Bibel, ist 2006 in der 18. Auflage erschienen. Der
	Autor Charles Schumann gehört zu den bedeutendsten deutschen
	Cocktailexperten und besitzt in München die bekannte Bar <em>Schumann's</em>.
	In seinem Buch listet er hunderte Rezepte, sowohl eigene Kreationen und
	Varianten bekannter Rezepte als auch Originalrezepte. Neben Rezepten
	findet man hier auch eine umfangreiche Warenkunde und Hinweise für den
	Aufbau einer eigenen Bar. 2010 soll der Nachfolger <strong>Bar</strong>
	erscheinen, welcher eine völlige Überarbeitung der Bar-Bibel ist.</li>
	<li><strong>Cocktails</strong> von <em>Franz Brandl</em> ist 2007 in
	der 1. Auflage erschienen. Auch Brandl gehört neben Schuman zu den
	bedeutendsten Cocktailexperten. Sein Buch Cocktails ist mit vielen
	Fotos versehen und bietet ebenso neben hunderten Cocktails eine
	Warenkunde und eine Menge an Barwissen.</li>
</ul>
<p>Viele günstige Cocktailbücher (5-10 €) bieten eine gute Auswahl an
Cocktailrezepten und eine Einführung zum Mixen, allerdings fehlt hier
meist die Warenkunde und umfangreiches Barwissen. Die Gestaltung und
Illustrationen sind dafür meist sehr ansprechend.</p>
</div>
