<?php print $this->partial('template/portal_nav.phtml'); ?>
<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Community',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'community'
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo $this->navigation($container)->breadcrumbs();
?></p>
<h2 style="margin-bottom: 0;">Community</h2>
<?php print $this->partial('template/community.phtml'); ?>
<h3 style="margin-bottom: 0.5em;">Neuste Aktivitäten</h3>
<fb:activity site="cocktailberater.de" width="410" header="false" recommendations="false"></fb:activity>
</div>

<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '111381035582024', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/de_DE/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
