<?php
/**
 * Kontakt view
 *
 * @author  Thomas Bachmann
 * @version 1.0
 */
?>
<div class="content">
<h2>Kontaktieren Sie uns!</h2>
<p>Mit diesem Formular können Sie schnell und einfach mit uns in Kontakt
treten. Wir freuen uns auf Ihre Nachricht!</p>
<?php if($this->form->isErrors()){ ?>
<div class="error"><?php echo $this->translate('Fehler aufgetreten!'); ?></div>
<?php } ?>
<?php echo $this->form; ?>
<p class="clear">(*) <?php echo $this->translate('Pflichtfeld'); ?></p>
</div>