<div class="content">
<h2>Fehler gefunden?</h2>
<h3 class="pink">Bitte melden!</h3>
<p>Wenn du einen Fehler auf unserer Seite gefunden hast, tut uns das
Leid. Wir bitten dich uns den Fehler über das <a href="<?php print $this->url(array('action'=>'contact')); ?>">Kontaktformular</a> oder
unseren <a href="http://code.google.com/p/cocktailberater/issues/entry">Bug-Tracker mitzuteilen</a>. Danke!</p>
</div>
