<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Barkunde',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'barkunde',
		            	'pages'      => array(
				            array(
				                'label'      => 'Gläser',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'glas'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<h2>Gläser</h2>
<h3>Glaskategorien</h3>
<ul style="list-style-position: outside; margin-left: 1.5em;">
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/longdrink.png"
		alt="Longdrinkglas" />Longdrink, ca. 25cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/highball.png"
		alt="Highball" />Highball</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/collins.png"
		alt="Collins" />Collins</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/hurricane.png"
		alt="Fancyglas" />Fancyglas, 30-50 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/cocktail.png"
		alt="Cocktailglas" />Cocktailglas / -schale, 6-10 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/tumbler_klein.png"
		alt="Tumbler" />Tumbler klein, 20 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/tumbler_gross.png"
		alt="Tumbler" />Tumbler groß</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/irish_coffee_cup.png"
		alt="Heißgetränke" />Glas für Heißgetränke, ca. 20 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/wine.png"
		alt="Weinglas" />Stielglas</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/brandy_sniffer.png"
		alt="Schwenker" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_5.png"
		alt="Schwenker" />Schwenker, 4 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/sekt.png"
		alt="Sektkelch" />Sektkelch, 10-20 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/champagnerfloete.png"
		alt="Champagnerflöte" />Champagnerflöte</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/shooter.png"
		alt="Schnapsglas" />Schnapsglas, 2-4 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/margarita.png"
		alt="Margaritaglas" />Margaritaglas, ca. 25 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/sherry_glass.png"
		alt="Sherryglas, 5 cl" />Sherryglas, 5 cl</p>
	</li>
</ul>
<div class="clear"></div>
<h3 class="clear abstand_oben_doppelt">Gläserkunde</h3>
<ul style="list-style-position: outside; margin-left: 1.5em;">
	<li><strong>Dünne Gläser</strong> sehen zwar schick aus, zerbrechen aber schnell beim
	Abspülen oder Hinunterfallen.</li>
	<li>Besser sind Gläser mit dickem Rand und geringem <strong>Platzbedarf</strong>. Somit
	halten sie lange und nehmen auch noch wenig Platz weg.</li>
	<li>Die angegebenen Volumen entsprechen der typischen <strong>Füllmenge</strong>, nicht
	dem maximalen Fassungsvermögen.</li>
</ul>
</div>
