<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Party Helferlein',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'hausbar'
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<h2>Party Helferlein</h2>
<p>Cocktailpartys benötigen ein wenig Organisation. Hier hilft die
virtuelle Hausbar zum Verwalten von Vorräten und Rezepten.</p>
<ul class="noBullet" style="margin-left: 0;">
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=mobile"><img
		src="/img/portal/hausbar.jpg"
		alt="Mechanismus der Hausbar, erst Zutaten auswählen, dann Rezepte angezeigt bekommen"
		class="left abstand_rechts box" style="margin-top: 0.3em;" /></a><br />
	Vorhandene Zutaten in der virtuellen <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=mobile">Hausbar</a>
	angeben und herausfinden welche Rezepte du damit mixen kannst.</li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch')); ?>?format=mobile"><img
		src="/img/portal/karte.jpg" alt="3 Seiten einer Cocktailkarte"
		class="left abstand_rechts box" style="margin-top: 0.3em;" /></a><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch')); ?>?format=mobile"><br />
	Cocktailkarte erstellen</a> mit ausgewählten Rezepten, z.B. aus deiner
	Hausbar.</li>
</ul>
</div>