<div class="content">
<h2>Impressum</h2>
<h3 class="pink">Anschrift</h3>
<div>Thomas Bachmann<br />
Kleiststraße 21<br />
70197 Stuttgart<br />
Deutschland</div>
<h3 class="pink">Betreiber</h3>
<div><a href="http://www.thobach.de"
	title="Webseite von Thomas Bachmann">Thomas Bachmann</a></div>
<h3 class="pink">E-Mail</h3>
<div><img src="<?php print $this->baseUrl(); ?>/img/email.png"
	alt="E-Mail" title="E-Mail" style="height: 16px; vertical-align: top" />
<a href="mailto:info@thobach.de">info@thobach.de</a></div>
<h3 class="pink">Telefon</h3>
<div><img src="<?php print $this->baseUrl(); ?>/img/telefon.png"
	alt="Telefon" title="Telefon" style="height: 16px; vertical-align: top" />
0711 - 935 08 58</div>
<div style="float: left; clear: both; margin-top: 20px"></div>
<h3 class="pink">Entwickler-Blog</h3>
<div><a href="http://blog.cocktailberater.de/">cocktailberater</a></div>
<h3 class="pink">Projektmanagement</h3>
<div><a href="http://code.google.com/p/cocktailberater/">cocktailberater
bei googel code</a><br />
<a href="http://ohloh.net/p/cocktailberater">cocktailberater bei
ohloh</a><br />
<a href="http://www.facebook.com/cocktailberater">cocktailberater auf
facebook</a><br />
<a href="http://twitter.com/cocktailberater">cocktailberater auf
twitter</a></div>
<h3 class="pink">cocktailberater Version</h3>
<div><?php print APPLICATION_VERSION; ?> (<?php print SVN_REVISION; ?>)</div>
<h3 class="pink">ZendFramework Version</h3>
<div><?php print Zend_Version::VERSION; ?></div>
<h3 class="pink">PHP Version</h3>
<div><?php print phpversion(); ?></div>
<h3 class="pink">Umgebung</h3>
<div><?php print APPLICATION_ENV; ?></div>
</div>
