<?php print $this->partial('template/portal_nav.phtml'); ?>
<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index'
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
?></p>
<h2 style="margin-bottom: 0;">Portal</h2>
<?php // print $this->partial('template/community.phtml'); ?>
<h3 style="margin-top: 0.1em;">Party Helferlein</h3>
<?php print $this->partial('template/hausbar.phtml'); ?>
<h3>Barkunde</h3>
<?php print $this->partial('template/barkunde.phtml'); ?>
</div>
