<?php print $this->partial('template/portal_nav.phtml'); ?>
<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Party Helferlein',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'hausbar',
		            	'pages'      => array(
				            array(
				                'label'      => 'Rezepte aus der Hausbar',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'meine-hausbar-mixen'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
?></p>
<h2 style="margin-bottom: 0;">Rezepte aus der Hausbar</h2>
<?php if(count($this->bar->getPossibleRecipies())>0){?>
<p class="abstand_unten">Die folgenden Rezepte kannst du mit deinen vorhanden Zutaten mixen:</p>
<?php foreach($this->bar->getPossibleRecipies() as $recipe){
	echo $this->cocktailPreview ($recipe);
}?> <?php } else { ?> <p class="abstand_unten">Mit den angegeben Zutaten lassen sich leider keine
Rezepte aus der cocktailberater Datenbank mixen.</p><?php } ?>
<p style="clear: left;">Du hast folgende Zutaten angegeben: <?php
if(count($this->bar->getPossibleRecipies())>0){
	$ingredients = array();
	foreach($this->bar->getIngredients() as $ingredient){
		$ingredients[] = $ingredient->name;
	}
	print implode(', ',$ingredients);
} else {
	print 'keine';
}
?>.</p>
<form id="ingredient2bar" name="ingredient2bar" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=html">
<input
	style="margin-top: 1em; margin-bottom: 1em;" type="submit" class="medium-button right"
	value="zurück zum Inventar" name="reset_ingredient2bar" /></form>
</div>
