<?php print $this->partial('template/portal_nav.phtml'); ?>
<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Party Helferlein',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'hausbar',
		            	'pages'      => array(
				            array(
				                'label'      => 'Hausbar',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'meine-hausbar'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
?></p>
<h2 style="margin-bottom: 0;">Hausbar</h2>
<?php print $this->notice($this->message); ?>
<p>Wenn du alle deine vorhandenen Zutaten angibst, 
kann der cocktailberater ermitteln, welche Rezepte du damit mixen kannst.</p>
<form id="ingredient2bar" name="ingredient2bar" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar-mixen')); ?>?format=html"><?php 
	$ingredientCategories=Website_Model_IngredientCategory::getIngredientCategories();
	foreach($ingredientCategories as $ingredientCategory){
		?>
<p class="pink clear" 
style="margin-bottom: 0.2em; font-weight: normal; margin-top: 1em;">Zutaten
 der Kategorie &quot;<?php print $ingredientCategory->name; ?>&quot; <span 
 class="link pointer category_<?php print $ingredientCategory->id; ?>_select"
 onclick="dojo.query('.category_<?php print $ingredientCategory->id; ?>').forEach(function(e){ e.checked=true; }); dojo.query('.category_<?php print $ingredientCategory->id; ?>_select').toggleClass('hide');">(alles auswählen)</span><span 
 class="link pointer category_<?php print $ingredientCategory->id; ?>_select hide" id="category_<?php print $ingredientCategory->id; ?>_unselect"
 onclick="dojo.query('.category_<?php print $ingredientCategory->id; ?>').forEach(function(e){ e.checked=false; }); dojo.query('.category_<?php print $ingredientCategory->id; ?>_select').toggleClass('hide');">(alles abwählen)</span></p>
<ul class="clear noBullet two_column" style="margin-top: 0.5em; margin-left: 0;">
<?php
$ingredients=Website_Model_IngredientCategory::getIngredientsByCategory($ingredientCategory->id,true);
foreach($ingredients as $ingredient){
	if ($this->bar->hasIngredient(Website_Model_CbFactory::factory('Website_Model_Ingredient',$ingredient->id))) {
		$checked='checked="checked"';
	} else {
		$checked='';
	}
	print stripslashes("<li style=\"margin-bottom: 0.4em; -webkit-column-break-inside: avoid; -webkit-break-inside:avoid-column; break-inside: avoid-column;\">".
			"<input type=\"checkbox\" name=\"ingredient2bar[]\" class=\"category_{$ingredientCategory->id}\" ". 
			"value=\"$ingredient->id\" $checked id=\"ingredient_{$ingredientCategory->id}_{$ingredient->id}\" /> ".
			"<label style=\"-webkit-column-break-inside: avoid; -webkit-break-inside:avoid-column; break-inside: avoid-column; \" for=\"ingredient_{$ingredientCategory->id}_{$ingredient->id}\">$ingredient->name</label>".
			"</li>");
}
?>
</ul>
<hr style="visibility: hidden; width: 50%;" />
<?php
	}
	?> <input style="margin-top: 1em; margin-bottom: 1em;" class="medium-button right" type="submit"
	value="Was kann ich damit mixen?" name="submit_ingredient2bar" /> <input
	style="margin-top: 1em; margin-bottom: 1em;" type="submit" class="small-button left"
	value="zurücksetzen" name="reset_ingredient2bar" /></form>
</div>
