<div class="content">
<p class="left" style="margin: 1em 0 1em 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
                'pages'      => array(
                    array(
                        'label'      => 'Party Helferlein',
                        'module'     => 'website',
                        'controller' => 'portal',
                        'action'     => 'hausbar',
                    	'pages'      => array(
		                    array(
		                        'label'      => 'Hausbar',
		                        'module'     => 'website',
		                        'controller' => 'portal',
		                        'action'     => 'meine-hausbar-mixen'
		                    )
		                )
                    )
                )
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<h2>Hausbar</h2>
<?php if(count($this->bar->getPossibleRecipies())>0){?>
<p class="abstand_unten">Die folgenden Rezepte kannst du mit deinen vorhandenen Zutaten mixen:</p>
<?php foreach($this->bar->getPossibleRecipies() as $recipe){
	echo $this->cocktailPreview ($recipe);
}?> <?php } else { ?> Mit den angegeben Zutaten lassen sich leider keine
Rezepte aus der cocktailberater Datenbank mixen. <?php } ?>
<p style="clear: left;">Du hast folgende Zutaten angegeben: <?php
$ingredients = array();
foreach($this->bar->getIngredients() as $ingredient){
	$ingredients[] = $ingredient->name;
}
print implode(', ',$ingredients)
?>.</p>
<form id="ingredient2bar" name="ingredient2bar"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=mobile"
	method="post"><input style="margin-top: 1em; margin-bottom: 1em;"
	type="submit" value="zurück zum Inventar" name="submit_ingredient2bar" /></form>
</div>