<div class="content">
<p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;">Sie sind hier: <?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Party Helferlein',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'hausbar',
		            	'pages'      => array(
				            array(
				                'label'      => 'Cocktailkarte',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'mein-cocktailbuch'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<h2 style="margin-bottom: 0">Cocktailkarte</h2>
<p class="abstand_unten">Wähle die gewünschten Cocktails für deine Cocktailkarte aus:</p>
<form id="recipe2menu" name="recipe2menu" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch-erstellen')); ?>?format=mobile">
<?php foreach($this->recipes as $recipe){ 
	// selectable
	$this->cocktailPreview($recipe,null,true,$this->menu->listRecipes());
} ?><hr style="clear: both; visibility: hidden;" /><input style="margin-top: 1em; margin-bottom: 1em; clear: both;" class="medium-button right" type="submit"
	value="Cocktailkarte erstellen" name="submit_recipe2menu" />
</form>
</div>
