<div class="content">
<h2>Rezepte aus der Hausbar</h2>
<?php if(count($this->bar->getPossibleRecipies())>0){?>
<p class="abstand_unten">Die folgenden Rezepte kannst du mit deinen vorhanden Zutaten mixen:</p>
<?php foreach($this->bar->getPossibleRecipies() as $recipe){
	echo $this->cocktailPreview ($recipe);
}?> <?php } else { ?> <p class="abstand_unten">Mit den angegeben Zutaten lassen sich leider keine
Rezepte aus der cocktailberater Datenbank mixen.</p><?php } ?>
<p style="clear: left;">Du hast folgende Zutaten angegeben: <?php
if(count($this->bar->getPossibleRecipies())>0){
	$ingredients = array();
	foreach($this->bar->getIngredients() as $ingredient){
		$ingredients[] = $ingredient->name;
	}
	print implode(', ',$ingredients);
} else {
	print 'keine';
}
?>.</p>
<form id="ingredient2bar" name="ingredient2bar" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=<?php print $this->format; ?>">
<input
	style="margin-top: 1em; margin-bottom: 1em;" type="submit" class="pink right"
	value="zurück zum Inventar" name="reset_ingredient2bar" /></form>
</div>
