<?php if($this->format=='html') { print $this->partial('template/portal_nav.phtml'); } ?>
<div class="content">
<p class="breadcrumb">
<?php if($this->format=='html') { ?>Sie sind hier: <?php } ?><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Party Helferlein',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'hausbar',
		            	'pages'      => array(
				            array(
				                'label'      => 'Cocktailkarte',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'mein-cocktailbuch'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($this->format=='html') {
	echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
} else {
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
}
if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>
<h2 style="margin-bottom: 0">Cocktailkarte</h2>
<p class="abstand_unten">Wähle die gewünschten Cocktails für deine Cocktailkarte aus:</p>
<form id="recipe2menu" name="recipe2menu" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch-erstellen')); ?>?format=html">
<?php foreach($this->recipes as $recipe){ 
	// selectable
	$this->cocktailPreview($recipe,null,true,$this->menu->listRecipes());
} ?><hr style="visibility: hidden;" /><input style="margin-top: 1em; margin-bottom: 1em;" class="pink right" type="submit"
	value="Cocktailkarte erstellen" name="submit_recipe2menu" />
</form>
</div>
