<?php $format = $this->format;
if($format != 'mobile'){
	print $this->partial('template/portal_nav.phtml'); 
} 
	?><p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Community',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'community',
			            'pages'      => array(
				            array(
				                'label'      => 'Mitglieder',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'members'
				            )
		        		)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($format == 'mobile'){
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());	
} else {
	echo $this->navigation($container)->breadcrumbs();
}
?></p>
<div class="content">
<h2>Community - Mitglieder</h2>
<p>Zeige deinen Freunden, dass dir der cocktailberater gefällt!</p>
<fb:like-box profile_id="132058865565" width="410" connections="9999" stream="false" header="false"></fb:like-box>
</div>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '111381035582024', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
<h3>Activity</h3>
<fb:activity site="cocktailberater.de" width="550" recommendations="true"></fb:activity>
<h3>Friends</h3>
<fb:friendpile width="550"></fb:friendpile>
<h3>Like</h3>
<fb:like href="http://www.cocktailberater.de" width="550"></fb:like>
<h3>Like Box</h3>

<h3>Live Stream</h3>
<fb:live-stream event_app_id="132058865565" width="550"></fb:live-stream>
<h3>Login</h3>
<fb:login-button show-faces="true" width="550"></fb:login-button>
<h3>Recommendations</h3>
<fb:recommendations site="cocktailberater.de" width="550"></fb:recommendations>

<fb:board xid="titans_board" 
          canpost="true"
          candelete="false"
          canmark="false"
          cancreatetopic="true"
          numtopics="5"
          returnurl="http: //apps.facebook.com/myapp/titans/">
   <fb:title>Discuss the Titans</fb:title>
</fb:board>