<div class="content">
<h2>Mitglieder</h2>
<p class="abstand_unten">Schau dir an, wie viele Leute schon <a
	href="http://www.facebook.com/cocktailberater">Fan</a> vom
cocktailberater sind und zeige auch deinen Freunden, dass dir der
cocktailberater gefällt!</p>
<fb:like-box profile_id="132058865565" width="410" connections="9999" stream="false" header="false"></fb:like-box>
</div>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '111381035582024', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/de_DE/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>