<div class="content">
<h2>Mixtechniken</h2>
<p>Cocktails kann man <a href="#schütteln">schütteln</a>, <a href="#rühren">rühren</a>,
<a href="#stoßen">stoßen</a> , <a href="#gießen">gießen</a>, <a
	href="#blenden">blenden</a> und <a href="#bauen">bauen</a>.</p>
<h3 class="pink" id="schütteln">Schütteln <em>(shaking)</em></h3>
<h4>Der Shaker</h4>
<p>Zum Schütteln eines Cocktails gibt es drei verschiedene Shaker: den
zweiteiligen Boston-Shaker (Rührglas und Metallteil), den zweiteiligen
French-Shaker (Metall) und den dreiteiligen Cobbler-Shaker (Metall) mit
integrierten Sieb. Alle drei eignen sich gleich gut.</p>
<h4>Eiswürfel und Reihenfolge der Zutaten</h4>
<p>Wenn man nur einen Cocktail im Shaker mixt, sollte man 5-6 Eiswürfel in
den unteren (Glas-)Teil geben und dann die Zutaten der Reihe nach,
beginnend mit Sirup, Sahne, Säften und Alkohol hinzugeben. Bei zwei
Cocktails benötigt man nur 3-4 Eiswürfel, beim Boston-Shaker sollte das
Rührglas aber nicht bis ganz oben gefüllt sein. Auf keinen Fall dürfen
kohlensäurehaltige Getränke in den Shaker, sonst ist die Küche hinterher
bunt.</p>
<h4>Schütteltechniken</h4>
<p>Es gibt verschiedene Schütteltechniken, die von unterschiedlichen
Barkeepern empfohlen werden: horizontal auf Schulterhöhe oder vertikal
vor dem Oberkörper. Wichtig ist kräftig und genügend lange zu schütteln.
Das heißt 10 Sekunden bei Cocktails ohne Sirup und 20 Sekunden bei
Cocktails mit Sirup. Nur dann vermengen sich alle Zutaten gut und werden
gleichzeitig perfekt gekühlt. Der Cocktail hat die richtige Temperatur,
wenn der Metallteil bis zur Glaskante (beim Boston-Shaker) beschlagen
ist.</p>
<h4>Abgießen in das Servierglas</h4>
<p>Dann wird der Shaker mit dem größeren Teil nach unten abgesetzt und
geöffnet. Wenn sich der Boston-Shaker nicht öffnen lässt, hilft ein Stoß
an der Kante, wo sich Glas- und Metallteil verbinden. Nun wird der
Cocktail durch ein Barsieb (beim Cobbler-Shaker eingebaut) in das
vorbereitete Glas gegossen und ggf. garniert.</p>
<h4>Videoanleitung</h4>
<iframe class="youtube-player" type="text/html" width="425" height="343"
	src="http://www.youtube.com/embed/odOh2Ql1T5s?hl=de_DE" frameborder="0"></iframe>
<h3 class="pink" id="rühren">Rühren <em>(stirring)</em></h3>
<h4>Rühren bei klaren Cocktails</h4>
<p>Cocktails ohne Saft, Sahne oder Sirup werden in der Regel nicht
geschüttelt, sondern gerührt. Dadurch brechen die Eiswürfel nicht, was
den Cocktail nur kühlt und nicht verwässert. Außerdem entstehen keine
Bläschen die bei klaren Cocktails nicht erwünscht sind.</p>
<h4>Vorbereitung</h4>
<p>Da gerührte Cocktails meist nicht auf Eis serviert werden, muss das
Glas - meist eine Cocktailschale - vorher gekühlt werden. Dies erreicht
man am besten, indem man das Glas mit Eiswürfeln füllt und Wasser bis
zum Rand hinzugibt. Bevor man den Drink dann in das Glas gibt, leert man es aus.</p>
<h4>Rühren und Abgießen</h4>
<p>Als nächstes füllt man sein Rührglas zu drei Viertel mit Eis und gibt die
Zutaten hinzu. Mit der Rückseite des Barlöffels rührt man den Cocktail
dann 10 Mal und gießt ihn schließlich durch ein Barsieb in das leere,
gekühlte Glas.</p>
<h4>Videoanleitung</h4>
<iframe class="youtube-player" type="text/html" width="425" height="343"
	src="http://www.youtube.com/embed/9y9QwDMdfPY?hl=de_DE" frameborder="0"></iframe>
<h3 class="pink" id="stoßen">Stoßen <em>(muddling)</em></h3>
<h4>Verwendung und Art des Stößels</h4>
<p>Cocktails wie der Mojito oder Caipirina werden
gestoßen. Das heißt Früchte wie Limetten oder Minzeblätter werden in das
Servierglas gegeben und mit einem Stößel zerdrückt. Dabei gibt es
verschiedene Arten von Stößeln, einige haben Zacken am unteren Ende und
sind für Limetten geeignet, andere sind flach und für Minzeblätter
geeignet, da sie das bittere Chlorophyll nicht in den Cocktail bringen.</p>
<h4>Videoanleitung</h4>
<iframe class="youtube-player" type="text/html" width="425" height="264"
	src="http://www.youtube.com/embed/QOsuJYvHIJg?hl=de_DE" frameborder="0"></iframe>
<h3 class="pink" id="gießen">Hin- und Hergießen <em>(roll)</em></h3>
<p>Einige Varianten des Bloody Mary oder Tequila Sunrise werden nicht
gerührt und nicht geschüttelt, sondern vor und zurück gegossen. Dazu
benötigt man zwei Rührgläser. Alle Zutaten werden in das erste Glas
gegeben und dann vorsichtig in das zweite Glas gegossen. Das ganze
passiert 5-6 Mal hintereinander und verwässert den Cocktail nicht und
fügt keine Luftbläschen hinzu.</p>
<h3 id="blenden">Blenden <em>(blend)</em></h3>
<h4>Fozen Cocktails &amp; Smoothies</h4>
<p>Frozen Cocktails oder Cocktails mit Fruchtstücken werden oft im
Blender zubereitet. Sie werden dadurch sehr cremig und eiskalt. Dazu
werden alle Zutaten zusammen mit Eiswürfeln in einen Blender gegeben,
auf höchster Stufe für ca. 10 Sekunden gemixt und in das Cocktailglas gegeben.</p>
<h4>Videoanleitung</h4>
<p>Am Beispiel eines Piña Colada wird hier gezeigt, wie ein Blender
verwendet wird.</p>
<iframe class="youtube-player" type="text/html" width="425" height="343"
	src="http://www.youtube.com/embed/cqNiIlfdpJc" frameborder="0"></iframe>
<h3 class="pink" id="bauen">Bauen <em>(build)</em></h3>
<h4>Schicht auf Schicht</h4>
<p>Cocktails wie der Tequila Sunrise oder Shooter wie der B52 werden
gebaut. Das heißt die Zutaten werden der Reihe nach in Schichten direkt
in das Cocktailglas gegeben. Das Ziel ist meist, dass man die Schichten
des Cocktails noch sieht und somit einen überraschenden Effekt erzielt.
Um eine solche Schicht im Shooter zu erzeugen müssen die Zutaten langsam
über den Rücken des Barlöffels in den Shooter gegeben werden. Manchmal
wird Grenadine auch am gedrehten Stiel eines Barlöffels herabgelassen.</p>
<h4>Videoanleitung</h4>
<p>Am Beispiel eines Tequila Sunrise und eines B 52 wird hier gezeigt, wie man
Cocktails baut.</p>
<iframe class="youtube-player" type="text/html" width="425" height="343"
	src="http://www.youtube.com/embed/QdnT3fpFuKc?hl=de_DE" frameborder="0"></iframe>
	<iframe class="youtube-player" type="text/html" width="425"
	height="343" src="http://www.youtube.com/embed/659t-Zf4lN8"
	frameborder="0"></iframe>
</div>
