<div>
<div class="menu_2_pre"><span class="pink">Statistik</span> <span
	class="grey smaller">wie viel wird getrunken, welche Rezepte werden
bevorzugt</span>
<div class="right">Party: <select class="margin_right">
	<option>Hawaii Party</option>
</select></div>
</div>

<div class="statistics">
<div class="clear left center"
	style="border-right: 2px dashed #DDDDDD; border-bottom: 2px dashed #DDDDDD; width: 49%; height: 200px; padding-top: 25px;">Die
beliebtesten Cocktails der Party:<br />
Hawaii Party<br />
<img class="margin_top"
	src="http://chart.apis.google.com/chart?chxs=0,676767,12&chxt=x&chs=360x100&cht=p3&chd=s0:kuvvjbUcf&chl=Tequila+Sunrise|Hurricane|Mojito|Planter's+Punch|Zombie|Lady+Killer|Mai+Tai|Pink+Dream|Sex+on+the+Beach" /></div>
<div class="left center"
	style="border-bottom: 2px dashed #DDDDDD; width: 49%; height: 180px; padding-top: 45px;">Die
beliebtesten Cocktails allerzeit<br />
<img class="margin_top"
	src="http://chart.apis.google.com/chart?chxs=0,676767,12&chxt=x&chs=360x100&cht=p3&chd=s0:kuvvjbUcf&chl=Tequila+Sunrise|Hurricane|Mojito|Planter's+Punch|Zombie|Lady+Killer|Mai+Tai|Pink+Dream|Sex+on+the+Beach" /></div>
<div class="clear left center"
	style="border-right: 2px dashed #DDDDDD; height: 304px; padding-top: 35px;">Histogramm
mit Anzahl Drinks der Party: <br />
Hawaii Party <br />
<img border="0" width="300" class="margin_top"
	src="http://3.bp.blogspot.com/_bsBsTL1TdYk/THFAfVmqifI/AAAAAAAAAa8/dsLGgvSBL3E/s320/histogramm_anzahl_drinks.png"></div>
<div class="left center"
	style="border-right: 2px dashed #DDDDDD; height: 304px; padding-top: 35px;">Histogramm
mit Anzahl Drinks der Party:<br />
Hawaii Party <br />
<img border="0" width="300" class="margin_top"
	src="http://4.bp.blogspot.com/_bsBsTL1TdYk/THFB3C-wgGI/AAAAAAAAAbk/mkEpjFKu_lc/s320/histogramm_anzahl_drinks-4.png"></div>
<div class="left center" style="height: 304px; padding-top: 35px;">Histogramm
mit Anzahl Drinks pro Party<br />
<img border="0" width="300" class="margin_top"
	src="http://2.bp.blogspot.com/_bsBsTL1TdYk/THFHgmdMCzI/AAAAAAAAAbs/5sGJDlEPNys/s320/histogramm_anzahl_drinks-5.png"><br />
Allzeit Durchschnitt: <br />
2,1 Cocktails pro Person</div>
</div>
</div>
