<?php
$format = Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html');
?>
<p>Um Barkeeper zu werden bedarf es einer Menge Wissen. Alles Wissen
rund um die Bar wird in unserer Barkunde festgehalten.</p>
<ul style="list-style-position: outside; margin-left: 1.5em;">
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'grundausstattung')); ?>?format=<?php echo $format; ?>">Barausstattung</a>
	um die erste eigene Bar einzurichten.</li>
	<li>Empfehlenswerte <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'buecher')); ?>?format=<?php echo $format; ?>">Cocktail-Bücher</a>.</li>
	<li>Andere <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'andere-seiten')); ?>?format=<?php echo $format; ?>">Cocktailseiten</a>
	mit interessanten Rezepten.</li>
	<li>Welches <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'glas')); ?>?format=<?php echo $format; ?>">Glas</a> zu welchem Cocktail?</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'manufacturer',
		'action'=>'index')); ?>?format=<?php echo $format; ?>">Hersteller</a>
	von Cocktailzutaten.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'mixtechniken')); ?>?format=<?php echo $format; ?>">Mixtechniken</a>
	damit jeder Cocktail zum Genuss wird.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'nutrition')); ?>?format=<?php echo $format; ?>">Nährwerttabelle</a>
	mit den Kalorien für alle Cocktails.</li>
	<li><a
		href="<?php print $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'authors'),null,true); ?>?format=<?php echo $format; ?>">Originalrezepte</a> von den Erfindern der Cocktails.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'utensilien')); ?>?format=<?php echo $format; ?>">Utensilien</a>
	zum Zubereiten von Cocktails.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'product',
		'action'=>'index')); ?>?format=<?php echo $format; ?>">Warenkunde</a>
	mit Beschreibungen und Rezepten.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'ingredient',
		'action'=>'index')); ?>?format=<?php echo $format; ?>">Zutaten</a> für Cocktails mit passenden Rezepten.</li>
</ul>
