<p>Die cocktailberater Community hilft den cocktailberater stets zu
verbessern. Neue Rezepte, Bewertungen, Tags/Schlagworte, Wissen für die
Barkunde etc. sorgen stets für anspruchsvolle Inhalte.</p>
<ul>
	<!-- <li>Finde heraus was der <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'cocktail-der-woche')); ?>">Cocktail
	der Woche</a> ist.</li>
	<li>Was sind eigentlich die <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'top10-drinks')); ?>">Top
	10 Drinks</a> im cocktailberater?</li> -->
	<li>Diskutiere mit über Cocktailrezepte im <a
		href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'forum'),null,true); ?>?format=<?php echo $format; ?>">Forum</a>.</li>
	<li>Schau dir an, wie viele und welche <a
		href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'members'),null,true); ?>?format=<?php echo $format; ?>">Mitglieder</a> der cocktailberater hat.</li>
</ul>
