<?php
$format = Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html');
?>
<p>Die cocktailberater Community hilft den cocktailberater stets zu
verbessern. Neue Rezepte, Bewertungen, Tags/Schlagworte, Wissen für die
Barkunde etc. sorgen stets für anspruchsvolle Inhalte.</p>
<ul class="abstand_unten">
	<li>Diskutiere mit über Cocktailrezepte im <a
		href="<?php print $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'forum'),null,true); 
			?>?format=<?php echo $format; ?>">Forum</a>.</li>
	<li>Schau dir an, wie viele und welche <a
		href="<?php print $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'members'),null,true); 
			?>?format=<?php echo $format; ?>">Mitglieder</a> der cocktailberater
	hat.</li>
	<li>Folge uns auf <a href="http://twitter.com/cocktailberater">Twitter</a>.</li>
</ul>
