<?php 
$config = Zend_Registry::get ( 'config' ) ;
?></div>
<!-- id:homepage -->
<div id="footer"><a href="<?php print $this->url(array('controller'=>'index','action'=>'index'),null,true); ?>">home</a><!--  - <a
	href="<?php print $this->url(array('controller'=>'index','action'=>'newsletter'),null,true); ?>">newsletter</a> --> - <a
	href="<?php print $this->url(array('controller'=>'portal','action'=>'index'),null,true); ?>">portal</a> - <a
	href="<?php print $this->url(array('controller'=>'index','action'=>'top10'),null,true); ?>">top10</a> - <a
	href="<?php print $this->url(array('controller'=>'index','action'=>'imprint'),null,true); ?>" title="Impressum"><img
	src="<?php print $config->paths->uri; ?>img/adresse.png" alt="Impressum"
	title="Impressum" height="10" /> impressum</a> - (c) 2009 by <a
	href="http://www.thobach.de">Thomas Bachmann</a> - <a
	href="http://validator.w3.org/check?uri=referer">XHMTL 1.0</a> - <a
	href="http://jigsaw.w3.org/css-validator/">CSS</a><br />
<!--
TODO: uncomment addthis
<a href="http://www.addthis.com/bookmark.php"
	onclick="addthis_url   = location.href; addthis_title = document.title; return addthis_click(this);"
	title="Diese Seiteeinem (Social)-BookmarkingServicehinzufügen"><img
	src="http://s9.addthis.com/button1-bm.gif" width="125" height="16"
	alt="Diese Seite einem (Social)-Bookmarking Service hinzufügen"
	style="margin-top: 2px;" /></a>
	-->
</div>
<!-- id:footer -->
</div>
<!-- id:wrapper -->
<!-- Google Analytics START -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-7324992-1");
pageTracker._trackPageview();
} catch(err) {}</script>
<!-- Google Analytics END -->
</body>
</html>
