<?php
$format = Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html');
?>
<p>Cocktailpartys benötigen ein wenig Organisation. Hier können unsere
Party Helferlein unterstützen. Die virtuelle Hausbar verwaltet Vorräte
und Rezepte, es können ansprechende Cocktailkarten erstellt werden und
Einkaufslisten aus Rezepten generiert werden.</p>
<ul class="no-bullet" style="margin-left: 0.5em; margin-top: 0.4em;">
	<li class="clear left" style="width: 14em; margin-right: 0;"><a
		href="<?php echo $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'meine-hausbar')); 
			?>?format=<?php echo $format; ?>"><img src="/img/portal/hausbar.jpg"
		alt="Mechanismus der Hausbar, erst Zutaten auswählen, dann Rezepte angezeigt bekommen"
		class="box" style="margin-top: 0.3em;" /></a>
	<p style="font-size: 1em; margin-bottom: 1em;">Gib vorhandene Zutaten in
	der <a
		href="<?php echo $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'meine-hausbar')); 
			?>?format=<?php echo $format; ?>">virtuellen Hausbar</a> an und ermittle mögliche
	Rezepte.</p>
	</li>
	<li class="left" style="width: 14em; clear: none;"><a
		href="<?php echo $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'mein-cocktailbuch')); 
			?>?format=<?php echo $format; ?>"><img src="/img/portal/karte.jpg"
		alt="3 Seiten einer Cocktailkarte" class="box"
		style="margin-top: 0.3em;" /></a>
	<p style="font-size: 1em;"><a
		href="<?php echo $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'mein-cocktailbuch')); 
			?>?format=<?php echo $format; ?>">Erstelle eine Cocktailkarte</a> mit
	ausgewählten Rezepten, z.B. aus deiner Hausbar.</p>
	</li>
	<li class="clear left abstand_unten" style="width: 14em; margin-right: 0;"><a
		href="<?php echo $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'meine-einkaufsliste')); 
		?>?format=<?php echo $format; ?>"><img
		src="/img/portal/einkaufsliste.png"
		alt="Generation einer Einkaufsliste aus angegeben Cocktails"
		class="box" style="margin-top: 0.3em;" /></a>
	<p style="font-size: 1em;"><a
		href="<?php echo $this->url(array('module'=>'website',
			'controller'=>'portal','action'=>'meine-einkaufsliste')); 
			?>?format=<?php echo $format; ?>">Erstelle eine Einkaufsliste</a> durch
	Auswählen von Cocktailzezepten.</p>
	</li>
</ul>
