<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>cocktailberater.de - Rezepte</title>
</head>
<body>
<link rel="stylesheet" type="text/css" href="<?php print $this->baseUrl(); ?>/css/screen.css"
	media="screen" />
<div id="distance"></div>
<div id="wrapper">
<div id="header"><a href="<?php print $this->baseUrl(); ?>"><img src="<?php print $this->baseUrl(); ?>/img/banner_small.png"
	alt="cocktailberater.de Banner" width="600" height="142" /></a></div>
<!-- id:header -->
<div id="homepage">