<?php 
$format = Zend_Controller_Front::getInstance()->getRequest()->getParam('format','html');
?><div class="sub_nav">
<ul class="textLeft">
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'community'),null,true); ?>?format=<?php echo $format; ?>">Community</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'cocktail-der-woche'),null,true); ?>?format=<?php echo $format; ?>">Cocktail der Woche</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'top10-drinks'),null,true); ?>?format=<?php echo $format; ?>">Top 10 Drinks</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'forum'),null,true); ?>?format=<?php echo $format; ?>">Forum</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'members'),null,true); ?>?format=<?php echo $format; ?>">Mitglieder</a></li>
	</ul></li>
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'hausbar'),null,true); ?>?format=<?php echo $format; ?>">Party Helferlein</a>
	<ul>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'login'),null,true); ?>?format=<?php echo $format; ?>">Anmelden / Login</a></li> -->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar'),null,true); ?>?format=<?php echo $format; ?>">Hausbar</a></li>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-favoriten'),null,true); ?>?format=<?php echo $format; ?>">Meine Favoriten</a></li> -->
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-cocktails'),null,true); ?>?format=<?php echo $format; ?>">Meine Cocktails</a></li> -->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch'),null,true); ?>?format=<?php echo $format; ?>">Cocktailkarte</a></li>
	</ul></li>
	<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'barkunde'),null,true); ?>?format=<?php echo $format; ?>">Barkunde</a>
	<ul>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'authors'),null,true); ?>?format=<?php echo $format; ?>">Originalrezepte</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'nutrition'),null,true); ?>?format=<?php echo $format; ?>">Nährwerte</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'glas'),null,true); ?>?format=<?php echo $format; ?>">Gläser</a></li>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'utensilien'),null,true); ?>?format=<?php echo $format; ?>">Utensilien</a></li>-->
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'mixtechniken'),null,true); ?>?format=<?php echo $format; ?>">Mixtechniken</a></li>-->
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'grundausstattung'),null,true); ?>?format=<?php echo $format; ?>">Grundausstattung</a></li>-->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'ingredient','action'=>'index'),null,true); ?>?format=<?php echo $format; ?>">Zutaten</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'manufacturer','action'=>'index'),null,true); ?>?format=<?php echo $format; ?>">Hersteller</a></li>
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'product','action'=>'index'),null,true); ?>?format=<?php echo $format; ?>">Warenkunde</a></li>
		<!-- <li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'buecher'),null,true); ?>?format=<?php echo $format; ?>">Buchempfehlungen</a></li> -->
		<li><a href="<?php print $this->url(array('module'=>'website','controller'=>'portal','action'=>'andere-seiten'),null,true); ?>?format=<?php echo $format; ?>">andere Cocktailseiten</a></li>
	</ul></li>
</ul>
</div>
