<?php 
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
$this->dojo()->enable();
?>
<div dojoType="custom.TestNameReadStore" jsId="testStore"
    url="<?php echo $this->url(array('action'=>'suggest','controller'=>'index','module'=>'website','format'=>'ajax')); ?>"
    requestMethod="get"></div>
    
<?php $this->headScript()->captureStart(); ?>
djConfig.usePlainJson=true;
dojo.registerModulePath("custom","<?php echo $this->baseUrl(); ?>/js/custom");
dojo.require("dojo.parser");
dojo.require("dojox.data.QueryReadStore");
dojo.require("dijit.form.ComboBox");
dojo.require("custom.TestNameReadStore");
<?php $this->headScript()->captureEnd(); 
$options = array(
                        'dojoType'       => array('dijit.form.ComboBox'),
                        'store'          => 'testStore',
                        'autoComplete'   => 'false',
                        'hasDownArrow'   => 'false',
                    ); 
                    ?>

<form method="post" id="suche_name"
	action="<?php print $this->url(array('controller'=>'index','action'=>'search','module'=>'website'),null,true); ?>"><fieldset><input
	type="hidden" name="selection" id="selection" value="-1" /></fieldset>
<div style="float: left; width: 122px; margin-top: 12px; padding-left: 2em;">
<fieldset><legend> <span id="legende_suchen">Cocktail: </span> </legend>
</fieldset>
</div>
<div style="float: left; width: 408px;">
<div style="float: left; margin-left: 10px; margin-top: 12px;"><?php echo $this->formText('search',null,$options); ?>
	<input type="hidden" id="search_type_value" name="search_type_value" value="name" />
<div
	style="float: left; margin-top: -2px; display: none; background-color: transparent; border: none;"
	id="search_suggest"
	onclick="document.getElementById('search_suggest').style.display='none';"></div>
</div>
<fieldset><input
	style="float: left; background-color: white; height: 58px; 137 px; margin-left: 4em;"
	name="submit" type="image"
	src="<?php print $this->baseUrl();?>/img/suchen-button.png"
	value="rezept suchen" id="search_button" /></fieldset>
</div>
<div
	style="clear: both; width: 560px; padding-top: 14px; margin-left: 100px; text-align: left">
<!-- Name --> <input id="search_type1" name="search_type" value="name" 
	checked="checked" type="radio" style="background-color: #f49ec0; vertical-align: text-top" 
	onclick="dojo.byId('search_type_value').value=this.value;" /><label
	for="search_type1">&nbsp;über Name</label> <!-- Zutat --> <input
	id="search_type2" name="search_type" value="ingredient" type="radio" 
	style="margin-left: 20px; background-color: #f49ec0; vertical-align: text-top" 
	onclick="dojo.byId('search_type_value').value=this.value;" /> <label
	for="search_type2">&nbsp;über Zutat</label> <!-- Tag --> <input id="search_type3" 
	name="search_type" value="tag" type="radio"
	style="margin-left: 20px; background-color: #f49ec0; vertical-align: text-top" 
	onclick="dojo.byId('search_type_value').value=this.value;" /> <label
	for="search_type3">&nbsp;über Schlagwort / Tag</label></div>
</form>
