<!-- search begin -->
<?php
// dojo helper
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
// enable dojo with custom module (readStore), parser, and comboBox
$this->dojo()->enable()
->registerModulePath('custom', $this->baseUrl().'/js/custom')
->requireModule('dojo.parser')
->requireModule('dojox.data.QueryReadStore')
->requireModule('dijit.form.ComboBox')
->requireModule('custom.TestNameReadStore');
// define url for autoCompletion
$autoCompletionUrl = array('module'=>'website','controller'=>'recipe','action'=>'index');
?>
<div id="testStore"></div>
<?php $this->headScript()->captureStart(); ?>
	// configure query
	djConfig.usePlainJson=true;
	// add the possibility to submit the search by pressing the ENTER key 
	function init() {
		var readStore = new custom.TestNameReadStore({url:"<?php echo $this->url($autoCompletionUrl,null,true); ?>", requestMethod:"get"},dojo.byId('testStore'));
		var search = new dijit.form.ComboBox({store:readStore, autoComplete:false, hasDownArrow:false},dojo.byId('search'));
		dojo.connect(dojo.byId("search"), 'onkeypress', function(e) {
			dojo.byId('search_backup').value = dojo.byId('search').value;
			if (e.keyCode == dojo.keys.ENTER) {
				dojo.byId('suche_name').submit(); 
			}
		});
		dojo.connect(dojo.byId("search"), 'onchange', function() {
			dojo.byId('search_backup').value = dojo.byId('search').value;	
		});
		dojo.connect(dojo.byId("search"), 'onfocus', function() {
			dojo.byId('search_backup').value = dojo.byId('search').value;	
		});
	<?php
	// only focus the search bar at the start page
	if(Zend_Controller_Front::getInstance()->getRequest()->getActionName()=='index'
		&& Zend_Controller_Front::getInstance()->getRequest()->getControllerName()=='index') { ?>
		dojo.byId("search").focus();
	<?php } ?>
	}
	dojo.addOnLoad(init);
	
<?php $this->headScript()->captureEnd(); ?>
<form method="post" id="suche_name"	action="<?php 
$searchLink = array('module'=>'website','controller'=>'recipe','action'=>'index');
print $this->url($searchLink,null,true); ?>">
<fieldset>
	<!-- hidden -->
	<legend>Rezepte:</legend>
	<!-- visible -->
	<label for="search">Cocktail:</label>
	<!-- text input w/ autocompletion -->
	<input type="text" name="search" id="search" value="">
	<input type="hidden" name="search" id="search_backup" value="">
	<!-- submit button -->
	<input type="submit" value="Suchen" id="search_button" 
		style="background-image: url('<?php print $this->baseUrl();?>/img/suchen-button.png');"
		onclick="dojo.byId('search_backup').value = dojo.byId('search').value;" />
	<!-- search options -->
	<div class="search_options">
		<!-- Name --> <input id="search_type1" name="search_type" value="name" checked="checked" type="radio" class="left" onclick="dojo.byId('search_type_value').value=this.value;" />
		<label for="search_type1">&nbsp;über Name</label> 
		<!-- Zutat --> <input id="search_type2" name="search_type" value="ingredient" type="radio" style="margin-left: 3em;" class="left" onclick="dojo.byId('search_type_value').value=this.value;" /> 
		<label for="search_type2">&nbsp;über Zutat</label> 
		<!-- Tag --> <input id="search_type3" name="search_type" value="tag" type="radio" style="margin-left: 3em;" class="left" onclick="dojo.byId('search_type_value').value=this.value;" /> 
		<label for="search_type3">&nbsp;über Schlagwort / Tag</label>
		<!-- needed in TestNameReadStore.js for selection of name, tag or ingredient -->
		<input type="hidden" id="search_type_value" name="search_type_value" value="name" />
	</div>
</fieldset>
</form>
<!-- search end -->
<hr class="abstand_oben_doppelt abstand_unten_doppelt">
