<!-- search begin -->
<form method="post" id="suche_name"	action="<?php 
$searchLink = array('module'=>'website','controller'=>'recipe','action'=>'index');
print $this->url($searchLink,null,true); ?>">
<fieldset>
	<!-- hidden -->
	<legend>Rezepte:</legend>
	<!-- visible -->
	<label for="search">Cocktail:</label>
	<!-- text input w/ autocompletion -->
	<input type="search" name="search" id="search" value="" />
	<!-- submit button -->
	<input type="submit" value="Suchen" id="search_button" />
	<!-- search options -->
	<div class="search_options">
		<!-- Name --><input id="search_type1" name="search_type" value="name" checked="checked" type="radio" class="left" />&nbsp;<label for="search_type1">über Name</label>
		<!-- Zutat --><input id="search_type2" name="search_type" value="ingredient" type="radio" class="left" />&nbsp;<label for="search_type2">über Zutat</label>
		<!-- Tag --><input id="search_type3" name="search_type" value="tag" type="radio" class="left" />&nbsp;<label for="search_type3">über Schlagwort / Tag</label>
	</div>
</fieldset>
</form>
<!-- search end -->
<hr class="abstand_unten" />
