<!-- search begin -->
<form method="post" id="suche_name"	action="<?php 
$searchLink = array('module'=>'website','controller'=>'recipe','action'=>'index');
print $this->url($searchLink,'recipes',true); ?>?format=mobile">
<fieldset>
	<label for="search">Cocktail:</label>
	<input type="text" name="search" id="search" value="" />
	<input type="submit" value="Suchen" id="search_button" />
	<div class="search_options">
		<input id="search_type1" name="search_type" value="name" checked="checked" type="radio" class="left" />&nbsp;<label for="search_type1">über Name</label>
		<input id="search_type2" name="search_type" value="ingredient" type="radio" class="left" />&nbsp;<label for="search_type2">über Zutat</label>
	</div>
</fieldset>
</form>
<!-- search end -->
<hr class="abstand_unten" />
