<?php print $this->partial('template/portal_nav.phtml'); ?>
<div class="content">
<h2>Portal</h2>
<?php print $this->partial('template/community.phtml'); ?>
<h3>Neuste Aktivitäten</h3>
<fb:activity site="cocktailberater.de" width="410" header="false" recommendations="false"></fb:activity>
</div>

<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '111381035582024', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
