<?php if($this->format=='html') { print $this->partial('template/portal_nav.phtml'); } ?>
<div class="content">
<p class="breadcrumb">
<?php if($this->format=='html') { ?>Sie sind hier: <?php } ?><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Community',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'community',
			            'pages'      => array(
				            array(
				                'label'      => 'Forum',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'forum'
				            )
		        		)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($this->format=='html') {
	echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
} else {
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
}
if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>
<h2 style="margin-bottom: 0">Forum</h2>
<h3 style="margin-top: 0.1em;">Forum auf der Facebook-Seite</h3>
<p>Wir benutzen das <a
	href="http://www.facebook.com/cocktailberater?v=app_2373072738">Forum auf unserer Facebook-Seite</a>.
Schau doch mal vorbei!</p>
<h3>Schnelles Feedback</h3>
<p class="abstand_unten">Was denkst du über den cocktailberater, was können wir verbessern?
Lass es uns wissen!</p>
<fb:comments xid="cocktailberater" simple="1" css="http://www-test.cocktailberater.de/css/fb_comments.css" numposts="100" width="410"></fb:comments>
</div>

<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '111381035582024', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/de_DE/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
