<div class="content">
<h2>Gläser</h2>
<h3 class="abstand_unten">Glaskategorien</h3>
<ul class="no-bullet">
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/longdrink.png"
		alt="Longdrinkglas" class="left"
		style="margin-top: 0.5em; margin-right: 1em;" />Das <strong>Longdrinkglas</strong>
	fasst ca. 25 cl. Es eignet sich sowohl für Longdrinks wie Rum-Cola als
	auch für Cocktails mit hohem Saft- oder Soda/Limonaden-Anteil wie
	Tequila Sunrise, Cuba Libre oder Mojito.</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/highball.png"
		alt="Highball" />Highball</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/collins.png"
		alt="Collins" />Collins</p>
	</li>
	<li>
	<p><img style="margin-top: 0.5em; margin-right: 1em;"
		src="<?php print $this->baseUrl(); ?>/img/glasses/hurricane.png"
		alt="Fancyglas" class="left" />Das <strong>Fancyglas</strong> fasst
	zwischen 30 und 50 cl. Es wird vor allem für tropische Cocktails wie
	Bahama Mama oder Swimming Pool verwendet. Seine bauchige Form und sein
	großes Fassungsvermögen macht es zu einen der beliebtesten
	Cocktailgläser unter den Gästen.</p>
	</li>
	<li>
	<p><img style=" margin-right: 1em;" class="left"
		src="<?php print $this->baseUrl(); ?>/img/glasses/cocktail.png"
		alt="Cocktailglas" />Das <strong>Cocktailglas</strong>, auch
	Cocktailschale genannt, fasst 6 bis 10 cl. Es wird für viele klare und
	frozen Cocktails verwendet. Viele Gäste sind verwundert, wenn sie einen
	Cocktail im Cocktailglas serviert bekommen, weil das Glas nur eine
	geringe Füllmenge besitzt. Um Enttäuschungen zu vermeiden sollten
	Cocktails, die im Cocktailglas serviert werden, in der Karte extra
	gekennzeichnet werden.</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/tumbler_klein.png"
		alt="Tumbler" />Tumbler klein, 20 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/tumbler_gross.png"
		alt="Tumbler" />Tumbler groß</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/irish_coffee_cup.png"
		alt="Heißgetränke" />Glas für Heißgetränke, ca. 20 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/wine.png"
		alt="Weinglas" />Stielglas</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/brandy_sniffer.png"
		alt="Schwenker" /><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/keine_ahnung_5.png"
		alt="Schwenker" />Schwenker, 4 cl</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/sekt.png"
		alt="Sektkelch" />Sektkelch, 10-20 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/champagnerfloete.png"
		alt="Champagnerflöte" />Champagnerflöte</p>
	</li>
	<li>
	<p><img src="<?php print $this->baseUrl(); ?>/img/glasses/shooter.png"
		alt="Schnapsglas" />Schnapsglas, 2-4 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/margarita.png"
		alt="Margaritaglas" />Margaritaglas, ca. 25 cl</p>
	</li>
	<li>
	<p><img
		src="<?php print $this->baseUrl(); ?>/img/glasses/sherry_glass.png"
		alt="Sherryglas, 5 cl" />Sherryglas, 5 cl</p>
	</li>
</ul>
<div class="clear"></div>
<h3 class="clear abstand_oben_doppelt">Gläserkunde</h3>
<ul>
	<li><strong>Dünne Gläser</strong> sehen zwar schick aus, zerbrechen
	aber schnell beim Abspülen oder Hinunterfallen.</li>
	<li>Besser sind Gläser mit dickem Rand und geringem <strong>Platzbedarf</strong>.
	Somit halten sie lange und nehmen auch noch wenig Platz weg.</li>
	<li>Die angegebenen Volumen entsprechen der typischen <strong>Füllmenge</strong>,
	nicht dem maximalen Fassungsvermögen.</li>
</ul>
</div>
