<?php require ("views/scripts/template/portal_nav.phtml"); ?>
<div style="float: left; width: 410px;">
<h2 style="margin-top: 0;">Portal - Gläser</h2>
<h3>Glaskategorien</h3>
<ul>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/highball.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>img/glasses/collins.png"
		alt="Longdrinkglas" />Longdrinkglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/red_wine.png"
		alt="Longdrinkglas" />Stielglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/hurricane.png"
		alt="Longdrinkglas" />Fancyglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/cocktail.png"
		alt="Longdrinkglas" />Cocktailglas / -schale</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/old_fashioned.png"
		alt="Longdrinkglas" />Tumbler</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/irish_coffee_cup.png"
		alt="Longdrinkglas" />Glas für Heißgetränke</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/red_wine.png"
		alt="Longdrinkglas" /><img
		src="<?php print $this->baseUrl(); ?>img/glasses/white_wine.png"
		alt="Longdrinkglas" />kleines / großes Weinglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/brandy_sniffer.png"
		alt="Longdrinkglas" /><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_5.png"
		alt="Longdrinkglas" />Schwenker</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_3.png"
		alt="Longdrinkglas" /><img src="<?php print $this->baseUrl(); ?>img/glasses/champagne_flute.png"
		alt="Longdrinkglas" /><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_7.png"
		alt="Longdrinkglas" />Sektkelch</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/unbekannt.png"
		alt="Longdrinkglas" />Schnapsglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/margarita.png"
		alt="Longdrinkglas" />Margaritaglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/sherry_glass.png"
		alt="Longdrinkglas" />Sherryglas</li>
	<li><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_1.png"
		alt="Longdrinkglas" /><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_2.png"
		alt="Longdrinkglas" /><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_4.png"
		alt="Longdrinkglas" /><img src="<?php print $this->baseUrl(); ?>img/glasses/keine_ahnung_6.png"
		alt="Longdrinkglas" />nicht zugeordnet</li>
</ul>
<h3>zu beachten:</h3>
<p>Dünne Gläser sehen zwar schick aus, zerbrechen aber schnell beim
Abspülen oder Hinunterfallen.</p>
<p>Besser sind Gläser mit dickem Rand und geringem Platzbedarf. Somit
halten sie lange und nehmen auch noch wenig Platz weg.</p>
</div>
</div>
