<div class="content full-width">
<p class="left breadcrumb">
<?php if($this->format=='html') { ?>Sie sind hier: <?php } ?><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Impressum',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'imprint'
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($this->format=='html') {
	echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
} else {
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
}
if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>
<h2>Impressum</h2>
<div class="attribut">Anschrift</div>
<div class="wert">Thomas Bachmann<br />
Kleiststraße 21<br />
70197 Stuttgart<br />
Deutschland</div>
<div class="attribut">Betreiber</div>
<div class="wert"><a href="http://www.thobach.de"
	title="Webseite von Thomas Bachmann">Thomas Bachmann</a></div>
<div class="attribut">E-Mail</div>
<div class="wert"><img src="<?php print $this->baseUrl(); ?>/img/email.png"
	alt="E-Mail" title="E-Mail" style="height: 16px; vertical-align: top" />
<a href="mailto:info@thobach.de">info@thobach.de</a></div>
<div class="attribut">Telefon</div>
<div class="wert"><img src="<?php print $this->baseUrl(); ?>/img/telefon.png"
	alt="Telefon" title="Telefon" style="height: 16px; vertical-align: top" />
0711 - 935 08 58</div>
<div style="float: left; clear: both; margin-top: 20px"></div>
<div class="attribut">Entwicklungs- Blog</div>
<div class="wert"><a href="http://blog.cocktailberater.de/">cocktailberater</a></div>
<div class="attribut">Projekt- management</div>
<div class="wert"><a href="http://code.google.com/p/cocktailberater/">cocktailberater bei googel code</a></div>
<div class="attribut">cocktailberater Version</div>
<div class="wert"><?php print APPLICATION_VERSION; ?> (<?php print SVN_REVISION; ?>)</div>
<div class="attribut">ZendFramework Version</div>
<div class="wert"><?php print Zend_Version::VERSION; ?></div>
<div class="attribut">PHP Version</div>
<div class="wert"><?php print phpversion(); ?></div>
<div class="attribut">Umgebung</div>
<div class="wert"><?php print APPLICATION_ENV; ?></div>
</div>
