<div class="content">
<p class="left" style="margin: 1em 0 1em 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal'
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<h2>Portal</h2>
<h3 class="abstand_unten abstand_oben">Party Helferlein</h3>
<p>Cocktailpartys benötigen ein wenig Organisation. Hier hilft die
virtuelle Hausbar zum Verwalten von Vorräten und Rezepten.</p>
<ul class="noBullet" style="margin-left: 1em;">
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=mobile"><img
		src="/img/portal/hausbar.jpg"
		alt="Mechanismus der Hausbar, erst Zutaten auswählen, dann Rezepte angezeigt bekommen"
		class="left abstand_rechts box" style="margin-top: 0.3em;" /></a><br />
	Vorhandene Zutaten in der virtuellen <a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar')); ?>?format=mobile">Hausbar</a>
	angeben und herausfinden welche Rezepte du damit mixen kannst.</li>
	<li><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch')); ?>?format=mobile"><img
		src="/img/portal/karte.jpg" alt="3 Seiten einer Cocktailkarte"
		class="left abstand_rechts box" style="margin-top: 0.3em;" /></a><a
		href="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch')); ?>?format=mobile"><br />
	Cocktailkarte erstellen</a> mit ausgewählten Rezepten, z.B. aus deiner
	Hausbar.</li>
</ul>
<h3 class="abstand_unten abstand_oben_doppelt">Barkunde</h3>
<p>Um Barkeeper zu werden bedarf es einer Menge Wissen. Alles Wissen
rund um die Bar wird in unserer Barkunde festgehalten.</p>
<ul style="list-style-position: outside;">
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'nutrition')); ?>?format=mobile">Nährwerttabelle</a> mit den Kalorien für
	alle Cocktails.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'glas')); ?>?format=mobile">Gläserkunde</a> mit den passenden Gläsern zu
	jedem Cocktail.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'utensilien')); ?>?format=mobile">Utensilien</a> zum Zubereiten von
	Cocktails.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'mixtechniken')); ?>?format=mobile">Mixtechniken</a> damit jeder Cocktail
	zum Genuss wird.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'grundausstattung')); ?>?format=mobile">Grundausstattung</a> um die erste
	eigene Bar einzurichten.</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'ingredient',
		'action'=>'index')); ?>?format=mobile">Zutaten</a> mit Beschreibungen, passenden
	Produkten und Rezepten</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'manufacturer',
		'action'=>'index')); ?>?format=mobile">Hersteller</a> mit Beschreibungen, ihren
	Produkten und Rezepten</li>
	<li><a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'product',
		'action'=>'index')); ?>?format=mobile">Warenkunde</a> mit Beschreibungen und Rezepten</li>
	<li>Empfehlenswerte <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'buecher')); ?>?format=mobile">Bücher</a> rund um das Thema Cocktails.</li>
	<li>Andere <a
		href="<?php echo $this->url(
		array('module'=>'website','controller'=>'portal',
		'action'=>'andere-seiten')); ?>?format=mobile">Cocktailseiten</a> mit interessanten
	Rezepten.</li>
</ul>
</div>
