<?php if($this->format=='html') { print $this->partial('template/portal_nav.phtml'); } ?>
<div class="content">
<p class="left breadcrumb"><?php if($this->format=='html') { ?>Sie sind hier: <?php } ?>
<?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index'
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($this->format=='html') {
	echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
} else {
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
}
if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>

<h2 style="margin-bottom: 0;">Portal</h2>
<h3 style="margin-top: 0.1em;">Community</h3>
<?php print $this->partial('template/community.phtml'); ?>
<h3>Party Helferlein</h3>
<?php print $this->partial('template/hausbar.phtml'); ?>
<h3>Barkunde</h3>
<?php print $this->partial('template/barkunde.phtml'); ?>
</div>
