<?php require ("views/scripts/template/portal_nav.phtml"); ?>
<div style="float: left;">
<h2 style="margin-top: 0;">cocktailberater - Portal</h2>
<p>Der alkoholische Drink der Woche ist:</p>
<div style="text-align: center; border: 1px solid black; width: 100px;"><img
	src="<?php print $this->picture_path; ?>recipes/1.jpg"
	style="width: 100px;" /><br />
<pre>Mojito</pre></div>
<p>Der alkoholfreie Drink der Woche ist:</p>
<div style="text-align: center; border: 1px solid black; width: 100px;"><img
	src="<?php print $this->picture_path; ?>recipes/1.jpg"
	style="width: 100px;" /><br />
<pre>Mojito</pre></div>
</div>
</div>
