<?php if($this->format=='html') { print $this->partial('template/portal_nav.phtml'); } ?>
<div class="content">
<p class="breadcrumb">
<?php if($this->format=='html') { ?>Sie sind hier: <?php } ?><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Party Helferlein',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'hausbar',
		            	'pages'      => array(
				            array(
				                'label'      => 'Einkaufsliste aus ausgewählten Rezepten',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'meine-einkaufsliste-erstellen'
				            )
			        	)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($this->format=='html') {
	echo str_replace('">','?format=html">',$this->navigation($container)->breadcrumbs());
} else {
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
}
if($this->format=='mobile') { ?> <a href="#navigation">[zur Navigation]</a><?php } ?></p>
<h2 style="margin-bottom: 0;">Einkaufsliste aus ausgewählten Rezepten</h2>
<?php
if(count($this->einkaufsliste->getIngredients())>0){ ?>
<p class="abstand_unten">Die folgenden Zutaten brauchst du für die ausgewählten Rezepte:</p>
<ul class="abstand_unten"><?php
	foreach($this->einkaufsliste->getIngredients() as $ingredient){
		
		echo '<li>'; echo $ingredient->name; echo '</li>';
	}
?></ul><?php 
} else {
	?> <p class="abstand_unten">Du hast keine Rezepte ausgewählt.</p><?php 
} ?>
<p style="clear: left;">Du hast folgende Rezepte angegeben: <?php
if(count($this->einkaufsliste->getRecipes())>0){
	$recipes = array();
	foreach($this->einkaufsliste->getRecipes() as $recipe){
		$recipes[] = $recipe->name;
	}
	print implode(', ',$recipes);
} else {
	print 'keine';
}
?>.</p>
<form id="recipe2ingredient" name="recipe2ingredient" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-einkaufsliste')); ?>?format=<?php print $this->format; ?>">
<input
	style="margin-top: 1em; margin-bottom: 1em;" type="submit" class="pink right"
	value="zurück zur Wunschliste" name="reset_recipe2ingredient" /></form>
</div>
