<div class="content">
<h2>Einkaufsliste</h2>
<?php
if(count($this->einkaufsliste->getIngredients())>0){ ?>
<p class="abstand_unten">Die folgenden Zutaten brauchst du für die ausgewählten Rezepte:</p>
<ul class="abstand_unten"><?php
	foreach($this->einkaufsliste->getIngredients() as $ingredient){
		
		echo '<li>'; echo $ingredient->name; echo '</li>';
	}
?></ul><?php 
} else {
	?> <p class="abstand_unten">Du hast keine Rezepte ausgewählt.</p><?php 
} ?>
<p style="clear: left;">Du hast folgende Rezepte angegeben: <?php
if(count($this->einkaufsliste->getRecipes())>0){
	$recipes = array();
	foreach($this->einkaufsliste->getRecipes() as $recipe){
		$recipes[] = $recipe->name;
	}
	print implode(', ',$recipes);
} else {
	print 'keine';
}
?>.</p>
<form id="recipe2ingredient" name="recipe2ingredient" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-einkaufsliste')); ?>?format=<?php print $this->format; ?>">
<input
	style="margin-top: 1em; margin-bottom: 1em;" type="submit" class="pink right"
	value="zurück zur Wunschliste" name="reset_recipe2ingredient" /></form>
</div>
