<div class="content">
<p class="left" style="margin: 1em 0 1em 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
                'pages'      => array(
                    array(
                        'label'      => 'Party Helferlein',
                        'module'     => 'website',
                        'controller' => 'portal',
                        'action'     => 'hausbar',
                    	'pages'      => array(
		                    array(
		                        'label'      => 'Hausbar',
		                        'module'     => 'website',
		                        'controller' => 'portal',
		                        'action'     => 'meine-hausbar'
		                    )
		                )
                    )
                )
            )
        )
    )
);
$container = new Zend_Navigation($pages);
echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());
?></p>
<h2>Hausbar</h2>
<p>Wenn du alle deine vorhandenen Zutaten angibst, kann der
cocktailberater ermitteln, welche Cocktailrezepte du damit mixen kannst.</p>
<form id="ingredient2bar" name="ingredient2bar" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'meine-hausbar-mixen')); ?>?format=mobile"><?php 
	$ingredientCategories=Website_Model_IngredientCategory::getIngredientCategories();
	foreach($ingredientCategories as $ingredientCategory){
		?>
<h3 class="pink"
	style="margin-bottom: 0.4em; margin-top: 1em; font-weight: normal;">Zutaten
aus der Kategorie &quot;<?php print $ingredientCategory->name; ?>&quot;</h3>
<ul class="noBullet">
<?php
$ingredients=Website_Model_IngredientCategory::getIngredientsByCategory($ingredientCategory->id,true);
foreach($ingredients as $ingredient){
	if ($this->bar->hasIngredient(Website_Model_CbFactory::factory('Website_Model_Ingredient',$ingredient->id))) {
		$checked='checked="checked"';
	} else {
		$checked='';
	}
	print stripslashes("<li style=\"margin-bottom: 0.7em;\">".
			"<input type=\"checkbox\" name=\"ingredient2bar[]\" value=\"$ingredient->id\" $checked id=\"ingredient_{$ingredientCategory->id}_{$ingredient->id}\" /> ".
			"<label for=\"ingredient_{$ingredientCategory->id}_{$ingredient->id}\">$ingredient->name</label>".
			"</li>");
}
?>
</ul>
<?php
	}
	?> <input style="margin-top: 1em; margin-bottom: 1em;" type="submit"
	value="Was kann ich damit mixen?" name="submit_ingredient2bar" /> <input
	style="margin-top: 1em; margin-bottom: 1em;" type="submit"
	value="zurücksetzen" name="reset_ingredient2bar" /></form>
</div>