<div class="content">
<h2>Cocktailkarte</h2>
<p class="abstand_unten">Wähle die gewünschten Cocktails für deine Cocktailkarte aus:</p>
<form id="recipe2menu" name="recipe2menu" method="post"
	action="<?php echo $this->url(array('module'=>'website','controller'=>'portal','action'=>'mein-cocktailbuch-erstellen')); ?>?format=html">
<?php foreach($this->recipes as $recipe){ 
	// selectable
	$this->cocktailPreview($recipe,null,true,$this->menu->listRecipes());
} ?><hr style="visibility: hidden;" /><input style="margin-top: 1em; margin-bottom: 1em;" class="pink right" type="submit"
	value="Cocktailkarte erstellen" name="submit_recipe2menu" />
</form>
</div>
