<?php $format = $this->format;
if($format != 'mobile'){
	print $this->partial('template/portal_nav.phtml'); 
} 
	?><p class="left" style="margin: 1.2em 0 0 0; font-size: 0.9em;"><?php
$pages = array(
    array(
        'label'      => 'Start',
        'controller' => 'index',
    	'module'     => 'website',
    	'action'	 => 'index',
    	'pages'      => array(
            array(
                'label'      => 'Portal',
                'module'     => 'website',
                'controller' => 'portal',
            	'action'	 => 'index',
	            'pages'      => array(
		            array(
		                'label'      => 'Community',
		                'module'     => 'website',
		                'controller' => 'portal',
		            	'action'	 => 'community',
			            'pages'      => array(
				            array(
				                'label'      => 'Mitglieder',
				                'module'     => 'website',
				                'controller' => 'portal',
				            	'action'	 => 'members'
				            )
		        		)
		            )
	        	)
            )
        )
    )
);
$container = new Zend_Navigation($pages);
if($format == 'mobile'){
	echo str_replace('">','?format=mobile">',$this->navigation($container)->breadcrumbs());	
} else {
	echo $this->navigation($container)->breadcrumbs();
}
?></p>
<div class="content">
<h2>Community - Mitglieder</h2>
<p>Zeige deinen Freunden, dass dir der cocktailberater gefällt!</p>
<fb:like-box profile_id="132058865565" width="410" connections="9999" stream="false" header="false"></fb:like-box>
</div>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '111381035582024', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/de_DE/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>