<div class="password"><h2 class="pink">Passwort vergessen?</h2>
<p>Wenn Sie ihr Passwort vergessen haben, geben Sie unten Ihre
E-Mail-Adresse an an und wir senden Ihnen ein neues Passwort zu.</p>
<form action="" method="post"><label>E-Mail-Adresse: <br />
<input type="email" /><span class="grey smaller">(z.B.
max.mustermann@tollebar.de)</span> </label> <a class="grey button" href="<?php print $this->url(array('action'=>'login')); ?>"
	 >Abbrechen</a> <input type="submit"
	value="Passwort zusenden" name="action" class="pink right" /></form>
</div>
